# Overview {-}

Aims in chronological order:

1. Hardcoding a simplified workflow for a limited set of schemes and types, at the level of Flanders, all SACs and 1 SAC.
1. Technological choices: comparing some alternatives, and updating choices in order to make improvements relative to previous states of the workflow. Do some targeted upscaling attempts to look at the effect, in order to make sure this will work to compute the entire design.
1. Transferring the functionalities to functions with appropriate arguments, and update the simplified workflow accordingly.
Meanwhile, add the infrastructure for reproducibility and efficient caching and updating (renv, targets).
1. Upscale the workflow to comprise all envisaged schemes and types at the Flemish level.
1. Define peculiar components that are still missing in this workflow, and that still need to be implemented in a final report (this POC doesn't aim to become the report, but to be the playground that will provide the essential computational workflow). Examples might be:
    - a mechanism to take in continuous updates to the base sampling frame (essentially needs a server-client based setup), and to update the distributed datasets that we use in the workflow and are derived from it.
    - the incorporation of currently already registered information during monitoring
    - shifting towards existing locations / neighbouring locations (from same or another scheme)
    - the use of a temporary design for groundwater

Overall requirements that we want to meet:

- speed
- reprocubility
- efficient dynamic updating
- metadata as inheritable attributes of R objects (such as which base data sources were used)
- relational integrity

```
# Settings

For the schemes, also recognize that a subset may exist with extra variables.
Use dummy variables for now, but make sure various types exist (repetitions within one year, once per year, continuous measurements which need multiple visits per year but only one value per year, etc.)
Also include necessary aspects for resource allocation in the sampling design, especially time investments per variable. (this may be added later)

## Setting schemes, types, variables and domains

## Setting scheme properties

## Setting data source versions



# Creating the base sampling frame and other essential starting points (datasets) to draw samples

## Creating tables for the base sampling frame (this includes spatial operations)

## Writing the base sampling frame

## Defining all inputs to draw samples

## Reading the base sampling frame (and other things), including phab-corrections



# Creating spatial sampling frames



# Drawing spatiotemporal samples, taking into account the revisit design, sample size, surplus sampling, domains

## Defining the samples

## Deriving datasets and layers for use and visualization

## Optimizing resource allocation in time and space (within or between years)


```


