rdata_set <- c(
  "schemes",
  "targetpops",
  "modules",
  "domains",
  "module_domains",
  "scheme_variableset_fieldmethod",
  "scheme_field_activity",
  "n2khab_types_expanded_properties",
  "n2khab_strata_expanded",
  "n2khab_strata",
  "n2khab_targetpops_expanded",
  "n2khab_targetpops",
  "grts_mh_n2khab_index",
  "domain_grts_n2khab",
  "stratum_grts_n2khab",
  "stratum_grts_n2khab_collapsed",
  "domain_stratum_nunits",
  "domain_type_nunits",
  "scheme_targetpop_sets",
  "module_targetpops_strata",
  "targetpops_strata",
  "field_activity_paneldesign",
  "scheme_variableset_paneldesign",
  "module_scheme_cycle_duration",
  "scheme_sampling_frame",
  "sp_samplingframes",
  "sp_samplingframe_domain",
  "mhq_sampled_types_per_domain",
  "mhq_mod_dom_scheme_type_no_sample",
  "mhq_mod_dom_type_no_sample",
  "mod_dom_scheme_ssf_stratum_nunits",
  "module_domain_schemes",
  "module_domain_scheme_typestats",
  "module_domain_scheme_stratumstats",
  "module_domain_scheme_designattr",
  "module_domain_scheme_stratum_target_sample_size",
  "module_domain_scheme_stratum_sample_size",
  "scheme_domain_stratum_spsamples",
  "scheme_domain_stratum_spsamples_sf",
  "samplinglocations_sf",
  "scheme_fag_fa",
  "scheme_domain_fag_panel_count",
  "scheme_domain_fag_panels",
  "scheme_domain_fag_panel_calendar",
  "scheme_domain_fag_panel_stratum_spsamples",
  "scheme_domain_fag_stratum_spsamples_calendar",
  "fag_grts_calendar",
  "fag_stratum_grts_calendar"
)
module_suffix <- if (length(params$active_modules) > 1) "" else {
  str_c("_", params$active_modules)
}
save(
  list = rdata_set,
  file = file.path(
    datapath,
    "binary/intermediate",
    str_c("objects", module_suffix, ".RData")
  )
)
