## Concepten

### Standplaats

Een eerste centraal begrip is de standplaats. De **standplaats** van een vegetatietype is een ruimtelijke eenheid die homogeen is in de voor planten belangrijkste milieufactoren. Het gaat dus over een *lokaal schaalniveau*, dat bijvoorbeeld overeenkomt met het schaalniveau van een 'homogene habitatvlek', en desgevallend door een kleiner proefvlak (voor gegevensinzameling) wordt vertegenwoordigd.

De standplaats kan ingedeeld worden in compartimenten. Elke **milieucompartiment** is een ruimtelijke eenheid in de standplaats die een apart deel van het standplaatsmilieu vertegenwoordigt. We onderscheiden volgende milieucompartimenten: atmosfeer, bodem, grondwater, inundatiewater, oppervlaktewater en waterbodem. Binnen elk compartiment kunnen nog subcompartimenten onderscheiden worden volgens fasen. Bijvoorbeeld binnen het compartiment bodem zijn dit de gasfase (bodemlucht), de vloeibare fase (bodemoplossing) en de vaste fase (bodempartikels).

Milieufactoren op de schaal van een standplaats noemen we **standplaatsfactoren**. Een voorbeeld hiervan is het waterpeil. Zowel in het compartiment grondwater, inundatiewater als oppervlaktewater kunnen waterpeilen gemeten worden. We weten nog niet welk waterpeil bedoeld wordt en hoe dit gemeten wordt. Om dit te specifiëren werken we met milieuvariabelen. Een **milieuvariabele** is een variabele waarvoor eenduidig vastligt hoe ze gemeten, berekend, geanalyseerd wordt geldend voor een specifiek tijdinterval en van toepassing op een concreet subcompartiment van de standplaats. 

Aan de hand van meerdere standplaatsfactoren en milieuvariabelen wordt de standplaats van een habittattype of rbb gekarakteriseerd.De set standplaatsfactoren die de standplaats van het vegetatietype kenmerkt worden ook **standplaatscondities**of **standplaatsvereisten** genoemd.Het zijn noodzakelijke voorwaarden opdat een type zou worden aangetroffen. Deze standplaatsfactoren zijn **sturend** voor het voorkomen van een vegetatietype.


### Milieuverstoringsketen

Wijzigingen aan milieufactoren kunnen van natuurlijke of antropogene oorsprong zijn. Is deze van antropgene oorsprong dan spreken we van een **milieudruk**, vaak als onmiddellijk gevolg van een maatschappelijk proces (als landbouw, verkeer, industrie, ...), en oefent een (vaak onrechtstreekse) negatieve invloed uit op natuur. Voorbeelden zijn verzuring via de lucht, eutrofiëring via het grondwater, toename overstromingsduur of -frequentie, ... 

De **milieuverstoringsketen** brengt de volledige procesketen in beeld van een milieudruk. Ze wordt traditioneel opgedeeld volgens het DPSI(R)-model en wordt daarom ook wel de **DPSIR-keten** genoemd. Toegepast voor standplaatsen is dit:

- **D**riving force: een maatschappelijk proces (landbouw, verkeer, industrie, ...).
- **P**ressure: een milieudruk (eutrofiëring via de lucht, verontreiniging via het oppervlaktewater, ...).
- **S**tate: de milieukwaliteit (en de verandering daarin), dus ter hoogte van de standplaats en te beschrijven met standplaatsfactoren.
- **I**mpact: de toestand van de levensgemeenschap ter hoogte van de standplaats.

Daarenboven staat de **R**espons voor hoe de maatschappij omgaat met de problemen die de milieuverstoring (D, P, S en I) teweegbrengt. 

Voor een uitgebreidere context verwijzen naar het [uitgebreidere document](files/030_concepten/concepten_details.pdf). 

## Terminologie

Voor een verklarende woordenlijst verwijzen we naar het [lexicon](#lexicon).

