## Referentielijsten milieudrukken en types {#reflijsten}

### Lijst van de milieudrukken

Specifieke uitleg bij de respectievelijke milieudrukken is beschikbaar als een [google spreadsheet](https://docs.google.com/spreadsheets/d/1aVUQWQlaL3k5hjuwyH-8c0lW7hjIkPz8VZbNgyMlN0A/edit?usp=sharing).

```{r message=FALSE, warning=FALSE, results='asis', echo=FALSE}
read_csv("../../data/BijlageMilieudrukken.csv") %>% 
    select(1:2) %>% 
    mutate(Milieudrukklasse = ifelse(is.na(Milieudrukklasse),
                                     "",
                                     Milieudrukklasse)) %>% 
    pandoc.table(
         split.table = Inf ,
         split.cells = c(30,50),
         justify = "left",
         caption = "(\\#tab:milieudrukken)*Lijst van de milieudrukken.*"
)
```

\FloatBarrier

### Lijst van de types

```{r message=FALSE, warning=FALSE, echo=FALSE}
milieudruk_rangschikking <-
    read_csv("../../data/Milieudruk_rangschikking.csv") %>% 
    mutate(Typeklasse = factor(Typeklasse, levels = 
                                   .$Typeklasse %>% 
                                   unique),
           Categorie = factor(Categorie, levels = c("H", "M", "L", "S", "P")))
```


```{r message=FALSE, warning=FALSE, results='asis', echo=FALSE}
# library(googlesheets)
# bestand <- gs_key("1dK0S1Tt3RlVEh4WrNF5N_-hn0OXiTUVOvsL2JRhSl78")
# bestand %>%
#     gs_read(ws=1,check.names = T) %>%
#     select(contains("geïntegr"), contains("niveau.1"), contains("Verkorte.naam")) %>%
#     rename(Vegcode = Code.geïntegreerd, Typeklasse = Groepering.niveau.1) %>% 
#     write_csv("../../data/types.csv")
read_csv("../../data/types.csv") %>% 
    select(2, 1, 3) %>% 
    semi_join(milieudruk_rangschikking) %>% 
    mutate(Typeklasse = factor(Typeklasse,
                               levels = levels(milieudruk_rangschikking$Typeklasse))) %>% 
    pandoc.table(
         split.table = Inf ,
         justify = "left",
         caption = "(\\#tab:types)*Lijst van de types, beschouwd in de MNM.*"
)
```

\FloatBarrier


