# Instrumenten voor keuzes

## Overzicht

Er bestaan heel wat verschillende milieudrukken, types^[Types: deze term gebruiken we om habitat(sub)types en regionaal belangrijke biotopen (RBB's) aan te duiden.] 
en standplaatsfactoren. Daartussen bestaan **relaties**, zoals weergegeven in Figuur \@ref(fig:prioritering):

- niet elke milieudruk beïnvloedt elke standplaatsfactor en elk type;
- deze invloeden variëren in sterkte;
- niet elke standplaatsfactor is relevant voor elk type.

De wetenschappelijke kennis die deze relaties bevat, wordt opgenomen in het zg. **conceptueel systeemschema van de standplaats**. Het ontsluit informatie met schema’s en een databank.

![(\#fig:prioritering)Het verband tussen de elementen waarvoor nadere keuzes gemaakt moeten worden in de MNM. De elementen zijn toegewezen aan een positie in de milieuverstoringsketen (P, S of I). Elk element (kadertje) vertegenwoordigt een reeks mogelijke waarden, in enkele gevallen symbolisch voorgesteld met een hoofdletter. De roze lijnen vertegenwoordigen de koppelingen tussen de respectievelijke waarden van de verschillende elementen, aangezien deze onderling samenhangen.](Prioriteringsnoden.png){width=100%}

Er zijn voor de MNM **keuzes nodig**:

- welke milieudrukken? (1)
- welke (groepen van) types? (2)
- welke standplaatsfactoren? (3)



Daarbij zal selectie (2) verschillend zijn per milieudruk (1), en zal selectie (3) verschillend zijn per milieudruk én type in kwestie. De selecties gebeuren **overkoepelend** voor de verschillende meetnetten.

De selecties worden gebaseerd op **drie afwegingskaders**, die milieudrukken, types en standplaatsfactoren rangschikken volgens criteria van beleidsrelevantie (prioritering). Zij worden op de volgende pagina's beschreven. Hun toepassingsgebied is in feite veel ruimer dan enkel de MNM.

- Het afwegingskader voor *milieudrukken (1)* betreft een **typespecifieke rangschikking van milieudrukken**, wat tevens tot een algemene rangschikking van milieudrukken leidt. Op basis van deze informatie kan tevens een doelpopulatie worden bepaald voor elke (weerhouden) milieudruk.
- Het afwegingskader voor *types (2)* is bedoeld om types te kunnen prioriteren binnen de doelpopulatie van elke milieudruk. Een centraal element is de **totaalindex** (tussen 0 en 1), die de beleidsrelevantie van een type weerspiegelt op basis van diverse achterliggende informatie.
- Het afwegingskader voor *standplaatsfactoren (3)* is onderdeel van het **conceptueel systeemschema** zelf, omdat het samengaat met de invloedrelatie tussen milieudrukken, milieucompartimenten en standplaatsfactoren.




