## Conceptueel systeemschema van de standplaats

Tekst op site beknopt houden, idealiter met wat figuren. Voorbeeld van [link](files/040_systeemschema/systeemschema_details.pdf) naar het achtergronddocument.

_Op de site-tekst van het systeemschema kan specifiek worden aangegeven dat er voor de MNM een prioritering van standplaatsfactoren gebeurt volgens de mate van rechtstreekse beïnvloeding door een milieudruk (P-proximiteit): meer rechtstreeks beïnvloed = hogere prioriteit. (waar we precies de lijn trekken, is dan onderwerp van het deel over de keuzes)_

<!-- ergens in de map background staat de vroegere systeemnota, omgezet naar markdown (zonder verdere verbeteringen) -->

<!-- tekst uit afwegingskader milieudrukken: -->

Het conceptueel systeemschema van de standplaats is een grafische voorstelling van de standplaatsfactoren die op een directe of indirecte wijze voor vegetatie relevant zijn, in de verschillende milieucompartimenten. Daarbij wordt gedifferentieerd tussen droge, natte en submerse standplaatsen (de waterhuishoudingsklasse). Bovenop deze voorstelling wordt aangeduid welke van deze standplaatsfactoren door de respectievelijke milieudrukken op een directe of indirecte wijze worden beïnvloed, samen met de richting van verandering (positief of negatief).

<!-- nog wat andere tekst, uit de notebook over selectie van standplaatsfactoren: -->

Een aantal elementen zijn onlosmakelijk met elkaar verbonden:

- habitattypes/RBB's (algemeen: *types*);
- waterhuishoudingsklasse (*1. droog tot vochtig, 2. tijdelijk tot permanent nat, 3. oppervlaktewater*): één fysieke standplaats behoort tot één waterhuishoudingsklasse;
- de milieucompartimenten die in een waterhuishoudingsklasse voorkomen (bv. bodem, waterkolom, ...);
- de standplaatsfactoren die in een milieucompartiment x waterhuishoudingsklasse voorkomen.

Het conceptueel systeemschema van de standplaats bundelt de wetenschappelijke kennis over deze linken onder de vorm van schema’s en een databank. Daarenboven bevat het ook voor elke milieudruk de aanduiding van *onder meer* die standplaatsfactoren die *rechtstreeks* door de milieudruk worden beïnvloed, én de aanduiding van het compartiment dat het eerst wordt beïnvloed. Het vormt aldus het **afwegingskader van standplaatsfactoren**.

Meer globaal betreft het de invloeden van milieudrukken in Figuur \@ref(fig:pathways) -- zie de vroegere en voorlopige [documentatie](https://drive.google.com/open?id=0B-DYcTNHFnIXNjYtalh5NEYteTg) bij het conceptueel systeemschema voor duiding bij de waterhuishoudingsklassen en milieucompartimenten:

![(\#fig:pathways)Voorstelling van de pathways voor milieudrukken. Per samenhorende groep van milieudrukken is de grafische kadervorm van het systeemschema voorgesteld. Daarbinnen telkens van links naar rechts drie waterhuishoudingsklassen, die tevens drie types van standplaatsen vertegenwoordigen: 1. droog tot vochtig, 2. tijdelijk tot permanent nat, 3. oppervlaktewater. De vakjes zelf stellen de milieucompartimenten voor.
Legende: bolletjes = standplaatsfactoren;
gekleurde lijnen = effectrelaties waarbij verandering in de ene standplaatsfactor effect heeft op verandering in de andere (op de figuur van links naar rechts);
donkerrood en donkerblauw: een positieve resp. negatieve effectrelatie / beïnvloede standplaatsfactor, die overeenkomt met een rechtstreekse invloed van de pressure in de keten (dit zijn steeds P-proxies);
lichtblauw en oranje: een positieve resp. negatieve effectrelatie / beïnvloede standplaatsfactor, die overeenkomt met een onrechtstreekse invloed van de pressure in de keten.](Pathways.png){width=100%}


