## Afwegingskader milieudrukken

Het afwegingskader voor de milieudrukken dient om *af te wegen* welke milieudrukken voor welke types nader worden beschouwd, in de MNM en eventueel ook in andere contexten van natuur- en milieu-onderzoek. Een afwegingskader is het instrument om deze selecties te doen. Het afwegingskader milieudrukken bevat:

1. een overzicht van de mate waarin **elk type**:
    - door elke milieudruk **actueel wordt beïnvloed** op niveau Vlaanderen;
    - voor elke milieudruk **gevoelig** is;
1. op basis van voorgaand overzicht, een **algemene rangschikking en indeling** van milieudrukken volgens hun relatie met types.

De actuele milieuproblematiek van elk type in Vlaanderen is gebaseerd op een expertenbevraging op INBO in 2016. De gevoeligheden van elk type zijn gebaseerd op basis van de effectenindicator en toegewezen gevoeligheden voor specifieke milieudrukken.

_Voor meer achtergrond bij het afwegingskader milieudrukken verwijzen we naar een [technisch achtergronddocument](https://drive.google.com/uc?export=download&id=0B-DYcTNHFnIXYmpEcXY2RlYzQ3M). Hier beperken we ons tot de resultaten, die het instrument vormen._

### Typespecifieke rangschikking van milieudrukken

De rangschikking is weergegeven in Figuur \@ref(fig:milieudruk_rangschikking). Deze bevat de volgende mogelijke scores ('Categorie') voor elk type en elke milieudruk:

- **H**: er is actueel een invloed met een **groot** belang in Vlaanderen, van de milieudruk op het type;
- **M**: er is actueel een invloed met een **matig** belang in Vlaanderen, van de milieudruk op het type;
- **L**: er is actueel een invloed met een **laag** -- maar nog steeds betekenisvol -- belang in Vlaanderen, van de milieudruk op het type;
- **S**: er is actueel in Vlaanderen geen *betekenisvolle* invloed van de milieudruk op het type, maar het type is wel gevoelig aan de milieudruk;
- **P**: er is actueel in Vlaanderen geen *betekenisvolle* invloed van de milieudruk op het type, en het type is *potentieel* gevoelig aan de milieudruk volgens de effectenindicator (gevoeligheid 'onbekend').

Het **belang** van een invloed hangt samen met zowel de 'gemiddelde' impact op de beïnvloede standplaatsen als het oppervlakte-aandeel van het type in Vlaanderen dat door de milieudruk wordt beïnvloed. Dit is in overeenstemming met de werkwijze in de artikel-17-rapportage. **H, M en L** staan samen voor 'betekenisvolle invloed'.

**XXXXXXX figuur milieudruk_rangschikking. In legende verwijzen naar de lijst milieudrukken en types**


### Algemene rangschikking en indeling van milieudrukken

Er is geopteerd voor een rangschikking van milieudrukken **per waterhuishoudingsklasse**. Op deze manier wordt een meer gelijkmatige vertegenwoordiging bekomen van de waterhuishoudingsklassen. De koppeling van milieudrukken met waterhuishoudingsklassen volgt uit de koppeling tussen types en waterhuishoudingsklassen in het systeemschema. Een type kan tot meer dan één waterhuishoudingsklasse behoren.

De rangschikking van een milieudruk in één waterhuishoudingsklasse is gebaseerd op de (gewogen) relatieve frequentie van types die een hoge of matige (H of M) invloed ondervinden van die milieudruk. Deze uitkomst is als getal (fractie tussen 0 en 1) weergegeven in Figuur \@ref(fig:druk_whh), en definieert de rangschikking van milieudrukken per waterhuishoudingsklasse.

**XXXXXXX figuur druk_whh. In legende verwijzen naar de lijst milieudrukken en types**

Op basis van de resultaten zijn de milieudrukken toegewezen aan een **groep a, b, c of d**, voor elke waterhuishoudingsklasse. In Figuur \@ref(fig:druk_whh) is dit te zien als de kleur van de cellen. Daarbij bevat groep a de milieudrukken met het hoogste belang en groep d deze met het laagste belang.


