## Afwegingskader types

Het afwegingskader voor de types dient om *af te wegen* welke types meer worden benadrukt, in de MNM en eventueel ook in andere contexten van natuur- en milieu-onderzoek. Een afwegingskader is het instrument om deze prioritering te doen.

De toepassing van het afwegingskader types in de MNM is **complementair** aan deze van het afwegingskader milieudrukken. Het afwegingskader milieudrukken wordt gebruikt om de doelpopulaties in eerste instantie af te bakenen. Het afwegingskader types kan dan dienen om binnen deze eerste afbakening nadere accenten te leggen (volgens beleidsrelevantie). Dit gebeurt meer specifiek per meetnet.

Het afwegingskader types integreert beleidsrelevante eigenschappen van types in één **totaalindex**. Dit maakt het een gemakkelijke basis voor rangschikking en selecties. Een volgens consensus geschikte correlatie is nagestreefd tussen de totaalindex en de volgende **type-eigenschappen**:

- Behoudsrelevantie Vlaams natuurbeleid:
    - zeldzaamheid
    - algemeenheid
    - relevante soorten
- Problematiek:
    - actueel sterke tot matige beïnvloeding door milieudrukken
    - het oordeel over de specifieke structuren en functies in 2013 (criterium in de staat van instandhouding; tot op heden bepaald volgens biotische habitatkwaliteit)
    - de status volgens de Europese Rode Lijst van habitats -- dit betreft *niet* de EU habitattypes maar een EUNIS-level-3-gebaseerde typologie.
- Beschikbaarheid abiotisch toetsingskader:
    - beschikbaarheid van een abiotisch toetsingskader voor de toestand
- Behoudsrelevantie Europees natuurbeleid:
    - Europees beschermd (habitattype of niet)
    - Europees prioritair
    - relatief belang van Vlaanderen voor instandhouding habitat in Europa (volgens G-IHD-rapport)

_Voor meer achtergrond bij het afwegingskader types verwijzen we naar een [technisch achtergronddocument](https://drive.google.com/uc?export=download&id=1JDBr2mILqj99Oaxz4FxLd4R8yTnfYsOr). Hier beperken we ons tot de resultaten, die het instrument vormen._

In Tabel \@ref(tab:typerangschikking) zijn alle types opgelijst en geordend volgens afnemende waarde van de totaalindex. Het rangnummer weerspiegelt deze volgorde.

```{r typerangschikking, results='asis', message=FALSE, echo=FALSE}
read_csv("../../data/20_type_indices_all.csv") %>% 
    mutate(Rangnummer = min_rank(Totaalindex),
           Totaalindex = round(Totaalindex, 3)) %>% 
    select(Rangnummer, Totaalindex, Vegcode, Verkorte.naam, Typeklasse) %>% 
    arrange(-Totaalindex) %>% 
    # kable(caption = "Rangschikking van types volgens afnemend beleidsbelang.") %>% 
    pandoc.table(
         split.table = Inf ,
         justify = "left",
         caption = "(\\#tab:typerangschikking)*Rangschikking van types volgens afnemend beleidsbelang.*"
)
```




