# Concrete keuzes MNM

## Afbakening van basisdoelpopulaties: selectie van types en milieudrukken {#doelpop}

De doelpopulatie van een **milieudruk** is de verzameling van **types** die door de MNM worden opgevolgd **om uitspraken te kunnen doen** over de invloed van die milieudruk (via monitoring van een geschikte standplaatsfactor). We spreken hier van *basisdoelpopulaties* omdat een verdere selectie van types mogelijk blijft tijdens het ontwerp van bepaalde meetnetten, die in dat geval de doelpopulatie zal definiëren.

De basisdoelpopulaties zijn samengesteld door het **afwegingskader milieudrukken te combineren met een aantal principes**. Door vergelijking van enkele scenario's werd een consensus bereikt over de keuze van principes en de samenstelling van de basisdoelpopulaties. De belangrijkste toegepaste **principes** zijn de volgende:

1. we laten milieudrukken 11, 14, 15 en 9.x buiten beschouwing, omdat zij ofwel (veelal) te maken hebben met vernietiging (veelal zo bij 11; geregeld ook bij 14 en 15), ofwel alleen gericht zijn op fauna (9.x), ofwel moeilijk in verband zijn te brengen met standplaatsfactoren (14, 15, en veelal ook bij 11). Zij vallen daarom buiten de scope van de MNM. We benadrukken wel dat voor deze milieudrukken een duidelijke informatienood bestaat -- 11 en 14/15 behoren typisch tot milieudrukkengroep a;
1. per waterhuishoudingsklasse:
    - milieudrukken van groep **a**: de basisdoelpopulatie bestaat uit de types die eraan gevoelig zijn (H, M, L, S of P);
    - milieudrukken van groep **b**: de basisdoelpopulatie bestaat uit de types die er betekenisvol door beïnvloed zijn (H, M of L);
    - milieudrukken van groepen **c of d**: de problematiek is beperkt tot minder types, maar is voor die types wel belangrijk. De basisdoelpopulatie bestaat uit de types die er sterk of matig door worden beïnvloed (H of M);
    - voor milieudrukkengroep **c** kan men dit eventueel uitbreiden voor specifieke milieudrukken (beleidskeuze, of in functie van kennishiaten) of types (beleidsrelevantie).
        - We doen een *pro forma* uitbreiding van de doelpopulatie voor de milieudrukken *8.1 tot 8.4 (verontreiniging)*, omwille van kennishiaten. Voor deze milieudrukken is geopteerd om de doelpopulaties *pro forma* te omlijnen als de types die er betekenisvol door beïnvloed zijn (H, M of L), waarbij we er rekening mee moeten houden dat deze inschattingen minder betrouwbaar en vermoedelijk onderschat zijn. De *precieze omlijning van de doelpopulaties voor 8.1 tot 8.4 is nader te bekijken in het kader van de meetnetontwerpen*.
        
Belangrijk om op te merken is dat door toepassing van dit principe, **een aantal bijkomende milieudrukken niet langer weerhouden blijft** (milieudrukken die geen enkel type hoog of matig beïnvloeden in Vlaanderen). Enkele scenario's om daarnaast nog verder milieudrukken te selecteren, zijn niet gevolgd. Dat zou voor heel wat types tot een aanzienlijk informatieverlies hebben geleid.

_Voor meer achtergrond bij de afbakening van doelpopulaties verwijzen we naar het [technisch achtergronddocument](https://drive.google.com/uc?export=download&id=0B-DYcTNHFnIXYmpEcXY2RlYzQ3M) van het afwegingskader milieudrukken._

**De basisdoelpopulaties zijn weergegeven in Figuur \@ref(fig:basisdoelpop-totaalwhh) -- het betreft de gekleurde cellen.**


```{r basisdoelpop-totaalwhh, echo = FALSE, fig.width = 9, fig.height=12, message=FALSE, warning=FALSE, fig.cap = "Totaalweergave van de basisdoelpopulaties -- het betreft de gekleurde cellen. Types zijn gesorteerd volgens (unieke) waterhuishoudingsklasse en dan volgens typeklasse. Milieudrukken zijn alfabetisch gesorteerd. Voor de verklaring van milieudrukken en types, zie paragraaf \\@ref(reflijsten)."}
types_whh <- read_csv("../../data/08_types_whh.csv")
types_whh2 <-
    types_whh %>% 
    group_by(Vegcode) %>% 
    mutate(AantLand = n()) %>% 
    spread(key = Waterhuishouding, value = Waterhuishouding, fill = "") %>% 
    rename(L1 = "Droog tot vochtig",
           L2 = "Tijdelijk tot permanent nat",
           L3 = "Oppervlaktewater") %>% 
    mutate(Waterhuishoudingsklasse_2 = 
               ifelse(AantLand == 1,
                                      str_c(L1, L2, L3),
                                      str_c(L1, L2, sep = " + ")
                                      )
           ) %>% 
    ungroup %>% 
    select(Vegcode, Waterhuishoudingsklasse_2) %>% 
    mutate(Waterhuishoudingsklasse_2 = factor(Waterhuishoudingsklasse_2, levels = 
                                          .$Waterhuishoudingsklasse_2 %>% 
                                          unique %>% sort %>% 
                                          .[c(1, 2, 4, 3)]
                                          ))
basisdoelpop <-
    read_csv("../../data/08_basisdoelpop.csv") %>% 
    mutate(Typeklasse = factor(Typeklasse, levels = 
                               .$Typeklasse %>% 
                               unique),
           Categorie = factor(Categorie, levels = c("H", "M", "L", "S", "P")))

basisdoelpop_whh2 <- 
    basisdoelpop %>%
    inner_join(types_whh2) %>% 
    mutate(    # sorteren van druk- en vegcode-levels
        Druk = factor(Druk,
                  levels = (distinct(., Druk) %>% 
                                mutate(Druk = as.character(Druk)) %>% 
                                arrange(Druk) %>% 
                                .$Druk)
                  ),
        Vegcode = factor(Vegcode,
                  levels = (distinct(., Waterhuishoudingsklasse_2, Typeklasse, Vegcode) %>% 
                            mutate(Vegcode = as.character(Vegcode)) %>% 
                            arrange(desc(Waterhuishoudingsklasse_2), desc(Typeklasse), desc(Vegcode)) %>% 
                            .$Vegcode)
        )
    )

basisdoelpop_whh2 %>% 
    myraster_whh2(str_c("MNM: aanduiding waarover uitspraken gewenst zijn (vragen beantwoorden)",
                        "\n(i.e. de gekleurde vakjes: doelpopulatie x milieudruk)"))
```





