## Selectie van primaire standplaatsfactoren

_Op deze site vindt u enkel de belangrijkste resultaten. Voor meer achtergrond bij de selectie van primaire standplaatsfactoren verwijzen we naar een [technisch achtergronddocument](XXXXXXX)._


### Selectie van primaire standplaatsfactor(en) per milieudruk {#stplf-mild}

Er zijn primaire en aanvullende standplaatsfactoren:

- **_Primaire standplaatsfactoren_** zijn deze waarover in eerste instantie wordt gerapporteerd, en die met het meetnet worden beoogd. Het betreft **per milieudruk** één of eventueel enkele standplaatsfactoren, waarmee we een interpretatie kunnen doen over de milieudruk. Wanneer het meerdere standplaatsfactoren betreft voor één milieudruk, zullen nadere data-analysen bepalen wat de hoofdfocus krijgt, en/of hoe meerdere standplaatsfactoren gecombineerd worden.
- _Aanvullende standplaatsfactoren_ hebben een ondersteunende functie en zijn voor het beleid van nut bij de verdere interpretatie van toestand en trend van een primaire standplaatsfactor. Ze worden meegemeten, maar de meetnetten beogen er geen specifieke uitspraak over.

De selectie van primaire standplaatsfactoren is gebeurd **op basis van het afwegingskader standplaatsfactoren, ingebouwd in het conceptueel systeemschema**, dit na vergelijking van enkele scenario's. We houden daarbij rekening met de **waterhuishoudingsklasse**, zodat we de specifieke compartimenten en standplaatsfactoren van een waterhuishoudingsklasse kunnen koppelen aan de types in elke waterhuishoudingsklasse. De koppeling met types komt aan bod in paragraaf \@ref(stplf-types).

In de MNM kijken we specifiek naar **P-proxies** [^P-proxies], zeker in een eerste periode. Die keuze is gemaakt omwille van het belang van milieudruk-informatie voor het brongerichte maatregelenbeleid, en omdat informatie over milieudrukken belangrijker is bij de bepaling van de staat van instandhouding. Voor meer informatie, zie het basisrapport [@vanderhaeghe_vraagstelling_2017]. Een **verdere subselectie** is gebeurd door:

- alleen nog die P-proxies te weerhouden die we als meest typische **vertegenwoordiger** zien van de soms ruimere set van nog beschikbare P-proxies;
- per waterhuishoudingsklasse alleen P-proxies te selecteren uit het **meest rechtstreeks door de milieudruk beïnvloede milieucompartiment**.

In Figuur \@ref() zijn de geselecteerde primaire standplaatsfactoren per milieudruk en milieucompartiment weergegeven.

**Figuur XXXXXXXXX mildr x stplf, per comp. onder elkaar te schikken.**




[^milieuvariabele]: Voor monitoring wordt elke (primaire en aanvullende) standplaatsfactor concreet gekoppeld aan de keuze van een (primaire resp. aanvullende) *milieuvariabele*, die zo gedefinieerd zal moeten zijn dat ze alle aspecten omvat van de staalname, bewaring, meetmethode, aggregatiemethode e.d. (alles wat van invloed is op de numerieke waarde). De keuze van een milieuvariabele voor een standplaatsfactor hangt samen met meerdere factoren en gebeurt voornamelijk door experten van het milieucompartiment in kwestie.

[^P-proxies]: P-proxies (P staat voor de milieudruk) zijn de volgens het conceptueel systeemschema *rechtstreeks* door een milieudruk beïnvloede standplaatsfactoren.






