---
title: "Bepaling van keuzes in de Meetnetten Natuurlijk Milieu"
author: "INBO"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
linkcolor: link.colour
citecolor: link.colour
urlcolor: link.colour
geometry: margin=1in
mainfont: "Calibri"
fontsize: 11pt
documentclass: "report"
lang: "nl-BE"
output:
  bookdown::html_book:
    theme: united
    split_by: "rmd"
    keep_md: yes
    toc: yes
    css: toc.css
    includes:
        in_header: header.html
    pandoc_args:
        - --csl
        - ../inbo.csl
  bookdown::pdf_book:
    base_format: INBOmd::inbo_rapport
    floatbarrier: subsubsection
    citation_package: none
    keep_tex: TRUE
  bookdown::pdf_document2:
    # md_extensions: +implicit_header_references
    fig_caption: yes
    pandoc_args:
        - --csl
        - ~/lib/R/library/INBOmd/inbo.csl
    keep_tex: yes
    toc: yes
    toc_depth: 3
    latex_engine: xelatex
    number_sections: true
    includes:
        in_header: header.tex
github-repo: "inbo/mnm_keuzes"
bibliography: ../mnm_keuzes.bib
link-citations: yes
description: "Onderbouwing keuzes MNM"
---


```{r setup, echo=FALSE, message=FALSE}
options(stringsAsFactors = FALSE,
        knitr.kable.NA = '')
library(knitr)
library(tidyverse)
library(vegan)
library(pander)
# library(xlsx)
opts_chunk$set(
  echo = TRUE,  # nodig ivm kadertjes
  dpi = 300
)
# functies en helpers inlezen:
source("../scripts/functies_helpers.R")
```


# Inleiding

De meetnetten natuurlijk milieu (MNM) zijn een instrument van de Vlaamse Overheid om de planning, onderbouwing, evaluatie en bijsturing van het milieugerichte, actieve natuurbeleid op niveau Vlaanderen te ondersteunen. Zij komen tot stand in een samenwerkingsverband tussen meerdere entiteiten, waarbij het INBO een trekkersrol opneemt. Een belangrijke taak van het actieve natuurbeleid bestaat er in om het kader en de maatregelen(programma’s) te voorzien opdat de milieuknelpunten voor natuur zouden worden opgelost. De beleidsondersteuning door de MNM komt tot stand via monitoring van de milieukwaliteit op standplaatsen van habitattypes en regionaal belangrijke biotopen (RBB's). Een analyse van vraag en aanbod leidde in 2017 tot het **basisrapport** van de MNM [@vanderhaeghe_vraagstelling_2017].

Om de meetnetten te kunnen ontwerpen, was een **vraagverfijning** nodig. Er dienden immers keuzes te worden gemaakt:

- over welke *milieudrukken* zijn uitspraken gewenst?
- voor welke *types* (habitattypes en RBB's) zijn deze uitspraken gewenst, afhankelijk van de milieudruk?
- van welke *standplaatsfactoren* worden hiervoor toestand en trend opgevolgd, afhankelijk van milieudruk en type?
- hoe zien we de verdeling van de geselecteerde types en standplaatsfactoren over *meetnetten*?

<!-- ```{block2, type = "exampleblock"} -->
**Op deze website zijn de volgende elementen samenvattend bijeengebracht:**

- recapitulatie van enkele concepten en van de vraagstelling;
- de instrumenten om de bovenvermelde selecties te kunnen doen;
- de gemaakte selecties;
- de opdeling in meetnetten en compartimentmeetnetten.
<!-- ``` -->







