---
title: "MNM: strategie voor steekproef, steekproefsimulatie en inferenties"
author: "Floris Vanderhaeghe"
date: "oktober 2018"
link-citations: true
linkcolor: link.colour
citecolor: link.colour
urlcolor: link.colour
geometry: margin=1in
mainfont: "Calibri"
fontsize: 11pt
documentclass: "article"
csl: ../../inbo.csl
bibliography: ../../RefsMNE_design.bib
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../doc") })
output:
  html_document:
    keep_md: TRUE
    number_sections: yes
    fig_caption: yes
    toc: TRUE
    toc_float:
      collapsed: FALSE
      smooth_scroll: FALSE
    includes:
        in_header: header.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


Hieronder de algemene benadering voor alle MNM-monitoring die op steekproeven (en niet op modellen) wordt gebaseerd. Meer meetnetspecifieke informatie staat in googlesheet.


# Principes voor steekproefstrategie en inferentie

- Elk hoofdmeetnet volgt een *aselecte* steekproefstrategie.
- Elk hoofdmeetnet volgt een *eenvoudige* steekproefopzet in ruimte en tijd. Wegens begrijpbaarheid, verwerkbaarheid, duurzaamheid.
- Kosteneffectiviteit.
- Haalbaarheid.
- Elk hoofdmeetnet hanteert een *flexibele* steekproefopzet.
    - Criterium hiervoor: inferentiewijzen kunnen op eenvoudige wijze valide blijven doorheen de tijd, niettegenstaande aanpassingen.
    - Kenmerken hierbij: aanpasbaarheid van vragen; bestand tegen aanpassing van domeinen en van steekproefkader; flexibiliteit inzake aanpasbaarheid van steekproefgrootte en het kunnen omgaan met non-response.
    - Daarom voorkeur voor equal probability designs:
        - Equal probability designs: zonodig te beschouwen per vooraf bepaald domein (maar domeinafbakening liever vermijden wegens afname van flexibiliteit).
        - Uitspraken voor (sub)domeinen gebeuren zoveel mogelijk post-hoc en zijn niet inherent aan de design (subpopulation estimations via poststratificatie).
- Afdoende ruimtelijke en temporele *dekking*
- Ruimtelijke *koppelingen*:
    - Meetnetten onderling maximaal gekoppeld (over milieucompartimenten heen)
    - Maximaal gekoppeld met meetnet biotische habitatkwaliteit
- De steekproefopzet laat een schatting toe van de *variantie* van de doelparameter.
- Toestandsbeschrijvingen (spatiotemporeel) gebeuren *design-based en model-assisted*:
    - design-based wegens objectiviteit en validiteit (belang van toestand in MNM)
    - model-assisted om de precisie en accuraatheid van global quantity estimators te verhogen (regression estimator gebruiken)
- Trendbeschrijvingen (spatiotemporeel) gebeuren:
    - *model-based* voor de temporele component (procesbeschrijving)
    - *design-based* voor de spatiale component (consistent met toestandsbeschrijving)
    
    Met andere woorden, we doen uitspraken over het data-genererende temporele *proces*, concreet voor de spatiaal *gerealiseerde* doelpopulatie.


# Domeinen, subpopulaties, doelparameters en beoogd type van uitspraken

## Afbakening doelpopulatie en domeinen

Spatiaal:

- De *domeinen* voor uitspraken in een meetnet zijn enerzijds de volledige Vlaamse doelpopulatie (= locaties van alle beoogde types in een meetnet) en anderzijds het deel van de doelpopulatie binnen het SBZ-H netwerk. Voor de (niet-verplichte) bijdrage aan de Europese rapportage, geldt tevens het domein 'Atlantisch Vlaanderen'. Deze domeinen liggen voor langere tijd vast, maar zijn niet absoluut constant.
    - we verkiezen om de domeinen niet te laten meespelen in de design, om flexibel te blijven naar de toekomst.
    - in eerste instantie dus abstractie maken van het domein 'SBZ-H-netwerk' en evalueren of de Vlaamse set afdoende informatie geeft voor het SBZ-H-netwerk (subpopulatieschatting via poststratificatie, zie verder). Immers komen de meeste habitatlocaties voor binnen SBZ-H.
- De uitspraken gebeuren gedifferentieerd voor verschillende groepen van types: zg. typegroepen (grootte-orde van een vijftal groepen). Types in een typegroep zijn volgens verwachting nauwer met elkaar 'verwant' inzake de waarde voor beschouwde doelvariabele. De afbakening van typegroepen verschilt per meetnet, en zal langere tijd aan discussie onderhevig blijven (en dus vatbaar blijven voor aanpassing). Hun ruimtelijke verspreiding verandert doorheen de tijd. Het is op niveau van de typegroepen dat een bepaalde precisie wordt nagestreefd.
    - Afgezien van de mogelijks mindere precisie op typeniveau, moet het steeds mogelijk blijven om ook per type nog inferenties te doen, omdat die vraag ook blijft.
- Het is wenselijk om types welgekozen te wegen in de typegroepen, waarbij de gewichten de informatiebehoefte beter tegemoet komen dan de loutere ruimtelijke oppervlakteverdeling tussen types in een typegroep. Bv. op basis van rangschikking volgens beleidsbelang van de types. Daarbij moet ook dit aspect bestand zijn tegen wijzigingen in voorkeuren in de toekomst. We nemen daarom als standaard voor een flexibele design *gelijke* gewichten aan tussen de types in de inferentie over een typegroep. Dus het betreft *gelijke aandelen* van de types in schatters voor een typegroep.

Temporeel:

- Voor toestandsbeschrijving standaard uitgaan van 6 jaar. Is de lengte van één natuurbeleidscyclus.
- Voor trendbeschrijving kijken naar perioden van 12 of 24 jaar (scenario's).
- In beide gevallen is per meetnet aan te geven welke periode binnen het jaar relevant is, en dus de temporele doelpopulatie af te bakenen.

## Doelparameters en beoogd type van uitspraken

Alle vermelde doelparameters betreffen 'global quantity estimators': zij vatten een eigenschap samen van de gerealiseerde Vlaamse doelpopulatie, niet van een superpopulatie.

De centrale analysen voor MNM zijn:

- kwantitatieve beschrijving **toestand**: schatting van spatiotemporeel *gemiddelde* / *SCDF* (kwantielen), met *betrouwbaarheidsinterval*, voor een milieuvariabele in een domein (de vlekken van bepaalde types in Vlaanderen, de vlekken van bepaalde types in SBZ-H-netwerk), over één bepaalde periode (standaard: één programmaperiode van zes jaar).
- kwantitatieve beschrijving **trend**: berekening van de (spatiaal gemiddelde) *meerjarentrend* voor een milieuvariabele in een domein (de vlekken van bepaalde types in Vlaanderen, de vlekken van bepaalde types in SBZ-H-netwerk), over langere tijd (bv. 12, 24 jaar). Met een *toets* die aangeeft of deze trend (gedefinieerd als gemiddelde jaarlijkse verandering) verschilt van nul (indien een lineaire of multiplicatieve benadering zinvol is).

Uitbreiding op bovenstaande toestandsbeschrijving:

- Een variant is dat de 'milieuvariabele' de overschrijding voorstelt van een (evt. locatiespecifieke) drempelwaarde (indien beschikbaar). Hiervan opnieuw schatting van spatiotemporeel gemiddelde / SCDF, met betrouwbaarheidsinterval.
- Een hierop voortbouwende variant is om het percentage van de overschrijding te schatten dat groter is dan nul (+ betrouwbaarheidsinterval) -- ervan uitgaand dat dat de ongunstige situatie voorstelt -- en te toetsen of dit percentage significant groter is dan 25%.

Verdere nodige uitspraken staan in paragraaf 9.3 van het [basisrapport](https://dx.doi.org/10.21436/inbor.13086011). Zie ook mail 1/6/18. We zien ze niet als sturend voor het ontwerp. De analyseroutines zijn wel te ontwerpen.

[Instelwaarden](https://docs.google.com/spreadsheets/d/1IMlLh9EPPRLLoDNWkDzbVJU2cVvst7C8NyJRM2NvujM) zijn reeds voor sommige milieuvariabelen beschikbaar.


# Steekproefstrategie

## (Non)-stratificatie, typegroepen en steekproefstrategie

Gelijkwaardig willen belichten van types en uitspraken doen over typegroepen: het is verleidelijk om een gestratificeerde design op te zetten (voor types en/of typegroepen). Dit beperkt echter flexibiliteit naar de toekomst toe; het maakt bemoeilijkt de inferentie bij o.a. veranderingen in de doelpopulatie en wijzigingen in de keuze van subpopulaties (zoals typegroepen) waarvoor inferentie is gewenst.

Domeinschatting (bv. SBZ-H) gebeurt om dezelfde reden door subpopulatieschatting via poststratificatie: gewichten worden post-hoc aangepast (binnen de inferentie), rekening houdend met de gekende poststrata-groottes en niet a priori (via stratificatie in design). Zo vermijden we inflexibiliteit.

Ook het toepassen van een staged design brengt, hoewel mogelijks kostenefficiënter, extra zorgen en beperkingen mee door ongelijke (maar niet in de tijd constante) sampling weights, de evolutie van de doelpopulatie in de tijd (en dus herzien van de steekproef) en de interferentie met een rotating panel design.

Kortom, substructuur in een meetnet zorgt voor beperkingen of complicaties later. Daarbij komt ook dat zowel typegroepen als types evolueren in hun definitie. Zie onder meer @overton_desirable_1996 en @manly_sampling_2014.

Uitgaande van de eerder gestelde principes zijn er maar twee robuuste en relatief eenvoudige alternatieven voor de opdeling van de meetnetten, die een spatiaal gebalanceerde en voorts spatiaal ongestructureerde steekproef gemeen hebben:

- het idee van wegingen van types laten varen, en genoegen nemen met een equiprobable sample voor de hele doelpopulatie van een meetnet. Dit impliceert dat inferentie over typegroepen en types gebeurt als subpopulatieschattingen (via poststratificatie), en dat de precisies hiervan volledig van de *total* sample size afhangen, en niet op maat gestuurd worden.
    - dit is vrijwel zeker goedkoper, maar heeft een vrij beperkt toepassingsgebied en biedt weinig controle over precisie van subpopulation estimates.
- een lage-precisie-meetnet ontwerpen voor elk type, wat een estimator per type oplevert. Een samengestelde estimator voor de typegroep kan dan post-hoc worden berekend als een (al dan niet gelijk gewogen) gemiddelde van de types. De variantie van deze afgeleide estimator is functie van de typespecifieke varianties. De steekproefgrootte per type heeft op die manier doorwerking in de precisie van uitspraken per typegroep, wat de trigger is om de typespecifieke steekproefgroottes te kiezen (evenredig met de typespecifieke standaardafwijking en met finite population correction).
    - dit heeft het voordeel van onafhankelijkheid tussen de verschillende meetnetten, en geeft beter zicht op concrete types
    - indien nodig kan een type (ook in een later stadium) intensiever worden gemeten zonder dat dit inferentieprocedures compliceert.
    - dit laat tevens toe om voor bepaalde types de populatie-eenheden anders in te vullen (bv. plassen)
    - bemerk dat hoe meer types een typegroep telt, hoe minder nauwkeurig de typespecifieke uitspraak zal zijn en hoe goedkoper de totale opzet. Er wordt immers gestuurd op precisie op niveau van de typegroep.

Belangrijk bij een zo breed inzetbare steekproefstrategie is dat de efficiëntie (hoge precisie) bekomen wordt door 1) de spatiale balancering, 2) een goede temporele spreiding (revisit design) en 3) het gebruik van auxiliary information door regression estimators te gebruiken (model-assisted design).



## Spatiaal

GRTS als basis voor een goede ruimtelijke spreiding en voor maximaliseren van de koppeling met meetnet biotische habitatkwaliteit.

- Celgrootte van 32 m² als basis voor de populatie-eenheid van terrestrische en semi-terrestrische types (overnemen grid van meetnet biotische habitatkwaliteit).
- Segmenten van waterlopen en individuele plassen zijn de populatie-eenheden voor aquatische types, maar dit is compatibel met een GRTS-trekking.

<!-- Te overwegen opties: -->

<!-- - GRTS (equal probability): beste ruimtelijke dekking, grootste eenvoud en flexibiliteit, maar vermoedelijk minder kosteneffectief -->
<!-- - two-stage GRTS met per meetnet geoptimaliseerde grootte van de PSU's (primary sampling units). De PSU's zijn dan hogere-orde rastereenheden van het GRTS-grid. -->
<!--     - voordeel ten opzichte van ruimtelijk variërende geografische eenheden (PSU's zoals gemeenten, fysische systeemeenheden, ecodistricten, ...) op maat van elk meetnet, is de grotere consistentie en overlap tussen de meetnetten, de gelijke ruimtelijke dekking per PSU en de eenvoud om te up- of downsizen (ontwerpscenario's) volgens de noden. -->
    
GRTS master sample gebruiken van het meetnet biotische habitatkwaliteit om de koppeling te maximaliseren
    - De doelpopulatie (steekproefkader) van een concreet meetnet (bv. verdroging via grondwater) is een subset hiervan: combinaties van Vlaamse X, Vlaamse Y en de voorkomende types (beperkt tot deze die we voor het meetnet viseren). Eén XY-coördinaat kan meerdere types bevatten.

<!-- Aandachtspunt: de aquatische types. Minstens voor atmosferische meetnetten wordt dezelfde milieuvariabele beoogd voor terrestrische en aquatische types. Het heeft daarom meerwaarde om ook de aquatische types binnen dezelfde opzet mee te nemen, om de uitspraken los van aquatisch of terrestrisch te kunnen doen (want ook de atmosferische typegroepen zullen gemengde terrestrisch-aquatische groepen zijn). Het verschil met terrestrisch zit dan vooral in de terreinprocedure, gegeven een getrokken 32 m² cel: -->

<!-- - stilstaande wateren: de volledige plas is habitat indien er habitat aanwezig is in de plas. Dus de gehele plas wordt door de geselecteerde gridcel vertegenwoordigd. In het kader van inferenties zijn dan voor plassen met meerdere geselecteerde cellen twee opties mogelijk (beide hebben volgens Luc meerwaarde): -->
<!--     - ofwel de observatie slechts één keer tellen en dus alle plassen even sterk laten wegen. Dezelfde benadering moet dan gebeuren in de bepaling van de populatiegrootte (mbv steekproefkader) bij poststratificatie. -->
<!--     - ofwel de observatie voor elke geselecteerde gridcel laten meetellen, en dus het oppervlakte-aspect laten meespelen. -->
<!-- - stromende wateren: segmenten uit het steekproefkader selecteren die overlappen met een geselecteerde gridcel. De observaties van deze segmenten zijn te koppelen met de gridcel(len) die zijn geselecteerd. -->
    
Koppeling meetnet biotische habitatkwaliteit:

*XXX nog bekijken hoe in habitatkwaliteit concreet is samengespoord met initiatieven van specifieke typeklassen (duinen, ...), om te evalueren hoe groot onze afwijking daarvan zal zijn. Default reflex: niets aan te doen. Tijdelijke tussenoplossingen (cf. overgangsfase grondwatermeetnet): E[schatter] heeft ongekende bias*

## Temporeel


Noot: er is geen temporele design van toepassing indien volledige tijdsreeksen beschikbaar (cf. grondwaterstanden met loggers). Er blijft in dat geval *wel* onzekerheid op trendschatters vermits deze model-based worden geschat.

- systematisch samplen (bv. jaarlijks, maandelijks). Nadeel is wel mogelijke onderschatting van de variantie, mede afhankelijk van hoe de temporele doelpopulatie is gedefinieerd.
- minstens jaarlijks data verzamelen, want:
    - jaarlijks een gelijkaardige inspanning leveren: goede spreiding bekomen om trendvorm te kunnen bekijken + goede spreiding voor spatiotemporele toestandsbepaling
    - afhankelijk van de milieuvariabele is de aggregatie op jaarniveau de basis voor analyse en inferenties. Bv. XG3's
- indien significante variatie optreedt binnen een jaar (cf. resultaten van modelwerk): het effect bepalen van meerdere keren bemonsteren per jaar op precisie van spatiotemporele toestand en van de trend

## Spatiotemporeel

Mede afstemming nodig met strategie in meetnet biotische habitatkwaliteit (--> ? serially alternating pattern op jaarbasis, met bijstelling steekproef elke 12 jaar, en dus vasthouden aan locaties?) Pilootmonitoring abiotiek oppervlaktewater: volgt nu binnen elk jaar een pure panel-aanpak (repeated sampling).

### Over jaren heen

Merk op dat de doelpopulatie ruimtelijk zal evolueren met de tijd. Daarom zesjaarlijks of vaker (bv. in opvolging van nieuwe versies habitatkaart) het steekproefkader bijwerken en trekking overeenkomstig aanpassen.

De nodige steekproefgrootte kan verdeeld worden over meerdere panels om de behoefte aan toestand- en trendinformatie te balanceren (beide belangrijk, toestand meest belangrijk).

De verdeling van steekproefelementen over panels komt neer op een opdeling van de steekproef in subsamples. Bij de toewijzing per jaar proberen we de volgende doelstellingen te combineren:

- ruimtelijke balans en dekking per jaar (zodat de data van elk jaar op zich ook als ruimtelijk gebalanceerde steekproef dienst doen);
- per jaar de steekproefelementen ruimtelijk méér bundelen dan het geval is voor de steekproef over meerdere jaren.

Dit is mogelijk door voor de toewijzing aan panels een GRTS-rangschikking op een hoger hiërarchisch niveau te gebruiken dan het niveau dat wordt gebruikt voor de steekproefelementen. Bv. voor panels hokken selecteren van ca. 1-enkele km²; het betreft dus een verdeling over de panels van alle hokken die de reeds getrokken steekproefelementen omvatten, en dit op zo'n manier dat het aantal steekproefelementen per jaar gelijkaardig is (panels met repeated measures in rekening genomen). Alle steekproefelementen die tot de voor één panel getrokken hokken behoren, rekenen we dus tot het betreffende panel.

De grootste kostenefficiëntie zou bereikt worden door hetzelfde hokkenpatroon toe te passen voor zoveel mogelijk MNM-meetnetten samen, maar deze synergie vereist tevens dat die meetnetten een sterk overlappende spatiotemporele design volgen. I.e. gelijk aantal panels en gelijke panel design.

Panel-notaties hieronder volgen @mcdonald_review_2003.

#### Geen vaste meetinstallaties

Cf. oppervlaktewater, bodem, evt. atmosfeer, evt. overstromingswater.

Hier verkiezen we een balans tussen repeated measurements voor trendinformatie en steeds 'nieuwe' locaties voor steeds betere toestandsinformatie en beperking van herhaalde verstoring en invloed (i.e. 'nieuw' zolang het steekproefkader nieuwe locs voorziet, daarna herbeginnen).

Een mogelijke opzet hiervoor is een split panel als volgt:

- enerzijds panels die éénmalig of hooguit twee keer bemonsterd worden, dus hetzij synchronous sampling [1-n] hetzij rotational sampling bv. [2-n] of een variant zoals [1-2-1-n].
    - de synergie van deze veranderende sets met het meetnet biotische habitatkwaliteit is dus automatisch kleiner, maar kan tussen de compartimentmeetnetten onderling wel worden gemaximaliseerd.
- anderzijds 1 tot 3 panels met repeated measurements, i.e. pure panel [1-0] (jaarlijks) of een serially alternating pattern [1-1] (tweejaarlijks) of [1-2] (driejaarlijks). Deze 'vaste' set blijft wel onderhevig aan revisie ivm evolutie van het steekproefkader (maar er wordt zoveel mogelijk aan dezelfde locaties vastgehouden).

De opzet gebeurt zodanig dat jaarlijks ongeveer eenzelfde aantal locaties wordt bemonsterd. De steekproefverdeling binnen een jaar is bv. 1/2 voor het pure panel en 1/2 voor nieuwe of laagfrequente locaties.

<!-- Opties daarbij: -->

<!-- - GRTS-rangnummer trekking steeds beginnen bij 1 (cf. quasi-static op zesjaarlijkse basis, serially alternating op jaarlijkse basis) -->
<!-- - rangnummer een stukje doorschuiven, grotere overlap behouden (cf. rotating pattern op zesjaarlijkse basis, serially alternating op jaarlijkse basis) -->

#### Vaste meetinstallaties

Cf. grondwater, atmosfeer, evt. overstromingswater.

Hier wordt gewerkt met een vaste set locaties (blijft wel onderhevig aan revisie ivm evolutie van het steekproefkader, cf. hiervoor). De synergie met meetnet biotische habitatkwaliteit is daarom groter. Om enerzijds detailinformatie te bekomen over trend en anderzijds om de sampling-intensiteit te blijven beheersen, is opnieuw een split panel interessant:

- enerzijds panels die laagfrequent worden bemeten: serially alternating pattern, bv. volgens design [1-3], [1-4], [1-6] of [1-12].
- anderzijds 1 pure panel [1-0] (jaarlijks).

De opzet gebeurt zodanig dat jaarlijks ongeveer eenzelfde aantal locaties wordt bemonsterd. De steekproefverdeling binnen een jaar is bv. 1/2 voor het pure panel en 1/2 voor laagfrequente locaties.


### Binnen een jaar

Optimalisatie mogelijk van de pure-panel aanpak binnen één jaar (cf. chemie waterkolom, zienswijze ICP, ...)? Enkele mogelijkheden:

- spatiale opzet variëren binnen een jaar:
    - rotating panel
    - serially alternating panel
    - synchronous sampling, systematisch in tijd (independent panels)
- tijdstippen binnen een jaar variëren:
    - frequentie van bezoeken is te variëren
    - begin- en eindtijdstip van de periode (~ indien verantwoord volgens vraagstelling)


#  Scenario's

Aspecten om te variëren (definiëren de scenario's):

- design-type (zie hiervoor: alles samen vs. type-submeetnetten)
- design-attributen:
    - steekproefgrootte, zowel spatiaal als temporeel
    <!-- - keuze van PSU's -->
- trend:
    - grootte van de trend
    - tijdsduur
- alternatieve afbakeningen van typegroepen (subpopulaties)

Scenario's evalueren:

- precisie, betrouwbaarheid, power van de resp. doelparameters --  te vergelijken met instelwaarden.
    - voor de scenario's wordt in eerste instantie gewerkt met de precisie van (spatiotemporele) *gemiddelden*, tenzij het voor een doelvariabele (analysevariabele, milieuvariabele) specifiek anders gewenst is.
- de kosteninschatting (middelen en VTE)
- haalbaarheid
- dit volgens de beoogde typegroepen en domeinen (i.h.b. SBZ-H-netwerk). Zie verder onder [inferentie](#inferentie).

Er wordt naar gestreefd om alternatieven te presenteren die een gelijke precisie behalen (dit voor enkele niveaus van precisie; cf. het minimaal en optimaal scenario voor de instelwaarden). Zo kunnen zij worden vergeleken op basis van kosten en haalbaarheid.


# Steekproefsimulatie en steekproefgrootteberekeningen

Bovenop de onderstaande berekeningen is ook een **design-effect** te schatten voor het effect van *model-assisted* werken (regression estimator). Inschatting is dat het opzetten van de benodigde spatiotemporeel expliciete modellen die hiervoor nodig zijn, meer tijd in beslag neemt dan momenteel beschikbaar. Afhankelijk van de technische mogelijkheden op kortere termijn, zal ook voor het effect van *spatiale balancering* een inschatting van design-effect gebeuren. De design-effecten worden conservatief ingeschat op basis van literatuurbronnen ivm milieumonitoring.

Onderstaande subparagrafen: verschillende mogelijke benaderingen voor steekproefgrootteberekeningen volgens verschillende scenario's, gerangschikt volgens toenemende complexiteit van de ontwerpoefening en toenemende effectiviteit van het ontwerp.

De analyses kunnen best gebeuren per typegroep, omdat de precisie op dit niveau het criterium vormt.

Indien de benadering impliceert om inferenties na te bootsen zoals beschreven onder het stuk [inferentie](#inferentie), dan gebeuren voor scenario-vergelijking de volgende vereenvoudigingen:

- gelijke weging van types
- het effect van de regression estimator wordt vervangen door een design-effect (in ruimte en/of tijd)
- het effect van GRTS-sampling wordt mogelijks ook vervangen door een design-effect (in ruimte)

De **design-effecten en de finite-population-correction** worden steeds meegenomen bij het berekenen van varianties.


## Louter kostengebaseerd

Steekproefgrootte enkel baseren op budgettaire en haalbaarheidsoverwegingen.

- Voordeel: quick
- Nadeel: dirty (geen zicht op de behaalde precisie)

## Indien reeds gegevens bestaan van een *aselecte* steekproef (bv. fysicochemische variabelen waterkolom)

Vertrekkend van een reeds bestaande, aselecte steekproef: bootstrap sampling voor simulatie van kleinere of grotere steekproeven, de nodige betrouwbaarheidsintervallen bepalen.

- voordeel: eenvoud, geen model nodig
- nadeel: je hangt vast aan de intrinsieke eigenschappen van de data (bv. moeilijk om een andere trend te kiezen). Tevens gaat een deel van de correlatiestructuur verloren, mede afhankelijk van de bootstrap procedure.


## Vuistregels

Bereken de precisie voor de doelparameters van interesse *voor een beschikbare dataset*, gegeven een gewenst betrouwbaarheidsniveau. Beschouw de verhouding tot de instelwaarden voor deze parameters (x keer smallere/bredere variantie), en hanteer vuistregels om de nodige steekproefgrootte te verkleinen of te vergroten (SE halveren --> 4 keer meer punten).

Het lastige hier is dat de relatieve bijdrage van de spatiale en de temporele steekproefgrootte aan deze precisie bepaald moet worden.



## Deelvarianties bepalen voor een eenvoudige opzet

Voor een eenvoudige opzet zoals de voorgestelde: formules beschikbaar voor steekproefgrootteberekening (voor toestand en trend). Zij gaan uit van de instelwaarden en de variantiecomponenten van de design, voor schatting van een gemiddelde. Deze laatste kunnen met een eenvoudig model worden geschat (gefit aan beschikbare data met eenvoudige assumpties; alle observaties i.i.d.).

Daarbij is de relatieve bijdrage van tijd en ruimte tot de variantie van een (spatiotemporele) schatter te bepalen zodat de steekproefgrootte navenant over tijd en ruimte kan worden verdeeld.

De berekeningen houden ook rekening met de onzekerheid op de variantiecomponenten, volgens het model.

Voordeel: relatief eenvoudig.

Nadeel:

- ivm trend: doordat de formules geen rekening houden met autocorrelatie, en dit later wel gebeurt in analyses, zul je de standard error van de trend onderschatten omwille van autocorrelatie.
- deze methode beperkt zich daarom in de eerste plaats tot de design-based *toestandsbepalingen* van eenvoudige designs.


## Steekproefsimulaties met een goed aan beschikbare data fittend model

Modelvorm: deze beschouwt minstens de kenmerken van de steekproefopzet, bv. jaar, maand, type, typegroep. Het model dient de data redelijkerwijze te fitten, dus ook andere covariaten en dependencies kunnen aangewezen zijn (bodemtype, effectieve neerslag, ...). Om steekproeven te kunnen simuleren, is het nodig dat deze aspecten ruimtelijk aan het steekproefkader gekoppeld zijn.

Het gebruik van dit model geldt onder de assumptie dat het model de volledige doelpopulatie goed beschrijft. Om het typeniveau te kunnen beschrijven, zullen diverse types ook in kleinere groepjes moeten worden gelumpt (weliswaar fijner niveau dan typegroepen) om er genoeg data over te hebben voor modellering.

De design matrix van het model variëren, door waarden te trekken uit het steekproefkader in overeenstemming met de gekozen scenario-attributen. Er kan tegelijk gesampled worden uit de distributie van de modelparameters (fixed & random).
    
Voor verschillende trendgroottes voor een typegroep worden 1000 'grote' steekproeven gegenereerd. Een subsample binnen elke steekproef laat dan spatiaal of temporeel kleinere, gesimuleerde steekproeven toe, alsook opsplitsing tussen types.

Evaluatie van deze gesimuleerde steekproeven gebeurt door de inferentie te doen op niveau van de typegroep en voor het SBZ-H netwerk, zoals voorzien in de monitoring.


# Inferentie

Betreft het doen van uitspraken over de doelpopulatie op basis van een steekproef.

## De doelpopulatie van inferentie

De schattingen voor typegroepen gebeuren:

- in het geval van één eenvoudig totaalmeetnet door subpopulatieschatting via poststratificatie
- in het geval van typespecifieke meetnetten (met lage precisie) met een samengestelde (afgeleide) estimator: (al dan niet gelijk gewogen) gemiddelde van de types

Voor zowel toestand als trend zijn schattingen mogelijk voor verschillende subpopulaties, alnaargelang de design gebeurt alles door subpopulatieschatting via poststratificatie of gebeuren berekeningen post-hoc met een samengestelde estimator:

- voor de gehele doelpopulatie van een meetnet in Vlaanderen
- voor de doelpopulatie binnen het SBZ-H-netwerk (zonder onderscheid tussen typegroepen)
- voor de typegroepen in Vlaanderen 
- voor de typegroepen, binnen het SBZ-H-netwerk
- voor de feitelijke types in Vlaanderen
- voor de feitelijke types, binnen het SBZ-H-netwerk

Bij subpopulatieschatting via poststratificatie conditioneren we de grootte van de sample weights zodanig dat het geschatte aantal units van de subpopulatie gelijk is aan het werkelijke aantal units van de subpopulatie in het steekproefkader. Zie @overton_desirable_1996.


## Regression estimators

De design-based schatters betreffen zoveel mogelijk regression (of ratio) estimators, zodat de juistheid en precisie gevoelig verhogen. Bemerk dat dit in de ontwerpoefening voorlopig alleen als een design-effect wordt meegenomen. Bij revisies van de meetnetten kan dit meer concreet meespelen in steekproefgroottebepaling.

De **modelvorm** van het verband tussen de auxiliary component (kan een constructie zijn met meerdere covariaten in ruimte en tijd) en de responsvariabele zodanig kiezen dat de best mogelijke correlatie (spatiaal en / of temporeel) wordt bekomen met de responsvariabele. Behalve de aangewezen covariaten (die voor de gehele doelpopulatie gekend moeten zijn!) dus ook spatiale en temporele dependency inbouwen. Het model kan voor meerdere of alle types samen worden opgebouwd, desgevallend gebruik makend van een covariaat type of typegroep. Zolang de predicties maar redelijk zijn.

Een regression estimator bevat minstens twee *pi-estimators* (design-based: de respons + één per covariaat van de auxiliary) en minstens één *gekende parameter* van de (sub)doelpopulatie (één per covariaat van de auxiliary).

## Werkwijze van inferentie

Praktisch: zoveel mogelijk terugvallen op R-packages zoals het `survey` package, `spsurvey` e.d. NB. voor de SE-schattingen van kwantielen worden daarbij (intern) typisch resampling procedures zoals bootstrapping toegepast.

Toestand + trend spatiaal: steeds naar typegroepen toe werken, hetzij met een samengestelde estimator op basis van type-meetnetten, hetzij via subpopulation estimation (via poststratificatie) op basis van één totaalmeetnet.

Toestand:

Afhankelijk van de concrete steekproefstrategie in een meetnet, de overeenkomstige formules toepassen. Typisch eerst spatiaal aggregeren en daarna temporeel, vermits het spatial sampling pattern verandert in de tijd.

Indien er repeated measurements voorkomen binnen de periode waarover een spatiotemporele aggregatie gebeurt (units die meerdere keren zijn bemeten), zoals in rotational en split panel designs, kan de spatiotemporele inferentie beter in één beweging gedaan worden waarbij repeated measurements worden downweighted in de analyse (zie @lumley_complex_2011 par. 3.4).

<!-- Mogelijks als een multi-stage sample te analyseren (PSU's: jaren). -->

Trend:

- Iets wat altijd werkt: spatiaal aggregeren en daarna toepassen in een model om de temporele trend te analyseren. Want de designs zijn niet static! Het model moet rekening houden met de autocorrelatie. Advies in @de_gruijter_sampling_2006: weighted least squares regression of spatial means, with weights inversely proportional to variances of spatial means.
- Alternatief is eerst volledig model-based werken (spatiaal en temporeel), op basis hiervan de sample-unit-specifieke trend voorspellen (voor alle sample units), en vervolgens spatiaal een design-based inferentie doen (volgens subpopulaties enz.). Dit is wellicht krachtiger (lokaal variërende trend is toegelaten), en het doet geen geweld aan de design-based ruimtelijke inferentie.
- Nog een alternatief is om de locatiespecifieke trend op basis van niet-complete tijdsreeksen te corrigeren op basis van het regressieverband tussen 'complete trend' en 'niet-complete trend' voor een panel met complete tijdsreeksen, als dat er is (bv. een pure panel in een split panel design). Zie @stevens_spatially_1999 p. 426.

## Finite population correction

Voor alle design-based onderdelen van de inferenties, i.e. de volledige toestandsbepaling (spatiotemporeel) en de spatiale component van de trendbepaling, wordt er rekening gehouden met de "finite population correction". De variantieschatter van elke (regression) estimator (dit kan dus per type zijn) wordt daartoe vermenigvuldigd met $(1- n/N)$ waarbij:

- $N$ staat voor het totale aantal units van de betreffende (sub)populatie in het steekproefkader
- $n$ staat voor het aantal sample units


# Tijdelijke afwijking

*XXX verder nakijken en reflectie nodig*

## Overgangsfase voor 'verdroging via grondwater'

- Opzet: tijdelijk blijven werken met welgekozen, bestaande reeksen om 'trendbepalingen onder voorbehoud' te kunnen doen.
- Intussentijd wordt het nieuw uitgewerkt meetnet geïnstalleerd om reeds op kortere termijn (na 6 jaar) representatieve toestandsbepalingen te kunnen doen. Voor trend is dit slechts meer betrouwbaar mogelijk na 12 of meer jaren.
- Het 'werken met bestaande meetreeksen' wordt beperkt tot kwaliteitsvolle reeksen en zoveel mogelijk gebalanceerd over X, Y en type, waarbij tekorten worden bijgepast:
    - vooreerst is aan elke meetreeks een kwaliteitslabel te hangen ivm kwaliteit van de data (zoals lengte van de meetreeks, volledigheid, wordt nog opgevolgd, enz.)
    - enkel kijken naar peilbuizen ter hoogte van een type uit de doelpopulatie
    - binnen die selectie wordt verder geselecteerd op zodanige manier dat:
        - de balans over X, Y en type optimaler is:
            - daarbij werken met het XY-GRTS-grid (2D, rangschikking buiten beschouwing) en gekruist met de factor type (1D). Er wordt alleen gewerkt met de cellen binnen de subpopulaties (typegroepen)
            - in stapsgewijs grotere celgroottes tewerk gaan (enkel voor wat de XY-component betreft; type blijft op vaste resolutie) en per 3D cel telkens slechts één peilbuis overhouden (obv GRTS-rangschikking).
            - vertrekken vanaf het kleinste 3D celniveau
        - het behouden aantal peilbuizen niet te klein is (toetsing met gewenste steekproefgrootte voor de typegroep in kwestie; i.e. gebaseerd op aantal types in typegroep)
    - de selectie (per subpopulatie) wordt verder aangevuld opdat de balans verder verbetert. Binnen de laagst gehanteerde resolutie (grootste 3D-cellen) met elk één peilbuis gebeurt voor deze grovere 3D-cellen, die overlap hebben met de subpopulatie maar *geen* bestaande peilbuis hebben, een aanduiding van één nieuwe peilbuis op basis van de kleinste 3D-cellen van het feitelijke 3D-GRTS-grid, namelijk deze met het laagste GRTS-rangnummer. Dit levert on the whole een redelijke balancering op voor X, Y en type.
    
**Of:**

Gebalanceerde set met deels bestaande peilbuizen (per type): sowieso pas na vergelijking van scenario's, om de ruimtelijke design te kunnen beslissen. Verdeling van punten is mogelijk volgens methode in Stevens & Olsen 2004 (grid-based), waarbij:

- een raster wordt gekozen dat goed de ruimtelijke heterogeniteit van de  weerspiegelt in de doelpopulatie, en dat bruikbaar is in relatie tot de nodige steekproefgrootte en de reeds beschikbare peilbuizen
- voor beschikbare peilbuizen alleen de 'kwaliteitsvolle' bekeken worden
- per cel het aantal volgens celpopulatiegrootte 'verwachte' peilbuizen wordt nagestreefd: indien er méér beschikbaar zijn, een random subselectie maken (GRTS-based); indien er te weinig zijn: aanvullen met random punten van de steekproeftrekking

*XXX: todo: overwegen van alternatieve methoden.*



# Literatuurreferenties {-}

