# Inleiding

## Situering

Dit verkennend document is bedoeld om keuzes te toetsen, nader te verfijnen en zonodig bij te stellen, aangaande spatiale elementen in hoofdstukken 3 en 5 van @vanderhaeghe_meetnetten_2018, dit om op doorgronde wijze het steekproefkader te kunnen opmaken en een steekproefopzet te implementeren.

We hernemen enkele basisprincipes uit hoofdstuk 2 van vermeld rapport.

- Elk meetnet volgt een *aselecte* steekproefstrategie.
- Afdoende ruimtelijke en temporele *dekking*
- Elk meetnet volgt een *eenvoudige* steekproefopzet in ruimte en tijd. Wegens begrijpbaarheid, verwerkbaarheid, duurzaamheid.
- Elk meetnet hanteert een *flexibele* steekproefopzet.
    - Criterium hiervoor: inferentiewijzen kunnen op eenvoudige wijze valide blijven doorheen de tijd, niettegenstaande evolutie van de context.
    - Kenmerken hierbij: aanpasbaarheid van vragen; bestand tegen aanpassing van domeinen en van steekproefkader; flexibiliteit inzake aanpasbaarheid van steekproefgrootte en het kunnen omgaan met non-response.
    - Daarom voorkeur voor equal probability designs.
    - Uitspraken voor (sub)domeinen gebeuren zoveel mogelijk post-hoc en zijn niet inherent aan de design (subpopulation estimations via poststratificatie).
        


## Aanleiding

Om tot een onderbouwd, transparant en vlot bij te werken steekproefkader te komen, en tot hierop afgestemde veldprotocols, is het belangrijk om goede keuzes te maken over de sample support (ruimtelijke definitie steekproefeenheid), design structuur en de werkwijze om om te gaan met fouten in het steekproefkader.

De basis hiervoor zijn de kenmerken van de spatiale doelpopulaties van de meetnetten in MNM, wat in dit document wordt verkend.
Bij de overwegingen omtrent steekproefopzet, veldprotocols en steekproefkader wordt ook rekening gehouden met de synergieën met het meetnet biotische habitatkwaliteit, zodat hiermee kan worden samengespoord.
Ook in het meetnet biotische habitatkwaliteit [@westra_monitoring_2014] kunnen waar mogelijk of zinvol aanpassingen worden doorgevoerd om de synergie en de effectiviteit te verhogen.

De meetnetten natuurlijk milieu (MNM) en het biotisch meetnet vertonen verschillende parallellen:

- gebruik van eenzelfde master **GRTS**-raster '`GRTSmaster_habitats`', met eenheden van 32 x 32 m² [@onkelinx_grts_2019].
We noemen zo'n rastercel verder een 'level0-cel', verwijzend naar de hiërarchische GRTS-niveaus in de `GRTSmh_brick` en `GRTSmh_diffres` databronnen [@vanderhaeghe_grtsmh_brick_2019; @vanderhaeghe_grtsmh_diffres_2019].
- de MNM hebben een **verklarende** waarde voor de resultaten van het biotisch meetnet [@westra_monitoring_2014], dit volgens _flexibel_ samen te stellen typegroepen per meetnet (i.e. typegroepen op maat, voor een milieudruk in een milieucompartiment, waarbij samenstelling van de typegroep makkelijk herzien kan worden) [@vanderhaeghe_meetnetten_2018].
- per hoofdhabitattype een integratie, op niveau Vlaanderen, van de biotische en abiotische elementen in de **gewestelijke staat van instandhouding (G-SVI)** [@vanderhaeghe_vraagstelling_2017]
- uitspraken zijn gewenst zowel op niveau **Vlaanderen** als op niveau van het **SBZ-H netwerk**
- **uitdagingen** i.v.m. steekproef en terreinwerk:
    - het handhaven van een _**aselecte**_ steekproef, in een context van allerhande bestaande meetpunten van een _judgment_ sample.
    N.B.: biotisch wordt geopteerd om van een aantal types bestaande punten (PQ's e.d.) te betrekken.
    - onzekerheid over de effectieve aanwezigheid op een bepaalde locatie van een bepaald type, volgens een van de databronnen `habitatmap_terr`, `watersurfaces_hab`, `habitatstreams`, `habitatsprings` (samen bestrijken deze alle types uit de doelpopulaties van de meetnetten).
    _**Uitdaging**: is het mogelijk om de trefkans te verhogen zodat een getrokken locatie van een type op terrein vaker overeenstemt met het type in kwestie?_
    Deze uitdaging stelt zich vooral terrestrisch, waar types veelal niet dekkend voorkomen in een polygoon en waarbij de locaties in de polygoon niet gekend zijn.
    Een hogere trefkans vermindert het aantal keren dat men op terrein naar een alternatieve locatie moet uitwijken.
    - het praktisch omgaan met de afwezigheid van een type op een bepaalde locatie waar het type voorkomt volgens het steekproefkader.
    Strikt genomen valt een locatie dan af en wordt een locatie uit het steekproefkader toegevoegd op basis van de GRTS-rangschikking.
    _**Uitdaging**: wat zijn mogelijke opties om hier op een meer praktische manier van af te wijken?_
    - veel terrestrische polygonen zijn maar ten dele bedekt door het type in kwestie (cf. phab-waarden).
    _**Uitdaging**: het veelvuldig voorkomen van kleinere habitatvlekken -- waar hogere milieudrukken kunnen worden verwacht (cf. versnippering) -- proberen mee te krijgen in het steekproefkader._

## Doelstelling

We wensen onderbouwde antwoorden te geven over verschillende vragen in de MNM (en die ten dele ook spelen voor het biotisch meetnet):

1. hoe onderscheiden de types zich op vlak van oppervlakte en aantal spatiale eenheden in de basislagen?
1. waar is een substructuur (domeinen of strata) in de design nodig resp. onnodig?
1. wat zijn de trefkansen om ter hoogte van een rastercel het beoogde terrestrische type effectief aan te treffen?
Zijn er zinvolle manieren om deze via de opmaak van het steekproefkader, de steekproefprocedure of via de ruimtelijke definitie van de steekproefeenheid te beïnvloeden?
1. wat is de ruimtelijke definitie van een steekproefeenheid, i.e. de sample support?
1. is er een zinvolle en haalbare vervangprocedure mogelijk, die compatibel is met de ruimtelijke definitie van de steekproefeenheden en met de ruimtelijk gebalanceerde, aselecte GRTS-aanpak?

Op basis van de verkenning in dit document trekken we besluiten voor de steekproefopzet, de veldprotocols en de opmaak van het steekproefkader.

## Aanpak en leeswijzer

We onderzoeken databronnen (basislagen) die zullen dienen voor het steekproefkader: `habitatmap_terr`, `watersurfaces_hab`, `habitatstreams`, `habitatsprings`.
_XXXXXXX habitatsprings nog te bekijken_
Voor meer informatie over deze databronnen, zie de documentatie van het R-package [n2khab](https://github.com/inbo/n2khab) (vignette over data sources) en de daar gerefereerde Zenodo-collecties.

Hoewel elk meetnet in MNM een eigen spatiale doelpopulatie heeft (gedefinieerd door de geselecteerde types en eventuele bijkomende restricties), beschouwen we in dit document de unie van deze doelpopulaties.
De enige opsplitsing die wordt gemaakt, is deze volgens de bovenvermelde databronnen.
Meer specifiek wordt de meeste aandacht besteed aan de terrestrische types, niet alleen omdat deze het grootste deel uitmaken, maar ook omdat de datalaag `habitatmap_terr` veel onzekerheden bevat die de opmaak van een betrouwbaar steekproefkader en een eenvoudige implementatie op terrein sterk bemoeilijken.

Na de datavoorbereiding (hoofdstuk \@ref(datavoorbereiding)) worden volgende topics overlopen of verkend:

- Het voorkomen van types (hoofdstuk \@ref(voorkomen))
    - Algemeen
    - Vertegenwoordiging van het domein 'SBZ-H-netwerk'
    - Terrestrische types: trefkans in een polygoon en oppervlakte van types in een polygoon
- Meer specifiek voor terrestrische types:
    - Evaluatie van doelpopulatiebeperkende criteria: de laag `shallowgroundwater` (hoofdstuk \@ref(shallow))
    - De implicaties van de koppelingswijze met het GRTS-raster voor (hoofdstuk \@ref(koppeling)):
        - de trefkans voor een type
        - de oppervlaktevertegenwoordiging van het type, op basis van de gekoppelde cellen
        - de populatiegrootte
    - Relaties tussen verschillende hiërarchische GRTS-resoluties en doorwerking naar een praktische aanpak (hoofdstuk \@ref(levels))
    - Overwegingen over het betrekken van de celselectiekans in de steekproefprocedure, met beslissingen over de verschillende aanpak van terrestrische types (hoofdstuk \@ref(celselectiekans))

**Op basis hiervan worden, voor alle types**:

- in hoofdstuk \@ref(design) de consequenties opgelijst voor de **steekproefopzet**
- in paragraaf \@ref(concl) **besluiten** geformuleerd voor de vragen van paragraaf \@ref(doelstelling)
- in paragraaf \@ref(veldprot) de consequenties overlopen voor het opstellen van **veldprotocollen**
- in paragraaf \@ref(steekproefkader) de consequenties behandeld voor de opmaak van het **steekproefkader**


