# Conclusies en consequenties voor veldprotocols en steekproefkader

## Antwoord op de vragen {#concl}

Samengevat zijn dit de antwoorden op de vragen van paragraaf \@ref(doelstelling):

> hoe onderscheiden de types zich op vlak van oppervlakte en aantal spatiale eenheden in de basislagen?

De types lopen heel **sterk uiteen** qua oppervlakte en populatiegrootte (het aantal beschikbare populatie-eenheden).

Voor de meeste _terrestrische types_ wordt ervoor gezorgd dat elke reëel door het type ingenomen oppervlakte-eenheid evenveel kans heeft om in de steekproef terecht te komen.
De steekproef wordt dus zo geconstrueerd dat het een aselecte trekking voorstelt, met gelijke inclusiekansen, uit een doelpopulatie waarvan alle eenheden eenzelfde deeloppervlakte van de totale oppervlakte vertegenwoordigen.

Voor de types van _stilstaande wateren_ blijkt dat een relatief beperkt aantal grotere watervlakken een groot aandeel van de oppervlakte bestrijken.
Het overwicht van grote plassen maakt het oppervlaktegebaseerde signaal, ondanks de discrepantie met de (oppervlaktegewogen) G-IHD, echter weinig informatief voor het voorkomen van (milieuproblematieken in) waterplastypes, wat voor het natuurbeleid meest relevant is.


> waar is een substructuur (domeinen of strata) in de design nodig resp. onnodig?

- het domein **'SBZ-H-netwerk' opnemen in de design is onnodig** en wordt daarom niet gedaan.
Vele types komen verhoudingsgewijs reeds veel meer geconcentreerd voor binnen de SBZ-H-gebieden, zodat hier vanzelf de nodige aandacht naar gaat.
Een specifieke substructuur hiervoor zou voor het inferentiestadium en de steekproef onnodige complicaties veroorzaken, cf. paragraaf \@ref(substructuur).
- om de mogelijkheid te behouden om voor de **stilstaande-watertypes** voldoende nauwkeurige oppervlaktegewogen uitspraken te doen, worden enkele types wel gestratificeerd volgens drie oppervlakteklassen: ≤ 1 ha, 1 - 50 ha, > 50 ha.

> wat zijn de trefkansen om ter hoogte van een rastercel het beoogde terrestrische type effectief aan te treffen, wanneer het centroïd van de rastercel een polygoon met het type treft in de `habitatmap_terr` databron?
Zijn er zinvolle manieren om deze via de opmaak van het steekproefkader, de steekproefprocedure of via de ruimtelijke definitie van de steekproefeenheid te beïnvloeden?

De gemiddelde trefkans loopt sterk uiteen per type en weinig types komen uit boven een 'success-rate' van 75%.
De meeste types hebben een gemiddelde trefkans tussen 25% en 75%, als we al hun cellen (met centroïd in de type-polygonen) evenwaardig in acht nemen.
Per rastercel komt de trefkans overeen met de reële proportie die het type in de rastercel inneemt.
Het overall patroon is te zien in Figuur \@ref(fig:detprob-point) en vertoont een duidelijk overwicht in het **lage** bereik.

Door niet centroïdgebaseerd maar celgebaseerd rastercellen te koppelen aan polygonen wordt de trefkans natuurlijk veel groter (celgebaseerd: een cel wordt geselecteerd als het type ergens in de cel voorkomt), cf. Figuur \@ref(fig:detprob-cell).
De celgebaseerde koppeling komt neer op een ruimere definitie van de steekproefeenheid.
Behalve de sterke toename van de populatiegrootte en de verminderde koppeling met het biotisch meetnet, heeft deze wijze van koppeling het belangrijke nadeel dat niet langer elke oppervlakte-eenheid van de doelpopulatie op gelijke wijze vertegenwoordigd wordt, maar vooral afhangt van de ruimtelijke kenmerken van de polygonen.
Dit bemoeilijkt sterk de interpretatie.

Daarom is ervoor gekozen om voor de meeste types de **centroïdgebaseerde** steekproefeenheid te handhaven, dit in combinatie met een **phab-gewogen GRTS-steekproefprocedure** zodat polygoonoppervlakte met lagere phab proportioneel minder in de steekproef terecht komt.
Aangevuld met een goede **vervangprocedure** voor niet-treffers op terrein (zie verder; phab-waarden reflecteren grote onzekerheden in het steekproefkader), levert dit een efficiënte en tegelijk verantwoorde steekproef op.

Enkel voor een zevental types (Tabel \@ref(tab:cell-based-types)) wordt wel de **celgebaseerde** koppeling toegepast.
Het zijn de types waarvan de level0-cellen met hoogstens 30% bedekking (binnen de cel) een oppervlakte-aandeel van minstens 55% van het type vertegenwoordigen.
In die gevallen is de centroïd-methode te inefficiënt en is het bij de celgebaseerde koppeling ook beter te verantwoorden om geen onderscheid te maken tussen lager- en hogerbedekkende cellen aangezien hoogbedekkende cellen zo weinig voorkomen.

Voor bepaalde MNM-meetnetten is het daarnaast wenselijk om via restrictie van het steekproefkader overtollige eenheden te verwijderen die niet tot de doelpopulatie behoren.
Bv. voor grondwaterdrukken is het vereist dat op de site gedurende een zekere tijd van het jaar ondiep grondwater aanwezig is.
Hiertoe onderzochten we de voorlopig aangemaakte **laag `shallowgroundwater`**, die de types in de grondwatermeetnetten poogt in te perken tot de locaties waar ondiep grondwater voorkomt -- een vereiste randvoorwaarde voor de doelpopulatie.
Zij blijkt momenteel te restrictief te zijn; _verdere verbetering_ van deze laag is dus gewenst.

> wat is de ruimtelijke definitie van een steekproefeenheid, i.e. de sample support?

Voor **(semi-)terrestrische types excl. 7220** is de ruimtelijke steekproefeenheid een GRTS-cel van 32 m x 32 m (level0-cel):

- Het type komt meestal _niet_ dekkend voor binnen de steekproefeenheid, maar moet (behalve voor de zeven types met celgebaseerde koppeling) op het centroïd (het exacte middelpunt) van die cel aanwezig zijn
- Ook moet het type minstens in die mate (aandeel) aanwezig zijn in de cel, nodig om bemeetbaar/bemonsterbaar te zijn.

Voor de **stilstaande wateren** is de steekproefeenheid de plas, ongeacht zijn grootte, dit om de hoger vermelde redenen.

Voor type **3260** is de steekproefeenheid een segment van 100 m.
De aanwezigheid van het type 3260 _binnen_ het segment is de voorwaarde voor een geldige steekproefeenheid.

Voor type **7220** is de steekproefeenheid de volledige habitatvlek (met variabele oppervlakte).
Deze benadering wordt gevolgd voor zowel de beek- als de semi-terrestrische vormen van 7220.

Nadere bespreking is te vinden in paragraaf \@ref(sample-support), inclusief koppeling met het GRTS-raster.

> is er een zinvolle en haalbare vervangprocedure mogelijk, die compatibel is met de ruimtelijke definitie van de steekproefeenheden en met de ruimtelijk gebalanceerde, aselecte GRTS-aanpak?

**Meerdere methoden** zijn beschikbaar en worden weerhouden, afhankelijk van het type:

- GRTS-toevoeging
- polygon-constrained GRTS-verwisseling zonder translatie
- polygon-constrained GRTS-verwisseling met translatie
- level-constrained GRTS-verwisseling

De methoden zijn nader besproken in paragraaf \@ref(vervang).


## Consequenties voor veldprotocollen {#veldprot}

Drie verschillende protocollen zullen nodig zijn om een meetvariabele op de standplaats van een type (in de steekproefeenheid) te bepalen:

- _overkoepelend voor alle meetnetten_, maar verschillende aanpak volgens enkele groepen van types en met extra voorwaarden bij sommige meetnetten:
een **unit-selection protocol** (selectieprotocol): om te bepalen welke van de potentiële steekproefeenheden effectief als steekproefeenheid worden aanvaard.
- _specifiek voor groepen van meetvariabelen in hetzelfde milieucompartiment (typisch de meetvariabelen met eenzelfde terreinaanpak)_:
    - een **subsampling protocol**: om te bepalen op welke plaats(en) binnen de steekproefeenheid het type wordt bemeten of bemonsterd, of van een (semi-)permanente meetinstallatie wordt voorzien.
    - een **measurement protocol** (meetprotocol) dat stapsgewijs en nauwkeurig beschrijft op welke manier wordt gemeten, of bemonsterd/bewaard/getransporteerd.
Desgevallend hoort daarbij ook de beschrijving van installatie, onderhoud of vervanging van permanente of semi-permanente meetinstallaties.

In bepaalde gevallen kan binnen een milieucompartiment nog een verdere opdeling van een protocol nodig zijn volgens bepaalde groepen van types -- _protocolvarianten_ -- bijvoorbeeld voor bodembemonstering in venen, voor de lokalisatie van een peilbuis in het geval van stilstaande wateren, waterlopen of niet-celvormige terrestrische steekproefeenheden (deel van 7220), of voor de oppervlaktewaterbemonstering van plassen versus waterlopen.

In [deze googlesheet](https://docs.google.com/spreadsheets/d/1gJb2nY-Cs-SCNMpz0sGFslb0j69mzNx5BJu9tQXpHfc/edit#gid=1805900003) staan meetvariabelen geclusterd volgens terreinmethode x milieucompartiment, wat vermoedelijk de logische eenheid zal zijn voor de subsampling- en de meetprotocollen.

Een bijzondere groep van variabelen zijn de **omgevingskenmerken**: het zijn variabelen om de toestand en trend van primaire milieuvariabelen beter te kunnen interpreteren, zoals milieudrukindicerende kenmerken van de standplaats en zijn omgeving, of causaal gerelateerde factoren die ter plaatse bepaald kunnen worden.
Het bepalen van hun waarde op terrein vereist eveneens een bijzonder soort 'meetprotocol'.

Voor alle protocollen is er tevens behoefte om deze centraal raadpleegbaar, geversioneerd en in een open formaat beschikbaar te stellen, zowel voor de MNM-medewerkers als voor de (wetenschappelijke) buitenwereld.
Een geschikt **platform** is hiervoor nodig.

### Unit-selection protocol

Het selectieprotocol bevat:

- _toetsingsregels_: de regels die nodig zijn om te evalueren of de aanvankelijke of vervangende steekproefeenheid deel uitmaakt van de doelpopulatie van het type.
    - Het protocol volgt dus strikt de ruimtelijke definitie van de steekproefeenheid zoals bepaald voor dat type, en beschrijft de nodige stappen (zoals lokale kartering) om dit in de praktijk te kunnen toepassen.
    Zie verder in paragraaf \@ref(sample-support).
    - Voor bepaalde meetnetten is het mogelijk dat niet alleen de type-identificatie belangrijk is, maar ook bepaalde milieurandvoorwaarden, om tot de doelpopulatie te behoren.
    Het hangt af van de desktopbeschikbaarheid van _betrouwbare_ datalagen hiervoor (cf. [deze gsheet](https://docs.google.com/spreadsheets/d/14jiHfF4vZUlmfPKiry8HCDDt-HFFvhDhW9_SFvtdSkk/edit#gid=907349910)) om te bepalen of op terrein hiervan een nadere evaluatie nodig is.
    Bv. voor grondwaterdrukken is het vereist dat op de site gedurende een zekere tijd van het jaar ondiep grondwater aanwezig is.
    Ook hiervoor dient een praktisch implementeerbare procedure te zijn opgenomen.
    Zie in R de kolom `spatial_restriction` in de tibble die wordt teruggegeven door `n2khab::read_schemes()`.
    - Ook moet de minimum nodige oppervlakte van het type binnen de steekproefeenheid beschreven zijn, om het te kunnen bemeten of bemonsteren.
    Zie ook paragraaf \@ref(subsampling-protocol).
- een praktische beschrijving van de _vervangprocedure_ (uitleg in par. \@ref(vervang));
- de wijze van eventuele _markeringen_ op terrein om bij herbezoek de eenheid opnieuw te kunnen lokaliseren;
- de wijze van _registreren_ (deel van de dataketen):
    - van de updates aan het steekproefkader die gepaard gaan met de uitvoering van het protocol
    - van het resultaat van de selectie en van de gevolgde stappen (bij vervanging: het adres van de nieuwe eenheid)
    - van beschrijvende / definiërende elementen  om bij herbezoek de eenheid opnieuw te kunnen lokaliseren (situatieschets, ...)
    - van non-responses en redenen daarvoor (bv. redenen van ontoegankelijkheid)
    
Het verdient aanbeveling dat het selectieprotocol zoveel mogelijk samenspoort tussen MNM en de biotische monitoring, opdat beiden gemeenschappelijke protocollen hanteren (synergie).
    
    
### Subsampling protocol
    
Metingen of bemonsteringen gebeuren steeds om de volledige steekproefeenheid te *vertegenwoordigen*, met betrekking tot het type.
Zij moeten leiden tot **één waarde voor de steekproefeenheid**. 
Het kan dus (bij beperkte ruimtelijke variatie) ook om één enkele meting of monster gaan.

Het beoogde type in de steekproefeenheid kan op _verschillende manieren_ worden bemeten (vertegenwoordigd), afhankelijk van de milieuvariabele:

- zeer lokaal geldende metingen (bv. bodemkwaliteit):
    - ofwel het type dekkend bemonsteren (binnen de eenheid) met een bepaalde intensiteit & ruimtelijke opzet (geeft een accurater resultaat voor de gehele steekproefeenheid)
    - ofwel -- enkel indien nodig (complexer): ivm verstoring, kostprijs, haalbaarheid: het type bemonsteren in een kleiner deel/delen van de steekproefeenheid, of met een lagere densiteit.
Sublocatie(s) zijn daarbij te roteren in de tijd, i.h.b. bij verstoringseffecten of indien ruimtelijke variatie te verwachten binnen de cel.
- ruimtelijk breder geldende metingen (bv. grondwater, atmosfeer):
    - 1 punt in de steekproefeenheid (in het type) volstaat voor de meting
    - indien de meting ruimtelijk breder toepasbaar is dan de steekproefeenheid, kan de meting desgevallend voor meerdere aangrenzende steekproefeenheden (of types) gelden.

Behalve de werkwijze om sublocaties te selecteren, beschrijft het protocol ook de werkwijze om de gevolgde subsamplingwerkwijze te **registreren** (deel van de dataketen).

Bemerk dat de minimaal nodige oppervlakte of lengte van een type, nodig om de bemonstering uit te kunnen voeren, zal moeten doorwerken in de _toetsingsregels_ van het selectieprotocol.

- Hiervoor is vermoedelijk het bodembemonsteringsprotocol meest limiterend.
- Mogelijks moet voor bepaalde types worden afgeweken van een default waarde.

### Measurement protocol

Voor het meetprotocol kan afstemming (tot en met gelijkschakeling) met bestaande protocollen gunstig zijn ivm synergie en operationele samenwerking.
Een randvoorwaarde bij het overnemen van protocollen is dat de werkwijze haalbaar, kostenefficiënt en effectief dient te zijn voor de in MNM beoogde doelstelling om de milieudrukkenproblematiek ter hoogte van types in Vlaanderen in beeld te brengen [in @vanderhaeghe_vraagstelling_2017, hoofdstuk 11, is hierover een kwalitatieve analyse te vinden per milieucompartiment].

_Meetvariabelen en omgevingskenmerken_ zijn per meetnet opgelijst in [deze googlesheet](https://docs.google.com/spreadsheets/d/1gJb2nY-Cs-SCNMpz0sGFslb0j69mzNx5BJu9tQXpHfc/edit?usp=sharing).

Het is verder te beoordelen op welk niveau _omgevingskenmerken_ best gegroepeerd kunnen worden om in protocollen op te nemen.

Behalve de **precieze werkwijze** van meten, bemonsteren/bewaren/transporteren, of installeren/onderhouden, beschrijft het protocol ook de werkwijze om **non-responses** en hun redenen (zoals niet-meetbaarheid, verlies van monster, vandalisme meetopstelling) te registreren (deel van de dataketen).




## Consequenties voor de opmaak van het steekproefkader {#steekproefkader}

Het steekproefkader van een type in een meetnet is de lijst van alle populatie-eenheden die volgens _de beschikbare informatie_ tot de doelpopulatie van het type in dat meetnet behoren óf _kunnen_ behoren.

De combinaties van types en meetnetten worden in R als een tibble gegeven door `n2khab::read_scheme_types()`.
Voor de meeste meetnetten is het steekproefkader van een type steeds hetzelfde (louter gedefinieerd door één van de biotische basislagen), maar in verschillende meetnetten moeten ook milieukundige randvoorwaarden worden gesuperponeerd.
Zie hiervoor in R de kolom `spatial_restriction` in de tibble die wordt teruggegeven door `n2khab::read_schemes()`.

Verschillende data-elementen zijn van belang:

1. Elke eenheid wordt in het steekproefkader minimaal met een bepaalde code geïdentificeerd en gekoppeld aan een **GRTS-rangnummer** van de `GRTSmaster_habitats` databron.
Het gebruik van het GRTS-rangnummer, in combinatie met het type in het meetnet, zal daarom in de meeste of in alle gevallen volstaan als identificatiecode.
1. Voor de opmaak van het steekproefkader van een type zijn bijgevolg verschillende **databronnen** benodigd, zoals:
    - `habitatmap_terr`
    - `watersurfaces_hab`
    - `habitatstreams`
    - `habitatsprings`
    - `shallowgroundwater`
1. Ook de bijgehouden **waarnemingen van de aanwezigheid of afwezigheid van een type ter hoogte van populatie-eenheden** (al dan niet opgenomen in de steekproef), inclusief het tijdstip van elke waarneming, zijn een belangrijke databron om het steekproefkader up to date te brengen volgens de resolutie van de steekproefeenheden.
Deze informatie is alvast voor de terrestrische types niet met die resolutie aanwezig in de basisdatabronnen -- en zal daar ook niet noodzakelijk tot aanpassing leiden -- maar is wel cruciaal voor de monitoring.
1. Voor de aquatische types is het belangrijk om over de coördinaten te beschikken van de **punten** waarnaar de respectievelijke steekproefeenheden zijn geabstraheerd.
1. Het moet duidelijk zijn voor welke **terrestrische** types het steekproefkader centroïdgekoppeld wordt opgebouwd en voor welke dit celgekoppeld gebeurt (zie Tabel \@ref(tab:cell-based-types) voor deze laatste).
Deze opdeling is ook van belang voor de steekproefprocedure en voor de veldprotocols (zie eerder).
1. Verdere data die één-op-één met het steekproefkader gekoppeld moeten zijn, omdat ze naast het GRTS-rangnummer eveneens nodig zijn in de steekproefprocedure:
    - voor stilstaande wateren: het **oppervlaktestratum**.
    - voor centroïdgebaseerde terrestrische types:
        - de **phab** waarde (nodig voor de steekproefprocedure)
        - een **random nummer** per cel.
        Dit kan gemeenschappelijk voor alle meetnetten.
        Gezien de temporele evolutie van het steekproefkader is het nodig om dit als een _master_ raster aan te maken, overeenkomend met de volledige extent van het GRTS-raster en dit binnen de buitengrenzen van Vlaanderen (i.e. inclusief Brussels Gewest).
        
Het steekproefkader gebruikt voor de opslag een efficiënt en transparant **datamodel** dat geversioneerd kan worden en online samenwerking mogelijk maakt.
Het al dan niet combineren of gescheiden houden van bepaalde groepen van types is een aandachtspunt.
Combinatie van alle types is te verkiezen als dit op een eenvoudige manier mogelijk is.
Er wordt ook rekening mee gehouden dat medewerkers updates moeten kunnen aanbrengen aan het steekproefkader, in functie van karteringen op terrein.



