---
title: "Water Level Variograms: Daily Data"
bibliography: references_csl.json
format:
  html:
    toc: true
    html-math-method: katex
    code-fold: true
    embed-resources: true
knitr:
  opts_chunk:
    echo: true
---


... the usual.

```{r setup}
#| include: false
void <- suppressPackageStartupMessages
library("dplyr")     |> void() # our favorite data wrangling toolbox
library("dbplyr")    |> void() # dplyr + databases
library("arrow")     |> void() # writing parquet files
library("ggplot2")   |> void() # a visualization toolbox
library("gridExtra") |> void() # panels with ggplot
library("ggcorrplot")|> void() # correlation, grid visualization
library("mapview")   |> void() # map visualization
library("ggridges")  |> void() # density ridges


if (getOption("browser") == "") options(browser = "librewolf") 

# user-set parameters
cluster_dist <- 3400 # m # parameter for clustering
data_export_file <- paste0("data/waterlevel_data_cl", cluster_dist, ".parquet")
chem_export_file <- paste0("data/waterchemistry_data_cl", cluster_dist, ".parquet")
diffdata_export_file <- paste0("data/waterchemistry_diffdata_cl", cluster_dist, ".parquet")

# parameters
#  extent <- 256 # m
# n_bins <- 50
bin_target <- 64


soilclass_colors <- c(
  "heavy" = "sienna",
  "light" = "burlywood",
  "peat" = "darkseagreen",
  "unknown" = "slategray"
)
```


The script `120_waterchemistry_reload.qmd` should be used to assemble the data set loaded here.



```{r load-data}

pp_data <- read_parquet(data_export_file)

std_chem <- read_parquet(file = chem_export_file) %>%
  mutate(date = as.Date(as.character(date), format = "%Y%m%d"))
pp_chem <- std_chem %>%
  select(-date) %>% 
  summarize(
    across(everything(), ~mean(., na.rm = TRUE)),
    .by = pp_idx
  )
```



```{r load-diffdata}

diff_data <- read_parquet(diffdata_export_file)

pp_join <- pp_data %>%
  select(pp_idx, fdepth, pp_code, mp_idx, cluster,
         x, y, soilclass, elevation_dhmv, slope_r2.5m,
         wata_min_dist, wata_dist_class,
         emd_n, emd_amp1, emd_amp2, emd_ampsum,
         emd_qdiff, emd_residual_qdiff
         )

diff_meta <- diff_data %>%
  select(pp_idx1, pp_idx2) %>%
  distinct() %>%
  left_join(
    pp_join,
    by = join_by(pp_idx1 == pp_idx),
    relationship = "many-to-one",
    suffix = c("", "1")
  ) %>%
  left_join(
    pp_join,
    by = join_by(pp_idx2 == pp_idx),
    relationship = "many-to-one",
    suffix = c("1", "2")
  ) %>%
  mutate(
      ds = sqrt((x2-x1)^2 + (y2-y1)^2),
      dh = elevation_dhmv2-elevation_dhmv1,
      dz = fdepth2-fdepth1,
      damp = emd_ampsum2-emd_ampsum1,
      dqdiff = emd_qdiff2-emd_qdiff1,
      dwadi = wata_min_dist2-wata_min_dist1,
      dslope = slope_r2.5m2-slope_r2.5m1,
      melevation = mean(c(elevation_dhmv2, elevation_dhmv1)),
      mslope = mean(c(slope_r2.5m2, slope_r2.5m1)) 
  )

```


```{r glimpse-data}

# diff_meta %>% glimpse
# diff_data %>% glimpse

diff_all <- diff_meta %>%
  select(pp_idx1, pp_idx2, cluster1,
      x1, y1, x2, y2, 
      soilclass1, wata_dist_class1, wata_dist_class2,
      ds, dh, dz, damp,
      dqdiff, dwadi, dslope,
      melevation, mslope
  ) %>%
  mutate(
    pair = factor(paste0(
      as.character(pp_idx1), "_", as.character(pp_idx2), sep = "")
    )
  ) %>%
  left_join(diff_data,
    by = join_by(pp_idx1 == pp_idx1, pp_idx2 == pp_idx2),
    relationship = "one-to-many"
  ) %>%
  filter(
    # ds >= extent/n_bins
    date2 - date1 == 0
  ) %>%
  mutate(date = date1) %>% select(-date1, -date2)
  # mutate(dt = abs(difftime(date1, date2, units = "days")))
    

diff_all %>% ggplot(aes(x = ds)) +
  geom_histogram(bins = 256, fill = "lightgray", color = "black") +
  theme_bw()

```


# binning


After some good prior experience, I will once more apply binning with variable bin width, to achieve **equal sample size per bin**.


```{r equibin-preparation}
#| code-fold: false

diff_equigrouped <- diff_all %>%
  summarize(
    n_obs = sum(as.integer(!is.na(dPC1))),
    soilclass = first(soilclass1),
    cluster = first(cluster1),
    ds = mean(ds, na.rm = TRUE),
    # dt = mean(abs(date2-date1), na.rm = TRUE),
    # semivar = 1/(2*n_obs)*sum(dPC1^2, na.rm = TRUE),
    dnnh4 = 1/(n_obs)*sum(abs(dnnh4), na.rm = TRUE),
    dnno3 = 1/(n_obs)*sum(abs(dnno3), na.rm = TRUE),
    dppo4 = 1/(n_obs)*sum(abs(dppo4), na.rm = TRUE),
    dnnh4r = 1/(n_obs)*sum(abs(dnnh4r), na.rm = TRUE),
    dnno3r = 1/(n_obs)*sum(abs(dnno3r), na.rm = TRUE),
    dppo4r = 1/(n_obs)*sum(abs(dppo4r), na.rm = TRUE),
    dPC1 = 1/(n_obs)*sum(abs(dPC1), na.rm = TRUE),
    dPC2 = 1/(n_obs)*sum(abs(dPC2), na.rm = TRUE),
    dPC3 = 1/(n_obs)*sum(abs(dPC3), na.rm = TRUE),
    .by = pair 
  ) %>% ungroup %>% arrange(ds) %>%
  group_by(soilclass) %>% 
  mutate(
    distance_equibin = cut_number(
      ds, as.integer(floor(n()/min(c(n()/8, bin_target))))
    ) # cut to equal sized bins
  ) %>%
  relocate(distance_equibin) %>% 
  ungroup

    
combine_grouped <- function (val, cnt) sum(val*cnt, na.rm = TRUE)/sum(cnt, na.rm = TRUE)

diff_binned <- diff_equigrouped %>%
  summarize(
    cnt = n(),
    ds = mean(ds), 
    # dt = mean(dt), 
    n_obs = sum(n_obs),
    # semivariance_groupmean = mean(semivar, na.rm = TRUE),
    # semivariance_all = combine_grouped(semivar, cnt),
    dPC1_all = combine_grouped(dPC1, n_obs),
    dnnh4 = mean(dnnh4, na.rm = TRUE), 
    dnno3 = mean(dnno3, na.rm = TRUE), 
    dppo4 = mean(dppo4, na.rm = TRUE), 
    dnnh4r = mean(dnnh4r, na.rm = TRUE), 
    dnno3r = mean(dnno3r, na.rm = TRUE), 
    dppo4r = mean(dppo4r, na.rm = TRUE), 
    dPC1 = mean(dPC1, na.rm = TRUE), 
    dPC2 = mean(dPC2, na.rm = TRUE), 
    dPC3 = mean(dPC3, na.rm = TRUE), 
    .by = c(distance_equibin, soilclass)
  ) %>%
  ungroup %>% arrange(ds)

```



```{r equibin-samplesize}
#| label: fig-equibin-sample-size
diff_binned %>%
  ggplot(aes(x = ds, y = cnt, color = soilclass)) +
  geom_step() +
  geom_hline(yintercept = 0, color = "darkgrey") +
  theme_bw()
```


```{r}
plot_ridge <- function(sc, chemvar) {

  diff_equigrouped %>%
    filter(soilclass == sc, ds < 100) %>% 
    ggplot(aes(x = !!rlang::sym(chemvar), y = distance_equibin)) +
    geom_density_ridges(rel_min_height = 0.05,
      quantile_lines = TRUE, quantiles = 4,
      scale = pi, bandwidth = 0.02,
      fill = soilclass_colors[[sc]],
      alpha = 0.8
    ) +
    # scale_fill_viridis_c(option = "plasma", name = "") +  xlim(0, 4) +
    labs(
      x = glue::glue("mean log(concentration) difference {chemvar}"),
      y = "well pair distance"
    ) +
    xlim(0, 1.0) +
    theme_bw() + coord_flip() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 

}

```

# equibin ridges

## $NH_4$

::: {.panel-tabset group="soilclass"}
### heavy

```{r}
#| fig-cap: "NH4, heavy"
plot_ridge("heavy", "dnnh4")
```

### light

```{r}
#| fig-cap: "NH4, heavy"
plot_ridge("light", "dnnh4")
```

### peat

```{r}
#| fig-cap: "NH4, heavy"
plot_ridge("peat", "dnnh4")
```


:::

## $NO_3$

::: {.panel-tabset group="soilclass"}
### heavy

```{r}
#| fig-cap: "NH4, heavy"
plot_ridge("heavy", "dnno3")
```

### light

```{r}
#| fig-cap: "NH4, heavy"
plot_ridge("light", "dnno3")
```

### peat

```{r}
#| fig-cap: "NH4, heavy"
plot_ridge("peat", "dnno3")
```


:::



## $PO_4$

::: {.panel-tabset group="soilclass"}
### heavy

```{r}
#| fig-cap: "NH4, heavy"
plot_ridge("heavy", "dppo4")
```

### light

```{r}
#| fig-cap: "NH4, heavy"
plot_ridge("light", "dppo4")
```

### peat

```{r}
#| fig-cap: "NH4, heavy"
plot_ridge("peat", "dppo4")
```


:::



## PC1

::: {.panel-tabset group="soilclass"}
### heavy

```{r}
#| fig-cap: "NH4, heavy"
plot_ridge("heavy", "dPC1")
```

### light

```{r}
#| fig-cap: "NH4, heavy"
plot_ridge("light", "dPC1")
```

### peat

```{r}
#| fig-cap: "NH4, heavy"
plot_ridge("peat", "dPC1")
```

:::

## PC2

::: {.panel-tabset group="soilclass"}
### heavy

```{r}
#| fig-cap: "NH4, heavy"
plot_ridge("heavy", "dPC2")
```

### light

```{r}
#| fig-cap: "NH4, heavy"
plot_ridge("light", "dPC2")
```

### peat

```{r}
#| fig-cap: "NH4, heavy"
plot_ridge("peat", "dPC2")
```

:::
