# Inleiding

Een puntenlaag wordt voorbereid voor berekening met het VLOPS-model, in aanvulling op de 1*1 km² modelresultaten en op de puntenberekeningen t.h.v. de meetlocaties.
VLOPS-puntberekeningen zijn de meest interessante basis om de modelresultaten te onderzoeken.
Met behulp van deze puntenlaag is het mogelijk om spatiale interpolatie te doen en op die manier inferenties te doen.

_Dit kadert in een analyse om de geschiktheid van VLOPS te staven voor de bepaling van (spatiotemporele) gemiddelden / kwantielen van tmd + tzd en achterliggende componenten, i.e. per typegroep (set van habitattypes) gedurende een zesjaarperiode voor al de Vlaamse locaties waar de typegroep voorkomt. Zie ook de presentatie gegeven aan VMM Dienst Lucht op 12 maart 2019._

Een aantal pistes voor puntenselectie worden verkend, samengesteld uit keuzes inzake:

- perimeter om punten binnen te selecteren:
    - Vlaanderendekkend
    - geconcentreerd (met buffer) rond de doelpopulatie
- strategie om punten te selecteren:
    - systematisch
    - ruimtelijk gebalanceerd
    
Er wordt voor puntselectie vertrokken van het [GRTS_master_habitats](https://doi.org/10.5281/zenodo.2611233) raster vermits dit ook gebruikt wordt om de locaties te definiëren voor inferentie over spatiotemporele quantities en omdat het toelaat om ruimtelijk gebalanceerde selecties te doen.


