## Referentielijsten milieudrukken en types {#reflijsten}

### Lijst van de milieudrukken

Specifieke uitleg bij de respectievelijke milieudrukken is beschikbaar als een [google spreadsheet](https://docs.google.com/spreadsheets/d/1aVUQWQlaL3k5hjuwyH-8c0lW7hjIkPz8VZbNgyMlN0A/edit?usp=sharing).

```{r message=FALSE, warning=FALSE, results='asis', echo=FALSE}
read_csv("../../data/BijlageMilieudrukken.csv") %>% 
    select(1:2) %>% 
    mutate(Milieudrukklasse = ifelse(is.na(Milieudrukklasse),
                                     "",
                                     Milieudrukklasse)) %>% 
    pandoc.table(
         split.table = Inf ,
         split.cells = c(30,50),
         justify = "left",
         caption = "(\\#tab:milieudrukken)Lijst van de milieudrukken."
)
```

\FloatBarrier

### Lijst van de types

```{r message=FALSE, warning=FALSE, echo=FALSE}
milieudruk_rangschikking <-
    read_vc("../../data/milieudruk_rangschikking")
milieudruk_rangschikking %>% 
    write_csv("../../data/milieudruk_rangschikking.csv")
typeklassen <- read_vc("../../data/typeklassen")
typenamen <- read_vc("../../data/typenamen")
types <- 
    typeklassen %>% 
    select(2, 1) %>% 
    inner_join(typenamen) %>% 
    select(-Volledige.naam) %>% 
    semi_join(milieudruk_rangschikking) %>% 
    rename(Type = Vegcode,
           VerkorteNaam = Verkorte.naam) %>% 
    arrange(Typeklasse, Type)
types %>% 
    write_csv("../../data/types.csv")
```


```{r message=FALSE, warning=FALSE, results='asis', echo=FALSE}
types %>% 
    pandoc.table(
         split.table = Inf ,
         justify = "left",
         caption = "(\\#tab:types)Lijst van de types, beschouwd in de MNM."
)
```

\FloatBarrier


