---
title: "Bepaling van keuzes in de Meetnetten Natuurlijk Milieu"
subtitle: "CONCEPT"
author: "INBO"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
linkcolor: link.colour
citecolor: link.colour
urlcolor: link.colour
geometry: margin=1in
mainfont: "Calibri"
fontsize: 11pt
documentclass: "report"
lang: "nl-BE"
output:
  bookdown::html_book:
    theme: united
    split_by: "rmd"
    keep_md: yes
    toc: yes
    css: toc.css
    includes:
        in_header: header.html
    pandoc_args:
        - --csl
        - ../../../research-institute-for-nature-and-forest.csl
  bookdown::pdf_book:
    base_format: INBOmd::inbo_rapport
    floatbarrier: subsubsection
    citation_package: none
    keep_tex: TRUE
    toc_depth: 2
  bookdown::pdf_document2:
    # md_extensions: +implicit_header_references
    fig_caption: yes
    pandoc_args:
        - --csl
        - ../research-institute-for-nature-and-forest.csl
    keep_tex: yes
    toc: yes
    toc_depth: 3
    latex_engine: xelatex
    number_sections: true
    includes:
        in_header: header.tex
github-repo: "inbo/mnm_keuzes"
bibliography: ../mnm_keuzes.bib
link-citations: yes
description: "Onderbouwing keuzes MNM"
---

<!-- Bij de auteurs een voetnoot toevoegen met de vermelding van de betrokken habitatexperten (bevraging milieudrukken). -->

<!-- Hieronder todo's (manuele workarounds) bij het compileren van PDF (zowel pdf_book als pdf_document2). Het builden loopt vast bij de compilatie van mnm_keuzes.tex. Dit heeft te maken met het voorkomen van dubbele backslashes in de resulterende tex, voor de figuren van de compartimentmeetnetten. Na vastlopen, doe het volgende: -->

<!-- - verplaats de map mnm_keuzes_files die staat onder _bookdown_files, 1 niveau hoger. Dit maakt dat bij de hercompilatie van mnm_keuzes.tex de betreffende figuur-pdf's gevonden worden. -->
<!-- - vervang in mnm_keuzes.tex de string \\ref door \ref -->
<!-- - hercompileer mnm_keuzes.tex -->


```{r setup, echo=FALSE, message=FALSE}
options(stringsAsFactors = FALSE,
        knitr.kable.NA = '')
library(knitr)
library(tidyverse)
library(vegan)
library(pander)
library(git2rdata)
library(n2khab)
# library(xlsx)
opts_chunk$set(
  echo = TRUE,  # nodig ivm kadertjes
  dpi = 300
)
# functies en helpers inlezen:
source("../scripts/functies_helpers.R")
```


# Inleiding

_**Een PDF-versie van deze website kunt u [hier](https://drive.google.com/uc?export=download&id=1V930kfXknddFLZghzG7Tjzk04XDGmpXW) downloaden.**_

De meetnetten natuurlijk milieu (MNM) zijn een instrument van de Vlaamse Overheid om de planning, onderbouwing, evaluatie en bijsturing van het milieugerichte, actieve natuurbeleid op niveau Vlaanderen te ondersteunen. Zij komen tot stand in een samenwerkingsverband tussen meerdere entiteiten, waarbij het INBO een trekkersrol opneemt. Een belangrijke taak van het actieve natuurbeleid bestaat er in om het kader en de maatregelen(programma’s) te voorzien opdat de milieuknelpunten voor natuur zouden worden opgelost. De beleidsondersteuning door de MNM komt tot stand via monitoring van de milieukwaliteit op standplaatsen van habitattypes en regionaal belangrijke biotopen (RBB's). Een analyse van vraag en aanbod leidde in 2017 tot het **basisrapport** van de MNM [@vanderhaeghe_vraagstelling_2017].

Om de meetnetten te kunnen ontwerpen, was een **vraagverfijning** nodig. Er dienden immers keuzes te worden gemaakt:

- over welke *milieudrukken* zijn uitspraken gewenst?
- voor welke *types* (habitattypes en RBB's) zijn deze uitspraken gewenst, afhankelijk van de milieudruk?
- van welke *standplaatsfactoren* worden hiervoor toestand en trend opgevolgd, afhankelijk van milieudruk en type?
- hoe zien we de verdeling van de geselecteerde types en standplaatsfactoren over *meetnetten*?

<!-- ```{block2, type = "exampleblock"} -->
**Op deze website zijn de volgende elementen samenvattend bijeengebracht:**

- recapitulatie van enkele concepten en van de vraagstelling;
- de instrumenten om de bovenvermelde selecties te kunnen doen;
- de gemaakte selecties;
- de opdeling in meetnetten en compartimentmeetnetten.
<!-- ``` -->

Deze keuzes kunnen nog verfijnd worden tijdens verdere ontwerp- en implementatiestappen (voortschrijdend inzicht), eventueel ook doordat onderliggende elementen kunnen evolueren (zoals type-indelingen, milieudrukindelingen, systeemschema, gehanteerde scores per type).
Op dat moment wordt deze website bijgewerkt.







