# Inleiding

## De meetnetten natuurlijk milieu

De meetnetten natuurlijk milieu (MNM) zijn een instrument van de Vlaamse Overheid om de planning, onderbouwing, evaluatie en bijsturing van het milieugerichte, actieve natuurbeleid op niveau Vlaanderen te ondersteunen. De individuele meetnetten zullen daartoe een coherent geheel moeten vormen met een gemeenschappelijke rationale in opzet en verwerking, in functie van de overkoepelende beleidsvragen. De meetnetten komen tot stand in een samenwerkingsverband tussen meerdere entiteiten, waarbij het INBO een trekkersrol opneemt. Een belangrijke taak van het actieve natuurbeleid bestaat er in om het kader en de maatregelen(programma’s) te voorzien opdat de milieuknelpunten voor natuur zouden worden opgelost. De beleidsondersteuning door de MNM komt tot stand via monitoring van de milieukwaliteit op standplaatsen van habitattypes en regionaal belangrijke biotopen (RBB's). De motivatie voor de MNM staat kort samengevat in bijlage \@ref(app:motivatie).

Een analyse van vraag en aanbod leidde in 2017 tot het **basisrapport** van de MNM [@vanderhaeghe_vraagstelling_2017]. Een daarop aansluitende verfijning van de vragen leidde tot selecties van milieudrukken, types (habitattypes en RBB's), standplaatsfactoren en tot het onderscheid in meetnetten en compartimentmeetnetten. Deze informatie is samengevat op een **website**^[Voorlopig is de website alleen lokaal te renderen, vandaar de link naar de PDF-versie.] omdat er op dit niveau verdere evolutie mogelijk blijft.
*XXX updaten wanneer online XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX*
*Een PDF-versie van de website is [hier](https://drive.google.com/uc?export=download&id=1V930kfXknddFLZghzG7Tjzk04XDGmpXW) te downloaden.*

In beide bronnen is ook uitleg te vinden bij inhoudelijke **termen** die in de MNM worden gehanteerd. De meest belangrijke voor dit rapport zijn opgenomen in Bijlage \@ref(app:termen).

Meer recent is er voor elke standplaatsfactor een overeenkomstige milieuvariabele gekozen om de milieudruk te kunnen vertegenwoordigen.



## Ten geleide bij dit rapport

Dit rapport geeft een algemene benadering voor de steekproefstrategie en de inferentiemethode voor alle MNM-meetnetten die op steekproeven (en niet op modellen) worden gebaseerd.

Monitoring van een milieuvariabele is mogelijk in het algemeen op basis van:

- ofwel oppervlaktedekkende -- veelal mechanistische -- modellen (i.f.v. tijd);
- ofwel oppervlaktedekkende metingen (herhaald of continu in tijd, bv. remote sensing);
- ofwel met een steekproef (dit rapport).

Momenteel wordt er voor bepaalde milieudrukken in het atmosferisch en het overstromingsmeetnet verkend of (vlakdekkende) modelleringen van bepaalde standplaatsfactoren haalbaar en effectief zouden zijn voor de MNM.

De methodologische keuzes in dit rapport zijn gebaseerd op:

- de aard van de vraagstelling van de MNM en het gebruik door de eindgebruikers;
- intrinsieke aspecten van milieumonitoring;
- keuzes in het meetnet biotische habitatkwaliteit;
- literatuurstudie over design van meetnetten en analyse van hun resultaten;
- overleg met betrokkenen in het beleidsdomein omgeving.

Over het algemeen is dit rapport technisch van aard en is zekere voorkennis of verdere literatuurstudie nodig voor een begrip ten gronde (zie de literatuurreferenties). Dit varieert echter van paragraaf tot paragraaf en veelal is de inhoud minstens op hoofdlijnen begrijpbaar voor (milieu)wetenschappers in het algemeen.

*Omwille van de status als conceptrapport zijn hier en daar passages in een verkorte vorm verwoord. XXXXXXXXXXXXXXXXXXXX updaten* 


