# Principes voor steekproefstrategie en inferentie

Uitgaande van 1) de context in hoofdstuk \@ref(inleiding), 2) het feit dat het om monitoring gaat en niet om een eenmalige survey, 3) sampling design theorie, 4) kennis en ervaring uit monitoringliteratuur, en 5) overleg, is tot een aantal voor de MNM gemeenschappelijke principes gekomen.

- Elk hoofdmeetnet volgt een *aselecte* steekproefstrategie.
    - *Voor meer info in verband met het belang van een aselecte steekproef, zie bv. @brus_method_2003, @edwards_issues_1998, @manly_sampling_2014, @olsen_statistical_1999.*
- Elk hoofdmeetnet volgt een *eenvoudige* steekproefopzet in ruimte en tijd. Wegens begrijpbaarheid, verwerkbaarheid, duurzaamheid.
- Kostenefficiëntie.
- Haalbaarheid.
- Elk hoofdmeetnet hanteert een *flexibele* steekproefopzet.
    - Criterium hiervoor: inferentiewijzen kunnen op eenvoudige wijze valide blijven doorheen de tijd, niettegenstaande evolutie van de context.
    - Kenmerken hierbij: aanpasbaarheid van vragen; bestand tegen aanpassing van domeinen en van steekproefkader; flexibiliteit inzake aanpasbaarheid van steekproefgrootte en het kunnen omgaan met non-response.
    - Meest eenvoudig (indien in overeenstemming met vraagstelling): equal probability designs:
        <!-- - Equal probability designs: zonodig te beschouwen per vooraf bepaald domein (maar domeinafbakening liever vermijden wegens afname van flexibiliteit). -->
        - Uitspraken voor (sub)domeinen gebeuren zoveel mogelijk post-hoc en zijn niet inherent aan de design (subpopulation estimations via poststratificatie).
- Afdoende ruimtelijke en temporele *dekking*
- Ruimtelijke *koppelingen*:
    - De meetnetten zijn onderling maximaal gekoppeld (over milieucompartimenten heen);
    - De meetnetten zijn maximaal gekoppeld met het meetnet biotische habitatkwaliteit. De koppeling is niet mogelijk voor regionaal belangrijke biotopen (RBB's) vermits deze niet gemonitord worden in het biotische meetnet. Er wordt dus zoveel mogelijk gekoppeld met de habitatlocaties, binnen de grenzen van de overige principes.
- De steekproefopzet laat een schatting toe van de *variantie* van de doelparameter, die rekening houdt met het type van steekproefopzet.
- Het ontwerp van de MNM (type van spatiale en temporele design, steekproefgrootte, revisit design enz.) wordt geconcipieerd om nauwkeurige antwoorden te kunnen geven op *de eerste en meest belangrijke kernvraag van de MNM*. Het betreft het kwantitatief bepalen van de toestand en de trend van bepaalde milieuvariabelen om actuele milieuknelpunten te kunnen vaststellen en kwantificeren. Dit gebeurt op schaal Vlaanderen, voor groepen van types (habitattypes en regionaal belangrijke biotopen). Het antwoord op de tweede en derde kernvraag betreft een verdere verwerking van de uitkomsten voor de eerste kernvraag.
- *Objectiviteit en robuustheid (validiteit)* van de uitspraken voor het niveau Vlaanderen: de onzekerheid die we kwantificeren op onze uitspraken (foutmarge en betrouwbaarheidsniveau) is effectief van toepassing op de Vlaamse doelpopulatie. Er zijn dus minimaal of geen aannames waaronder de onzekerheidsbepaling gebeurt. Dit beperkt de bekritiseerbaarheid en leidt tot een grote mate van objectiviteit.
- Inferentie over de **toestand** (spatiotemporeel) gebeurt *design-based en model-assisted*:
    - design-based wegens objectiviteit en validiteit (belang van toestand in MNM)
    - model-assisted om de precisie en accuraatheid van global quantity estimators te verhogen (regression estimator of poststratificatie gebruiken)
- Inferentie over de **trend** (spatiotemporeel) gebeurt:
    - *model-based* voor de temporele component (procesbeschrijving)
    - *design-based* voor de spatiale component (consistent met toestandsbeschrijving)
    
    Met andere woorden, we doen uitspraken over het data-genererende temporele *proces*, concreet voor de spatiaal *gerealiseerde* doelpopulatie.
    Dezelfde aanpak als voor trend (model- én design-based) wordt tevens gevolgd voor de inferentie over de **toekomstige toestand** (derde kernvraag MNM). Het is een verdere toepassing van de aanpak voor de trend. We gaan er in dit rapport niet nader op in.
- Voor een goede interpretatie van monitoringsresultaten is een analyse met potentieel causale factoren wenselijk, i.e. met aanvullende milieuvariabelen en omgevingskenmerken. Er zijn dus inferenties over het proces wenselijk, waarvoor een *model-based* aanpak nodig is. Een design-based projectie van deze steekproefgebaseerde modelresultaten naar de volledige Vlaamse doelpopulatie is aansluitend mogelijk, maar niet noodzakelijk.


## Iets meer over de design-based en model-based aanpak

De essentie van design-based inferenties is dat uitspraken gedaan worden over de spatiaal (spatiotemporeel) *gerealiseerde* doelpopulatie. De populatie wordt dus als 'fixed' beschouwd (het sampling pattern is random), en de onzekerheid op uitspraken (variantie) heeft betrekking op de sampling error: slechts een deel van de *spatiale (spatiotemporele)* populatie is bemonsterd. De parameterschatters en hun variantie hangen daarom geheel samen met het toegepaste type van sampling design (en meer concreet: met de toegepaste inclusion probabilities). De variantieschatting is typisch gebaseerd op de centrale limietstelling. Stochasticiteit wordt enkel geïntroduceerd door de randomness in het sampling pattern en niet via modelassumpties over de doelvariabele. De schattingen voor de gerealiseerde doelpopulatie zijn hierdoor robuust omdat de validiteit van modelassumpties (indien model-assisted) er geen invloed op heeft.

Het doen van uitspraken op basis van een model (model-based aanpak) vertrekt van de assumptie dat het model het datagenererende proces (superpopulatie) voor het geheel van de gerealiseerde doelpopulatie goed beschrijft (dus ook het niet-bemeten deel), waarbij de onzekerheid in uitspraken gebaseerd wordt op de assumpties van het model zelf. De model-based aanpak levert daarom estimators en predictors op die enkel *model*-unbiased zijn, i.e. unbiased onder de assumptie van een valide model. Sampling design en sampling error spelen geen rol in de onzekerheid: het model beschrijft alleen het proces ter hoogte van de bemeten populatie-eenheden en de toepassing ervan voor niet-bemeten populatie-eenheden steunt op de assumptie van valide transfereerbaarheid naar niet-bemeten populatie-eenheden. Wel kan de design een belangrijke invloed uitoefenen op deze validiteit, gezien het effect in praktijk op het gefitte model. Het theoretisch principe is echter dat een 'juist' model niet afhangt van de sampling design: als het model maar alle covariaten op een correcte manier bevat om in alle omstandigheden correcte uitspraken te doen (en dus juist is), dan maakt het niet uit op basis van welke sampling design het model was opgesteld (het kan bovendien ook een mechanistisch model zijn). De populatie wordt in de model-based aanpak als 'random' beschouwd (en het sampling pattern is fixed); het model beschrijft de onzekerheid van het datagenererende proces waarbij de concreet aanwezige doelpopulatie maar één mogelijke realisatie is.

Voor *toestandsuitspraken* waar robuustheid belangrijk is (politiek, maatschappelijk, ...) en bekritiseerbaarheid van modelassumpties en -validiteit (invloed op de schatting) beter vermeden wordt, wordt geadviseerd om design-based te werken. De assumptie dat het model overal valide is, is immers vaak niet vanzelfsprekend.  *Trenduitspraken* daarentegen beogen juist wel het achterliggende, datagenererende temporele proces (veralgemening van de temporele verandering op basis van de metingen), waardoor de temporele component wel met een model wordt genalyseerd (tijdsserie-analyse). De spatiale inferentie kan dan nog steeds design-based gebeuren.

*Voor overwegingen omtrent design- versus model-based aanpak, zie bv. @brus_random_1997, @brus_using_2000, @chambers_introduction_2012, @dobbie_sparse_2008, @lohr_sampling:_2010 en @theobald_using_2007. Nuttige overzichten van design-based mogelijkheden zijn te vinden in @de_gruijter_sampling_2006, @lumley_complex_2011 en @sarndal_model_1992.*
