# Domeinen, subpopulaties, doelparameters en beoogd type van uitspraken

## Afbakening doelpopulatie en domeinen

Spatiaal:

- De *domeinen* voor uitspraken in een meetnet zijn enerzijds de volledige Vlaamse doelpopulatie (= locaties van alle beoogde types in een meetnet) en anderzijds het deel van de doelpopulatie binnen het SBZ-H netwerk. Voor de (niet-verplichte) bijdrage aan de Europese rapportage, geldt tevens het domein 'Atlantisch Vlaanderen'. Deze domeinen liggen voor langere tijd vast, maar zijn niet absoluut constant.
    - we verkiezen om de domeinen niet te laten meespelen in de design, om flexibel te blijven naar de toekomst.
    - in eerste instantie dus abstractie maken van het domein 'SBZ-H-netwerk' en evalueren of de Vlaamse set afdoende informatie geeft voor het SBZ-H-netwerk (subpopulatieschatting via poststratificatie, zie verder). Immers komen de meeste habitatlocaties voor binnen SBZ-H.
- De uitspraken gebeuren gedifferentieerd voor verschillende groepen van types: zg. typegroepen (grootte-orde van een vijftal groepen). Types in een typegroep zijn volgens verwachting nauwer met elkaar 'verwant' inzake de waarde voor beschouwde doelvariabele. De afbakening van typegroepen verschilt per meetnet, en zal langere tijd aan discussie onderhevig blijven (en dus vatbaar blijven voor aanpassing). Hun ruimtelijke verspreiding verandert doorheen de tijd. Het is op niveau van de typegroepen dat een bepaalde precisie wordt nagestreefd.
    - Afgezien van de mogelijks mindere precisie op typeniveau, moet het steeds mogelijk blijven om ook per type nog inferenties te doen, omdat die vraag ook blijft.
- Het is wenselijk om types welgekozen te wegen in de typegroepen, waarbij de gewichten de informatiebehoefte beter tegemoet komen dan de loutere ruimtelijke oppervlakteverdeling tussen types in een typegroep. Bv. op basis van rangschikking volgens beleidsbelang van de types. Daarbij moet ook dit aspect bestand zijn tegen wijzigingen in voorkeuren in de toekomst. We nemen daarom als standaard voor een flexibele design *gelijke* gewichten aan tussen de types in de inferentie over een typegroep. Dus het betreft *gelijke aandelen* van de types in schatters voor een typegroep.

Temporeel:

- Voor toestandsbeschrijving standaard uitgaan van 6 jaar. Is de lengte van één natuurbeleidscyclus.
- Voor trendbeschrijving kijken naar perioden van 12 of 24 jaar (scenario's).
- In beide gevallen is per meetnet aan te geven welke periode binnen het jaar relevant is, en dus de temporele doelpopulatie af te bakenen.

## Doelparameters en beoogd type van uitspraken

Alle vermelde doelparameters betreffen 'global quantity estimators': zij vatten een eigenschap samen van de gerealiseerde Vlaamse doelpopulatie, niet van een superpopulatie.

De centrale analysen voor MNM zijn:

- kwantitatieve beschrijving **toestand**: schatting van spatiotemporeel *gemiddelde* / *SCDF* (kwantielen), met *betrouwbaarheidsinterval*, voor een milieuvariabele in een domein (de vlekken van bepaalde types in Vlaanderen, de vlekken van bepaalde types in SBZ-H-netwerk), over één bepaalde periode (standaard: één programmaperiode van zes jaar).
- kwantitatieve beschrijving **trend**: berekening van de (spatiaal gemiddelde) *meerjarentrend* voor een milieuvariabele in een domein (de vlekken van bepaalde types in Vlaanderen, de vlekken van bepaalde types in SBZ-H-netwerk), over langere tijd (bv. 12, 24 jaar). Met een *toets* die aangeeft of deze trend (gedefinieerd als gemiddelde jaarlijkse verandering) verschilt van nul (indien een lineaire of multiplicatieve benadering zinvol is).

Uitbreiding op bovenstaande toestandsbeschrijving:

- Een variant is dat de 'milieuvariabele' de overschrijding voorstelt van een (evt. locatiespecifieke) drempelwaarde (indien beschikbaar). Hiervan opnieuw schatting van spatiotemporeel gemiddelde / SCDF, met betrouwbaarheidsinterval.
- Een hierop voortbouwende variant is om het percentage van de overschrijding te schatten dat groter is dan nul (+ betrouwbaarheidsinterval) -- ervan uitgaand dat dat de ongunstige situatie voorstelt -- en te toetsen of dit percentage significant groter is dan 25%.

Verdere nodige uitspraken staan in paragraaf 9.3 van het [basisrapport](https://dx.doi.org/10.21436/inbor.13086011). Zie ook mail 1/6/18. We zien ze niet als sturend voor het ontwerp. De analyseroutines zijn wel te ontwerpen.

[Instelwaarden](https://docs.google.com/spreadsheets/d/1IMlLh9EPPRLLoDNWkDzbVJU2cVvst7C8NyJRM2NvujM) zijn reeds voor sommige milieuvariabelen beschikbaar.


