# Doelparameters en beoogd type van uitspraken {#doelparameters}

Alle vermelde doelparameters betreffen 'global quantities': zij vatten een eigenschap samen van de gerealiseerde Vlaamse doelpopulatie, niet van een superpopulatie. Ze worden dus geschat met 'global quantity estimators'.

De basis voor de doelparameters zijn de waarden van een milieuvariabele, met één waarde **per sampling unit**, hetzij per bezoekevent, hetzij geaggregeerd op jaarniveau o.b.v. meerdere herhalingen in een jaar (gemiddeld, gemiddeld hoogste, kwantiel, totale depositie, ...). Aggregatie op jaarniveau is een optie in volgende gevallen:

- ofwel continumetingen
- ofwel niet-continue, herhaalde metingen: dan bij voorkeur in rekening brengen van onzekerheid op de aggregatie (design- of model-based inferentie doen, met een betrouwbaarheidsinterval!)

De centrale analysen voor MNM beogen de volgende doelparameters (in vet en cursief):

- kwantitatieve beschrijving **toestand**: design-based schatting van spatiotemporeel **_gemiddelde_** en optioneel de *SCDF^[SCDF = spatial cumulative distribution function.]* (kwantielen zoals 25- en 75-percentiel), met *betrouwbaarheidsinterval*, voor een milieuvariabele in een domein (de vlekken van bepaalde types in Vlaanderen, de vlekken van bepaalde types in SBZ-H-netwerk), over één bepaalde periode (standaard: één programmaperiode van zes jaar).
- kwantitatieve beschrijving **trend**: berekening van de spatiaal gemiddelde **_meerjarentrend_** voor een milieuvariabele in een domein (de vlekken van bepaalde types in Vlaanderen, de vlekken van bepaalde types in SBZ-H-netwerk), over langere tijd (bv. 12, 24 jaar). De spatiale inferentie is design-based; de temporele inferentie is model-based. Met een *toets* die aangeeft of deze trend (gedefinieerd als gemiddelde jaarlijkse verandering) verschilt van nul (indien een lineaire of multiplicatieve benadering zinvol is).

**Het natuurbeleid hecht het grootste belang aan de toestandsbepaling, en een groot belang (maar dus minder groot) aan trendbepaling.**

Uitbreiding op bovenstaande toestandsbeschrijving:

- Een variant is dat de 'milieuvariabele' de overschrijding voorstelt van een (evt. locatiespecifieke) drempelwaarde (indien beschikbaar). Hiervan opnieuw schatting van spatiotemporeel gemiddelde / SCDF, met betrouwbaarheidsinterval.
- Een hierop voortbouwende variant is om het percentage van de overschrijding te schatten dat groter is dan nul (+ betrouwbaarheidsinterval) -- ervan uitgaand dat dat de ongunstige situatie voorstelt -- en te toetsen of dit percentage significant groter is dan 25%.

Verdere nodige uitspraken staan in paragraaf 9.3 van het [basisrapport](https://dx.doi.org/10.21436/inbor.13086011).<!-- Zie ook mail 1/6/18. --> Het betreft onder meer ook de tweede en derde kernvraag van de MNM. De tweede kernvraag betreft de beoordeling van milieutoestand en -trend, dit t.b.v. 1) de voortgangsbewaking van de G-IHD en 2) de verwerking van actuele toestand en trend in de staat van instandhouding (rol in de specifieke structuren en functies). De derde kernvraag betreft de bepaling van de toekomstige toestand, zowel kwantitatief als beoordeeld (een projectie van vragen 1 en 2 naar de toekomst). We zien deze vragen evenwel niet als sturend voor het *ontwerp*. De analyseroutines zijn wel te ontwerpen.

[Instelwaarden](https://docs.google.com/spreadsheets/d/1IMlLh9EPPRLLoDNWkDzbVJU2cVvst7C8NyJRM2NvujM) zijn voor bepaalde milieuvariabelen beschikbaar [cf. @vanderhaeghe_een_2019].
Het betreft het **gewenste** niveau van de 'informatiekwaliteit', weergegeven als gewenste waarden van *kwaliteitsmaten* bij de respectievelijke doelparameterschatters. Typische kwaliteitsmaten zijn de foutmarge van schattingen, en de power (onderscheidend vermogen) en minimum detecteerbare effectgrootte bij het toetsen van hypothesen. Zij hangen samen met de kansdistributie van de doelparameterschatter.

Bij zowel toestand- als trenduitspraken is het bovendien nodig om met **aanvullende, verklarende gegevens (omgevingskenmerken, aanvullende variabelen)** meer indicatie te verkrijgen over mogelijke oorzaken voor de waargenomen toestand en trend. Dit gebeurt typisch met een modelmatige analyse. Lijsten van bruikbare omgevingskenmerken zijn (nog onvolledig) beschikbaar in google-documenten over [omgevingskenmerken](https://docs.google.com/spreadsheets/d/14jiHfF4vZUlmfPKiry8HCDDt-HFFvhDhW9_SFvtdSkk) en [milieuvariabelen](https://docs.google.com/spreadsheets/d/1gJb2nY-Cs-SCNMpz0sGFslb0j69mzNx5BJu9tQXpHfc).


## Specifiëring van het begrip 'trend' {#trendspecif}

Het betreft steeds een spatiaal gemiddelde trend, hetzij berekend als spatiaal gemiddelde van de locatiespecifieke trend (levert nauwkeuriger resultaat) of als trend van een (bv. jaarlijks) spatiaal gemiddelde (het laatste laat meer flexibiliteit in design en in de voor inferentie gebruikte tijdsspanne, maar is minder nauwkeurig).

Het is belangrijk om te duiden wat we met de temporele component -- dus de feitelijke trend -- bedoelen, de spatiale inferentie buiten beschouwing gelaten. In de monitoring bedoelen we meerdere deelaspecten:

1. de gemiddelde **lineaire (absolute) ofwel exponentiële (proportionele) verandering** per jaar, over een periode van minstens 12 jaar ('meerjarentrend').
    - Deze verandering wordt geschat door een lineaire resp. exponentiële functie te fitten aan de data^[Het komt er op aan een gepaste link-functie en error-distributie toe te passen; voor een exponentieel verband wordt een log-link gebruikt.].
    - De keuze tussen lineair en exponentieel gebeurt enerzijds op basis van de milieuvariabele (wat is ecologisch meest zinvol: absoluut of proportioneel) en anderzijds op basis van de beste fit;
1. het **grafisch** voor te stellen patroon van de verandering in toestand (scatterplot). Deze scatterplot is een belangrijke basis voor de volgende punten [cf. @bart_analysis_2012];^[Tenzij het expliciet gaat om een beschrijving van de bemeten locaties (per locatie of gezamenlijk), wordt in deze grafiek het temporele verloop voor de spatiale doelpopulatie weergegeven met de voor elk jaar (of volgens ander tijdsinterval) geschatte spatiale gemiddelden + betrouwbaarheidsintervallen.]
1. de kenmerken van het **best passende model** op basis van de data, dat dus beter aan het grafiekpatroon tegemoetkomt dan een lineair of exponentieel model maar zonder overfitting (een informatiecriterium wordt hiervoor gebruikt in de modelbouw);
1. een procesgerichte en/of milieudrukgerichte **interpretatie** van de trendmodellering op de bemeten locaties:
    - rechtstreeks afgaande op de kenmerken van voorgaande uitkomsten;
    - of door aan het model spatiale en/of temporele covariaten toe te voegen, die invloed hebben op het abiotische proces (o.m. antropogene activiteit) en de modelparameters te interpreteren (cf. hoger).

Alleen de twee eerste deelaspecten hanteren methoden die vergelijkbaarheid opleveren gedurende opeenvolgende rapporteringscycli en die routinematig (semi-geautomatiseerd) kunnen worden uitgevoerd. De andere deelaspecten beogen meer maatwerk per cyclus, en dienen om interpretaties te verbeteren. Zij vergen een aanzienlijke personeelstijd om dit voor verschillende milieuvariabelen (miliedrukken; meetnetten) recurrent te kunnen uitvoeren.

De lineaire of exponentiële trendmodellering levert een modelgebaseerd betrouwbaarheidsinterval voor de modelparameters (en dus rond het gemiddelde verloop). Indien de modellering locatiespecifieke trends schat (i.e. voor de bemeten locaties), dan zal via spatiale inferentie de spatiale onzekerheid worden berekend en weergegeven voor zowel de locatiespecifieke modelpredictie van de *trend* als diens bijhorende (locatiespecifieke) *grenzen* van het betrouwbaarheidsinterval. Zie ook paragraaf \@ref(inferentiewerkwijze), @stevens_spatially_1999 [p. 423 onderaan] en @de_gruijter_sampling_2006. Dezelfde spatiale doorvertaling kan desgewenst ook gebeuren voor modellen-op-maat met verklarende componenten.

In het kader van het **ontwerp** richten we ons voor het aspect 'trend' best op de precisie van een lineaire ofwel exponentiële trendparameter, na de spatiale inferentie. Meer concreet kan worden gekeken naar de power van de toets of de spatiaal gemiddelde trend verschillend is van nul. Het betrouwbaarheidsinterval op de trendparameter wordt hiervoor bepaald door de spatiale CI-bovengrens van de locatiespecifieke CI-bovengrens en de spatiale CI-ondergrens van de locatiespecifieke CI-ondergrens.



