# Steekproefstrategie

## Stratificatie, typegroepen en steekproefstrategie

Gelijkwaardig willen belichten van types en uitspraken doen over typegroepen: dit kan eventueel met een gestratificeerde design volgens de types, onafhankelijk van de indeling in typegroepen. Binnen elk stratum wordt dan gewerkt met gelijke inclusiekansen. De inclusiekansen worden steeds bijgehouden (evolutie treedt op t.g.v. veranderingen in doelpopulatie en non-response).

Zowel stratificatie volgens types als non-stratificatie geven flexibiliteit t.a.v. de definitie van typegroepen.

Domeinschatting (bv. SBZ-H) gebeurt door subpopulatieschatting via poststratificatie: gewichten worden post-hoc aangepast (binnen de inferentie), rekening houdend met de gekende poststrata-groottes en niet a priori (via stratificatie in design). Zo vermijden we inflexibiliteit.

Het toepassen van een staged design (getrapte steekproef) brengt, hoewel mogelijks kostenefficiënter, extra zorgen en beperkingen mee door ongelijke (maar niet in de tijd constante) sampling weights, de evolutie van de doelpopulatie in de tijd (en dus herzien van de steekproef). We verkiezen dus per type voor gelijke inclusiekansen t.b.v. maximale flexibiliteit.

Kortom, substructuur in een meetnet zorgt voor beperkingen of complicaties later. Daarbij komt ook dat zowel typegroepen als types evolueren in hun definitie. Zie onder meer @overton_desirable_1996 en @manly_sampling_2014.

Uitgaande van de eerder gestelde principes zijn er maar twee robuuste en relatief eenvoudige alternatieven voor de opdeling van de meetnetten, die een spatiale balans en voldoende flexibiliteit gemeen hebben:

- het idee van wegingen van types laten varen, en genoegen nemen met een equiprobable sample voor de hele doelpopulatie van een meetnet. Dit impliceert dat inferentie over typegroepen en types gebeurt als subpopulatieschattingen (via poststratificatie), en dat de precisies hiervan volledig van de *total* sample size afhangt en niet op maat gestuurd wordt.
    - dit is vrijwel zeker goedkoper, maar heeft een vrij beperkt toepassingsgebied en biedt weinig controle over precisie van subpopulation estimates.
- stratificeren volgens types, met lage-precisie-uitspraken per stratum (type). Een samengestelde estimator voor de typegroep kan dan post-hoc worden berekend als een (al dan niet gelijk gewogen) gemiddelde van de types. De variantie van deze afgeleide estimator is functie van de typespecifieke varianties. De steekproefgrootte per type heeft op die manier doorwerking in de precisie van uitspraken per typegroep, die de trigger is om de typespecifieke steekproefgroottes te kiezen (evenredig met de typespecifieke standaardafwijking en met finite population correction).
    - dit heeft het voordeel van onafhankelijkheid tussen de verschillende types, en geeft beter zicht op concrete types
    - indien nodig kan een type (ook in een later stadium) intensiever worden gemeten zonder dat dit inferentieprocedures compliceert.
    - dit laat tevens toe om voor bepaalde types de populatie-eenheden anders in te vullen (bv. plassen)
    - bemerk dat hoe meer types een typegroep telt, hoe minder nauwkeurig de typespecifieke uitspraak zal zijn en hoe goedkoper de totale opzet. Er wordt immers gestuurd op precisie op niveau van de typegroep.

Belangrijk bij een zo breed inzetbare steekproefstrategie is dat de effectiviteit (hoge precisie) bekomen wordt door 1) de spatiale balancering, 2) een goede temporele spreiding (revisit design) en 3) het gebruik van auxiliary information door regression estimators te gebruiken (model-assisted design).



## Spatiaal

GRTS als basis voor een goede ruimtelijke spreiding (~ efficiëntie van schatters) en voor maximaliseren van de koppeling met meetnet biotische habitatkwaliteit.

- Celgrootte van 32 x 32 m² als basis voor de populatie-eenheid van terrestrische en semi-terrestrische types (overnemen grid van meetnet biotische habitatkwaliteit).
    - Overweging: voor bepaalde milieuvariabelen een trap hoger werken in de hiërarchie
- Segmenten van waterlopen en individuele plassen zijn de populatie-eenheden voor aquatische types, maar dit is compatibel met een GRTS-trekking.

<!-- Te overwegen opties: -->

<!-- - GRTS (equal probability): beste ruimtelijke dekking, grootste eenvoud en flexibiliteit, maar vermoedelijk minder kosteneffectief -->
<!-- - two-stage GRTS met per meetnet geoptimaliseerde grootte van de PSU's (primary sampling units). De PSU's zijn dan hogere-orde rastereenheden van het GRTS-grid. -->
<!--     - voordeel ten opzichte van ruimtelijk variërende geografische eenheden (PSU's zoals gemeenten, fysische systeemeenheden, ecodistricten, ...) op maat van elk meetnet, is de grotere consistentie en overlap tussen de meetnetten, de gelijke ruimtelijke dekking per PSU en de eenvoud om te up- of downsizen (ontwerpscenario's) volgens de noden. -->
    
GRTS master sample gebruiken van het meetnet biotische habitatkwaliteit om de koppeling te maximaliseren

- De doelpopulatie (steekproefkader) van een concreet meetnet (bv. verdroging via grondwater) is een subset hiervan: combinaties van Vlaamse X, Vlaamse Y en de voorkomende types (beperkt tot deze die we voor het meetnet viseren). Eén XY-coördinaat kan meerdere types bevatten.

<!-- Aandachtspunt: de aquatische types. Minstens voor atmosferische meetnetten wordt dezelfde milieuvariabele beoogd voor terrestrische en aquatische types. Het heeft daarom meerwaarde om ook de aquatische types binnen dezelfde opzet mee te nemen, om de uitspraken los van aquatisch of terrestrisch te kunnen doen (want ook de atmosferische typegroepen zullen gemengde terrestrisch-aquatische groepen zijn). Het verschil met terrestrisch zit dan vooral in de terreinprocedure, gegeven een getrokken 32 m² cel: -->

<!-- - stilstaande wateren: de volledige plas is habitat indien er habitat aanwezig is in de plas. Dus de gehele plas wordt door de geselecteerde gridcel vertegenwoordigd. In het kader van inferenties zijn dan voor plassen met meerdere geselecteerde cellen twee opties mogelijk (beide hebben volgens Luc meerwaarde): -->
<!--     - ofwel de observatie slechts één keer tellen en dus alle plassen even sterk laten wegen. Dezelfde benadering moet dan gebeuren in de bepaling van de populatiegrootte (mbv steekproefkader) bij poststratificatie. -->
<!--     - ofwel de observatie voor elke geselecteerde gridcel laten meetellen, en dus het oppervlakte-aspect laten meespelen. -->
<!-- - stromende wateren: segmenten uit het steekproefkader selecteren die overlappen met een geselecteerde gridcel. De observaties van deze segmenten zijn te koppelen met de gridcel(len) die zijn geselecteerd. -->
    
<!-- Koppeling meetnet biotische habitatkwaliteit: -->

<!-- *XXX nog bekijken hoe in habitatkwaliteit concreet is samengespoord met initiatieven van specifieke typeklassen (duinen, ...), om te evalueren hoe groot onze afwijking daarvan zal zijn. Default reflex: niets aan te doen. Tijdelijke tussenoplossingen (cf. overgangsfase grondwatermeetnet): E[schatter] heeft ongekende bias* -->

## Temporeel


Noot: er is geen temporele design van toepassing indien volledige tijdsreeksen beschikbaar (cf. grondwaterstanden met loggers / jaarlijkse data van elke locatie). Er blijft in dat geval *wel* onzekerheid op trendschatters vermits deze model-based worden geschat.

- systematisch samplen (bv. jaarlijks, maandelijks). Nadeel is wel mogelijke onderschatting van de variantie, mede afhankelijk van hoe de temporele doelpopulatie is gedefinieerd.
- minstens jaarlijks data verzamelen, want:
    - jaarlijks een gelijkaardige inspanning leveren: goede spreiding bekomen om trendvorm te kunnen bekijken + goede spreiding voor spatiotemporele toestandsbepaling
    - afhankelijk van de milieuvariabele is de aggregatie op jaarniveau de basis voor analyse en inferenties. Bv. XG3's
- indien significante variatie optreedt binnen een jaar (cf. resultaten van modelwerk): het effect bepalen van meerdere keren bemonsteren per jaar op precisie van spatiotemporele toestand en van de trend

## Spatiotemporeel

<!-- Mede afstemming nodig met strategie in meetnet biotische habitatkwaliteit (-> ? serially alternating pattern op jaarbasis, met bijstelling steekproef elke 12 jaar, en dus vasthouden aan locaties?) Pilootmonitoring abiotiek oppervlaktewater: volgt nu binnen elk jaar een pure panel-aanpak (repeated sampling). -->

### Over jaren heen

Merk op dat de doelpopulatie ruimtelijk zal evolueren met de tijd. Daarom zesjaarlijks of vaker (bv. in opvolging van nieuwe versies habitatkaart) het steekproefkader bijwerken en trekking overeenkomstig aanpassen.

De nodige steekproefgrootte kan verdeeld worden over meerdere panels om de behoefte aan toestand- en trendinformatie te balanceren (beide belangrijk, toestand meest belangrijk).

De verdeling van steekproefelementen over panels komt neer op een opdeling van de steekproef in subsamples. Bij de toewijzing per jaar proberen we de volgende doelstellingen te combineren:

- ruimtelijke balans en dekking per jaar (zodat de data van elk jaar op zich ook als ruimtelijk gebalanceerde steekproef dienst doen);
- enkel indien veel punten zijn te bemonsteren per jaar: per jaar de steekproefelementen ruimtelijk méér bundelen dan het geval is voor de steekproef over meerdere jaren (beperking van verplaatsing geeft kostenefficiëntie).

Dit is mogelijk door voor de toewijzing aan panels een GRTS-rangschikking op een hoger hiërarchisch niveau te gebruiken dan het niveau dat wordt gebruikt voor de steekproefelementen. Bv. voor panels hokken selecteren van ca. 1-enkele km²; het betreft dus een verdeling over de panels van alle hokken die de reeds getrokken steekproefelementen omvatten, en dit op zo'n manier dat het aantal steekproefelementen per jaar gelijkaardig is (panels met repeated measures in rekening genomen). Alle steekproefelementen die tot de voor één panel getrokken hokken behoren, rekenen we dus tot het betreffende panel.

De grootste kostenefficiëntie zou bereikt worden door hetzelfde hokkenpatroon toe te passen voor zoveel mogelijk MNM-meetnetten samen, maar deze synergie vereist tevens dat die meetnetten een sterk overlappende spatiotemporele design volgen. I.e. gelijk aantal panels en gelijke panel design.

Panel-notaties hieronder volgen @mcdonald_review_2003.

<!-- #### Geen vaste meetinstallaties -->

<!-- Cf. oppervlaktewater, bodem, evt. atmosfeer, evt. overstromingswater. -->

<!-- Hier verkiezen we een balans tussen repeated measurements voor trendinformatie en steeds 'nieuwe' locaties voor steeds betere toestandsinformatie en beperking van herhaalde verstoring en invloed (i.e. 'nieuw' zolang het steekproefkader nieuwe locs voorziet, daarna herbeginnen). -->

<!-- Een mogelijke opzet hiervoor is een split panel als volgt: -->

<!-- - enerzijds panels die éénmalig of hooguit twee keer bemonsterd worden, dus hetzij synchronous sampling [1-n] hetzij rotational sampling bv. [2-n] of een variant zoals [1-2-1-n]. -->
<!--     - de synergie van deze veranderende sets met het meetnet biotische habitatkwaliteit is dus automatisch kleiner, maar kan tussen de compartimentmeetnetten onderling wel worden gemaximaliseerd. -->
<!-- - anderzijds 1 tot 3 panels met repeated measurements, i.e. pure panel [1-0] (jaarlijks) of een serially alternating pattern [1-1] (tweejaarlijks) of [1-2] (driejaarlijks). Deze 'vaste' set blijft wel onderhevig aan revisie ivm evolutie van het steekproefkader (maar er wordt zoveel mogelijk aan dezelfde locaties vastgehouden). -->

<!-- De opzet gebeurt zodanig dat jaarlijks ongeveer eenzelfde aantal locaties wordt bemonsterd. De steekproefverdeling binnen een jaar is bv. 1/2 voor het pure panel en 1/2 voor nieuwe of laagfrequente locaties. -->


<!-- #### Vaste meetinstallaties -->

<!-- Cf. grondwater, atmosfeer, evt. overstromingswater. -->

Omdat veel non-responses optreden bij een eerste bezoek van nieuwe locaties (cf. rotational sampling, synchronous sampling), wordt gewerkt met een vaste set locaties (blijft wel onderhevig aan revisie ivm evolutie van het steekproefkader, cf. hiervoor). Dit is ook opportuun voor locaties met een vaste meetopstelling zoals peilbuizen. De synergie met meetnet biotische habitatkwaliteit hierdoor ook het grootst. Om enerzijds detailinformatie te bekomen over trend en anderzijds om de sampling-intensiteit te blijven beheersen, is eventueel een split panel te overwegen (zoniet: gaan voor het serially alternating pattern):

- enerzijds panels die laagfrequent worden bemeten: serially alternating pattern, bv. volgens design [1-3], [1-4], [1-6] of [1-12].
- anderzijds 1 pure panel [1-0] (jaarlijks).

De terugkeerperiode wordt best ingeschat op basis van de milieuvariabele:

- ingeschatte snelheid van verandering
- duurtijd en effect van verstoring

Andere overweging voor terugkeerperiode: samensporen meetnet biotische habitatkwaliteit? (kostenefficiënter?)

De opzet gebeurt zodanig dat jaarlijks ongeveer eenzelfde aantal locaties wordt bemonsterd. De steekproefverdeling binnen een jaar is bv. 1/2 voor het pure panel en 1/2 voor laagfrequente locaties.


### Binnen een jaar

Optimalisatie mogelijk van de pure-panel aanpak binnen één jaar (cf. chemie waterkolom, zienswijze ICP, ...)? Enkele mogelijkheden:

- spatiale opzet variëren binnen een jaar:
    - rotating panel
    - serially alternating panel
    - synchronous sampling, systematisch in tijd (independent panels)
- tijdstippen binnen een jaar variëren:
    - frequentie van bezoeken is te variëren
    - begin- en eindtijdstip van de periode (~ indien verantwoord volgens vraagstelling)


