# Overgangsfase voor bestaande meetinstallaties: strategie

Voor sommige meetnetten met reeds een zekere historiek, kan een overgangsfase worden voorzien in MNM.
Een voorbeeld zijn piëzometers.

Een dergelijke overgangsfase is een benadering om bestaande monitoringdata nog een periode te blijven gebruiken voor inferenties, terwijl de nieuwe aselecte steekproef nog wordt opgebouwd. Dit heeft zin omdat ter hoogte van de nieuwe locaties nog geen historische tijdsreeksen beschikbaar zijn, terwijl dat wel zo is op verschillende bestaande locaties. Omdat door het betrekken van bestaande locaties een ongekende vertekening optreedt (het betreft een judgment sample, geen probability sample), die niet ondervangen kan worden door de betrouwbaarheidsintervallen in de inferentie, dient de inferentie over toestand en trend in Vlaanderen met het nodige voorbehoud te gebeuren zolang meetlocaties uit een judgment sample worden gebruikt.

Dit is daarom te zien als overgangsfase, tot wanneer in de aselecte set voldoende lange tijdsreeksen zijn opgebouwd zodat inferenties op basis van enkel de aselecte set kunnen gebeuren. Bestaande meetlocaties kunnen ook dan nog een rol blijven spelen in de inferentie (zie verder), en zullen daarnaast vaak ook een rol blijven spelen om andere redenen dan MNM (modelcalibratie, lokale toepassingen).

Tevens is er de mogelijkheid bestaat dat sommige *aselect* getrokken locaties (nieuwe steekproef) samenvallen met bestaande locaties. In dat geval kan de bestaande locatie wel blijvend worden betrokken voor de inferentie in MNM.

- Opzet: tijdelijk blijven werken met welgekozen, bestaande reeksen om 'status- en trendbepalingen onder voorbehoud' te kunnen doen.
- Het 'werken met bestaande meetreeksen' wordt beperkt tot kwaliteitsvolle reeksen en zoveel mogelijk ruimtelijk gebalanceerd, waarbij tekorten worden bijgepast:
    - vooreerst is aan elke meetreeks een kwaliteitslabel te hangen ivm kwaliteit van de data (zoals lengte van de meetreeks, volledigheid, wordt nog opgevolgd, enz.)
    - enkel bestaande meetlocaties ter hoogte van *een type uit de doelpopulatie* komen in aanmerking
- Intussentijd wordt het nieuw uitgewerkt meetnet geïnstalleerd om reeds op kortere termijn (na 6 jaar) representatieve toestandsbepalingen te kunnen doen. Voor trend is dit maar betrouwbaar mogelijk na 12 of meer jaren.
- Na ca. 12 jaar kunnen de beide sets met elkaar worden vergeleken om verschillen tussen de sets te onderzoeken, indien de power van deze toets groot genoeg is om relevante verschillen te detecteren. Dit vooral om te kunnen evalueren of de eerdere toestands- en trendbepalingen aangehouden kunnen worden.
    - Ongeacht of een verschil wordt gevonden, blijft een robuuste design-based inferentie niet mogelijk met een judgment sample: inferenties blijven vatbaar voor kritiek en daarom moeilijk te verdedigen. De vergelijking beschouwt namelijk alleen verschillen voor de *onderzochte kenmerken*, in de *beschouwde periode* en met slechts *één* aselecte steekproef. Alleen wanneer de doelpopulatie zelf gekend is, kan een vertekening correct in beeld worden gebracht.
    - De oudere meetreeksen kunnen in principe wel nog steeds bijdragen aan de precisie en juistheid van de inferentie met nieuwe meetpunten, dit via de modelcomponent van model-assisted design-based inference (cf. @brus_method_2003).

<!--     - binnen die selectie wordt per type verder geselecteerd op zodanige manier dat: -->
<!--         - de ruimtelijke balans per type optimaler is: -->
<!--             - daarbij werken met het GRTS-grid (rangschikking buiten beschouwing). Er wordt alleen gewerkt met de cellen binnen de subpopulaties (types) -->
<!--             - in stapsgewijs grotere celgroottes tewerk gaan en per cel telkens slechts één peilbuis overhouden (obv GRTS-rangschikking). -->
<!--             - vertrekken vanaf het kleinste celniveau -->
<!--         - het behouden aantal peilbuizen niet te klein is (toetsing met gewenste steekproefgrootte voor het type in kwestie) -->
<!--     - de selectie (per subpopulatie) wordt verder aangevuld opdat de balans verder verbetert. Binnen de laagst gehanteerde resolutie (grootste cellen) met elk één peilbuis gebeurt voor deze grovere cellen, die overlap hebben met een subpopulatie maar *geen* bestaande peilbuis hebben, een aanduiding van één nieuwe peilbuis op basis van de kleinste cellen van het feitelijke GRTS-grid, namelijk deze met het laagste GRTS-rangnummer. Dit levert on the whole een redelijke ruimtelijke balancering op per type. -->

<!-- **Of:** -->

Werkwijze: gebalanceerde set met deels bestaande meetlocaties (per type): sowieso pas na vergelijking van scenario's, om de nodige steekproefgrootte te kunnen beslissen. Verdeling van punten is grid-based mogelijk volgens methode in @stevens_spatially_2004, waarbij:

- een evaluatieraster wordt gekozen, bv. 512 x 512 m² of grover, dat goed de ruimtelijke heterogeniteit van de doelpopulatie weerspiegelt (vooral dan de densiteit van een type), en dat bruikbaar is in relatie tot de nodige steekproefgrootte en de reeds beschikbare meetlocaties;
- voor beschikbare meetlocaties alleen de 'kwaliteitsvolle' bekeken worden;
- per evaluatiecel het aantal volgens celpopulatiegrootte 'verwachte' meetlocaties in de steekproef wordt nagestreefd: indien er méér beschikbaar zijn, een random subselectie maken (GRTS-based); indien er te weinig zijn: aanvullen met random punten van de steekproeftrekking. In dat geval kan eveneens met een evaluatieraster worden gewerkt binnen de evaluatiecel, teneinde de ruimtelijke balans van nieuwe punten ten opzichte van bestaande punten te bewaren.



