# Keuze van een scenario, steekproeftrekking en uitwerking van een meetplan

Op basis van de vergelijking van scenario's wordt één scenario verkozen. Gekoppeld aan dit scenario wordt nog eens extra kritisch gekeken naar de flexibiliteit: kan de inferentie eenvoudig blijven gebeuren indien:

- de doelpopulatie wijzigt?
- de domeinen wijzigen?
- de typedefinities wijzigen?
- de typegroepdefinities wijzigen?
- een flink deel non-responses optreedt (uitval medewerker, ...)?
- de keuze van primaire milieuvariabelen wijzigt, bv. omdat een meetmethode wijzigt?
- de keuze van doelparameters wijzigt?
- attributen wijzigen van de spatiale, temporele en revisit design (verdeling van locatie over panels, ...), inclusief steekproefgrootte?

Indien zij nodig zijn, zullen de meeste van bovenstaande wijzigingen op een welgekozen moment worden geïmplementeerd in het kader van een revisie. Er dient een één-op-één verband te zijn met een aanpassing aan de vraagstelling. Daarbij is het belangrijk dat de coherentie van de MNM (overeenstemming in vraagstelling tussen meetnetten) niet in het gedrang komt.

De met het verkozen scenario verbonden spatiale design wordt gebruikt om een ruimtelijke **steekproeftrekking** te doen met GRTS (grid van meetnet biotische habitatkwaliteit).
Een belangrijke basis voor de trekking is het **steekproefkader**, dat de best beschikbare beschrijving is van de doelpopulatie: de *lijst van alle steekproefeenheden* met alle voor de steekproeftrekking en voor de inferentie nodige *attributen*.

Bij de trekking wordt uitgegaan van *steekproefgroottes* per type die rekening houden met:

- tussen (groepen van) types verschillend ingeschatte variabiliteit, inzoverre nog niet vervat in het model (steekproefgrootte evenredig bijstellen met variantie);
- finite population correction;
- overbemonstering voorzien wegens onvolkomenheden in het steekproefkader:
    - te baseren op de actuele kwaliteit van het steekproefkader in het meetnet biotische habitatkwaliteit;
    - voorts conform aanpak biotisch meetnet: a rato van de verhouding van de polygoonoppervlakte van het type in de habitatkaart en de geschatte 'werkelijke' oppervlakte van het type met het oppervlaktepercentage volgens de habitatkaart.
    
Een **meetplan** wordt opgesteld waarbij de temporele design en revisit design van het verkozen scenario wordt toegepast op de spatiale steekproef (in overeenstemming met hoofdstuk \@ref(steekproefstrategie)). Een *response design* (paragraaf \@ref(response-design)) wordt toegevoegd, en wordt geoperationaliseerd in een of meerdere protocollen. Het vaststellen of een steekproefeenheid tot de doelpopulatie behoort, is een gemeenschappelijk deel van de response design voor alle meetnetten. Ook is het belangrijk om aan te geven *welke acties nodig zijn* wanneer een steekproefeenheid niet tot de doelpopulatie behoort of bij non-response (ontoegankelijkheid, niet-meetbaarheid, verlies van staal, vandalisme meetopstelling, ...).

Daarnaast is ook een *reservelijst van locaties* nodig, niet alleen ter vervanging van steekproefeenheden die buiten de doelpopulatie vallen, maar ook voor het geval tijd resteert. Immers wordt het (verwachte) optreden van problemen (vertragingen) meegerekend bij het evalueren van scenario's. In sommige gevallen kan dit meevallen en dan is er extra tijd beschikbaar. Een *protocol* bepaalt hoe hiermee wordt omgegaan. Daarbij is te bepalen hoe een nieuwe locatie wordt toegewezen aan een panel (zie paragraaf \@ref(revisit-design)).

In het meetplan worden ook verdere aandachtspunten vermeld voor de implementatie van het terreinwerk, en zijn verdere todo's opgelijst voor de uitbouw van de data-, verwerkings- en communicatieketens (zie takenlijst meerjarenplanning MNM: o.a. opslag, koppeling en documentatie van data, verwerkingsprocedures en resultaten). In verband met de implementatie kunnen bijvoorbeeld voorafgaandelijke terreinbezoeken nodig zijn om te verifiëren dat een locatie tot de doelpopulatie (het beoogde type) behoort, wanneer bemonstering in de winter gebeurt.

Vóór of tijdens de implementatieperiode zijn in het kader van de verwerking ook de zaken te onderzoeken die nog niet in het ontwerp aan bod kwamen: 

- het beschikbaar maken van auxiliary variables, en het effect ervan op de nauwkeurigheid onderzoeken. En dus de R-scripts voor de inferenties en bijhorend databeheer;
- voorafspiegeling van een complete analyse en interpretatie (met verklarende variabelen) in MNM. En dus de bijhorende R-scripts en databeheer;
- inbrengen van het GRTS-aspect in de design-based verwerkingsroutines.
