# Inferentie

Betreft het doen van uitspraken over de doelpopulatie op basis van een steekproef. De onderstaande methoden worden toegepast in de monitoring zelf, maar in principe ook voor de gesimuleerde steekproeven in de ontwerpfase, met dat verschil dat voor het ontwerp vereenvoudigingen en aannames gebeuren (zie onder).

## Subpopulaties voor inferentie

De schattingen voor typegroepen gebeuren:

- in het geval van één eenvoudig totaalmeetnet door subpopulatieschatting via poststratificatie
- in het geval van strata (met lage precisie) volgens type: met een samengestelde (afgeleide) estimator: (al dan niet gelijk gewogen) gemiddelde van de types

Voor zowel toestand als trend zijn schattingen mogelijk voor verschillende subpopulaties. Alnaargelang de design gebeurt alles door subpopulatieschatting via poststratificatie of gebeuren berekeningen post-hoc met een samengestelde estimator:

- voor de gehele doelpopulatie van een meetnet in Vlaanderen
- voor de doelpopulatie binnen het SBZ-H-netwerk (zonder onderscheid tussen typegroepen)
- voor de typegroepen in Vlaanderen 
- voor de typegroepen, binnen het SBZ-H-netwerk
- voor de feitelijke types in Vlaanderen
- voor de feitelijke types, binnen het SBZ-H-netwerk
- voor andere mogelijke groeperingen van types, in Vlaanderen
- voor andere mogelijke groeperingen van types, binnen het SBZ-H-netwerk

Bij subpopulatieschatting via poststratificatie conditioneren we de grootte van de sample weights zodanig dat het geschatte aantal units van de subpopulatie gelijk is aan het werkelijke aantal units van de subpopulatie in het steekproefkader. Zie @overton_desirable_1996.


## Gebruik van omgevingskenmerken (auxiliary variables)

Voor een meer accurate en precieze inferentie wordt gebruik gemaakt van informatielagen met een gekende waarde voor de gehele doelpopulatie en die correleren met de doelvariabele.

De design-based schatters betreffen dus zoveel mogelijk regression (of ratio) estimators (mbv continue auxiliaries), en/of zijn gebaseerd op poststratificatie met een categorische auxiliary, zodat de juistheid en precisie verhogen. Bemerk dat dit in de ontwerpoefening voorlopig alleen als een design-effect wordt meegenomen, of helemaal niet (conservatief). Bij revisies van de meetnetten kan dit meer concreet meespelen in steekproefgroottebepaling.

De **modelvorm** van het verband tussen de auxiliary component (kan een constructie zijn met meerdere covariaten in ruimte en tijd) en de responsvariabele zodanig kiezen dat de best mogelijke correlatie (spatiaal en / of temporeel) wordt bekomen met de responsvariabele. Behalve de aangewezen covariaten (die voor de gehele doelpopulatie gekend moeten zijn!) dus ook spatiale en temporele dependency inbouwen. Het model kan voor meerdere of alle types samen worden opgebouwd, desgevallend gebruik makend van een covariaat type of typegroep. Zolang de predicties maar redelijk zijn.

Een regression estimator bevat minstens twee *pi-estimators* (design-based: de respons + één per covariaat van de auxiliary) en minstens één *gekende parameter* van de (sub)doelpopulatie (één per covariaat van de auxiliary). Bij poststratificatie worden de sampling weights bijgesteld [@de_gruijter_sampling_2006; @lumley_complex_2011; @overton_desirable_1996].

## Werkwijze van inferentie {#inferentiewerkwijze}

Praktisch: zoveel mogelijk terugvallen op R-packages zoals het `survey` package, `spsurvey` e.d. NB. voor de SE-schattingen van kwantielen worden daarbij (intern) typisch resampling procedures zoals bootstrapping toegepast.

Toestand + trend spatiaal: steeds naar typegroepen toe werken, hetzij met een samengestelde estimator op basis van type-strata, hetzij via subpopulation estimation (via poststratificatie) op basis van één totaalmeetnet.

Toestand:

Afhankelijk van de concrete steekproefstrategie in een meetnet, de overeenkomstige formules toepassen. Typisch eerst spatiaal aggregeren en daarna temporeel, vermits het spatial sampling pattern verandert in de tijd. Meer in het algemeen de correcte estimator gebruiken in overeenstemming met de design.

Indien er repeated measurements voorkomen binnen de periode waarover een spatiotemporele aggregatie gebeurt (units die meerdere keren zijn bemeten), zoals in rotational en split panel designs, kan de spatiotemporele inferentie beter in één beweging gedaan worden waarbij repeated measurements worden downweighted in de analyse (zie @lumley_complex_2011 par. 3.4).

<!-- Mogelijks als een multi-stage sample te analyseren (PSU's: jaren). -->

Trend:

- verandering in tijd van de milieuvariabele wordt beschreven met een model
- over een beschouwde periode van $x$ keer 6 jaar ($x$ > 1)
- bv. lineair: trend = (gemodelleerde) vaste toe- of afname per jaar

Werkwijze voor de spatiale aggregatie:

- Wat altijd werkt: spatiaal aggregeren en daarna toepassen in een model om de temporele trend te analyseren. In het bijzonder bruikbaar bij non-static designs. Het model moet rekening houden met de autocorrelatie. Advies in @de_gruijter_sampling_2006: weighted least squares regression of spatial means, with weights inversely proportional to variances of spatial means.
- Alternatief is eerst volledig model-based werken (spatiaal en temporeel), op basis hiervan de locatiespecifieke trend voorspellen (voor alle sample units afzonderlijk), en vervolgens spatiaal een design-based inferentie doen (volgens subpopulaties enz.). Dit is wellicht krachtiger (lokaal variërende trend is toegelaten), en het doet geen geweld aan de design-based ruimtelijke inferentie.
    - Het betrouwbaarheidsinterval op de trendparameter wordt dan bepaald door de spatiale CI-bovengrens van de locatiespecifieke CI-bovengrens en de spatiale CI-ondergrens van de locatiespecifieke CI-ondergrens. Zie ook paragraaf \@ref(trendspecif).
- Nog een alternatief is een two-phase sampling aanpak om de locatiespecifieke trend op basis van niet-complete tijdsreeksen te corrigeren op basis van het regressieverband tussen 'complete trend' en 'niet-complete trend' voor een panel met complete tijdsreeksen, als dit verband er is (bv. een pure panel in een split panel design). Zie @stevens_spatially_1999 [p. 426] en @de_gruijter_sampling_2006.

## Finite population correction

Voor alle design-based onderdelen van de inferenties, i.e. de volledige toestandsbepaling (spatiotemporeel) en de spatiale component van de trendbepaling, wordt er rekening gehouden met de "finite population correction". De variantieschatter van elke (regression) estimator (dit kan dus per type zijn) wordt daartoe vermenigvuldigd met $(1- n/N)$ waarbij:

- $N$ staat voor het totale aantal units van de betreffende (sub)populatie in het steekproefkader
- $n$ staat voor het aantal sample units


