# (APPENDIX) Bijlagen {-}

# Bijlage: motivatie voor de meetnetten natuurlijk milieu {#app:motivatie}

-   Het natuurlijk milieu speelt een zeer grote rol in de kansen voor
    ontwikkeling of behoud van een levensgemeenschap. Bijvoorbeeld geeft
    het vierde Milieubeleidsplan (MINA 4) aan dat de **belangrijkste
    randvoorwaarde** voor de biodiversiteitsdoelstellingen in het
    natuurbeleid de goede lokale milieukwaliteit is.
-   De basisreden waarom de MNM in Vlaanderen worden opgezet, is dat
    diverse **milieudrukken** de beoogde toestand van habitattypes in
    belangrijke mate verhinderen of bedreigen. Milieudrukken zijn in die
    mate aanwezig dat ze het actieve natuurbeleid belemmeren bij het
    realiseren van de gewestelijke natuurdoelen.
-   De invloed van milieudrukken in Vlaanderen verklaart de grote nood
    aan natuurgerichte milieu-informatie om het **actieve natuurbeleid
    te ondersteunen**. Een belangrijke taak van het actieve natuurbeleid
    bestaat er in om het kader en de maatregelen(programma’s) te
    voorzien opdat de milieuknelpunten voor natuur zouden
    worden opgelost. De MNM ondersteunen het natuurbeleid voor:
    -   *planning*: prioriteiten en een aanpak opmaken voor elke
beleidscyclus;
    -   *onderbouwing*: beleidsverantwoording naar andere
beleidsdomeinen, sectoren, en het bredere publiek;
    -   *evaluatie*: bepalen waarom de staat van instandhouding niet of
onvoldoende de gewenste kant uitgaat + voortgangsbewaking van
de realisatie van de G-IHD en het Vlaams Natura 2000 Programma
(partim milieuvoorwaarden);
    -   *bijsturing* van het beleid: prioriteiten, regelgeving,
maatregelprogramma’s, milieubeleid.

-   Er bestaan in Vlaanderen diverse milieumeetnetten. Er **ontbreekt**
    echter een systematische monitoring van het natuurlijk milieu van
    Natura 2000 habitattypes in Vlaanderen.
-   Als voornaamste juridische beweegreden geldt **artikel 50undecies
    van het Natuurdecreet**. Zowel de staat van instandhouding als
    *(potentiële) oorzaken van achteruitgang ervan* dienen via
    monitoring te worden opgevolgd in Vlaanderen. Daarnaast zijn de
    monitorings- en rapporteringsverplichtingen volgens de
    Habitatrichtlijn (artikels 11 en 17) een onrechtstreekse beweegreden
    om de MNM te starten.

_Verdere info is te vinden in het
**[basisrapport](http://dx.doi.org/10.21436/inbor.13086011)** van de MNM
en diens
**[beleidssamenvatting](https://drive.google.com/uc?export=download&id=0B-DYcTNHFnIXaU1LNWFFLUNUWmc)**._
