# Bijlage: enkele belangrijke termen  {#app:termen}

Wijzigingen aan milieufactoren kunnen van natuurlijke of antropogene oorsprong zijn. Is deze van antropogene oorsprong, dan spreken we van een **milieudruk**. Een milieudruk is vaak onmiddellijk gevolg van een maatschappelijk proces (zoals landbouw, verkeer, industrie, ...) en oefent een (vaak onrechtstreekse) negatieve invloed uit op natuur. Voorbeelden zijn verzuring via de lucht, eutrofiëring via het grondwater, toename overstromingsduur of -frequentie, ...

Een **milieuvariabele** is een variabele waarvoor eenduidig vastligt hoe ze gemeten, berekend en geanalyseerd wordt, en met welk tijdsinterval en subcompartiment ze overeenkomt. Ze worden in de MNM steeds gemeten ter hoogte van standplaatsen van zg. *types*: habitattypes of regionaal belangrijke biotopen (RBB's). Er kan onderscheid worden gemaakt tussen de *primaire milieuvariabelen* en de *aanvullende milieuvariabelen*:

- het eerste type beantwoordt meest rechtstreeks de vragen van de MNM (het betreft per milieudruk één of eventueel enkele milieuvariabelen). Het is over dit type dat in eerste instantie wordt gerapporteerd;
- het tweede type heeft een ondersteunende functie en is voor het beleid van nut bij de verdere interpretatie van toestand en trend van de primaire milieuvariabele.

*In dit rapport bedoelen we met de term 'milieuvariabele' steeds 'primaire milieuvariabele', tenzij anders vermeld.* Het is bovendien zo dat we veronderstellen dat het om de *analysevariabele* of *doelvariabele* gaat, d.w.z. de variabele waarover we uitspraken doen met een meetnet. Een milieuvariabele kan in die zin van enkelvoudige meetvariabelen zijn afgeleid, of reeds een aggregatie zijn van meerdere metingen in ruimte of tijd.

Een **meetnet** beoogt vragen te beantwoorden over **één milieudruk in één milieucompartiment**, aan de hand van één gerelateerde primaire milieuvariabele (soms enkele).  Elk **milieucompartiment** is een ruimtelijke eenheid in de standplaats die een apart deel van het standplaatsmilieu vertegenwoordigt. We onderscheiden volgende milieucompartimenten: atmosfeer, bodem, grondwater, inundatiewater, oppervlaktewater en waterbodem.

Op basis van de actuele milieuproblematiek voor de types zijn 7 meetnetten aangeduid als **hoofdmeetnetten**. Zij zullen een specifiek ontwerp krijgen (aantal, ligging, tijdstip van metingen), aangepast aan de beoogde betrouwbaarheid, precisie, kost en haalbaarheid. De **secundaire meetnetten** zijn de overige meetnetten. Zij hebben een typisch kleinere doelpopulatie, in termen van het aantal betrokken types. Ze worden niet in detail ontworpen, maar de monitoring wordt evenzeer beoogd (incl. verwerking en uitspraken), dit zoveel mogelijk op locaties / tijdstippen van de hoofdmeetnetten. De secundaire meetnetten vertegenwoordigen samen nog een heel groot aandeel van de gezamenlijke milieuproblematiek.

De meetnetten geven het niveau weer waarop data-analysen en uitspraken zullen gebeuren. Meetnetten uit eenzelfde milieucompartiment kunnen we voor de praktische organisatie van het terreinwerk groeperen tot  **compartimentmeetnetten**. Vermits er geen hoofdmeetnetten voorkomen in het milieucompartiment _waterbodem_, nemen we de waterbodemmeetnetten op in het compartimentmeetnet voor de *waterkolom*. We onderscheiden **vijf compartimentmeetnetten** en **zeven hoofdmeetnetten**:

- **grondwatermeetnet**, met de hoofdmeetnetten voor **verdroging via grondwater (5.1)** en **eutrofiëring via grondwater (3.3)**;
- **bodemmeetnet**, met het hoofdmeetnet voor **eutrofiëring via de bodem (3.2)**;
- **oppervlaktewatermeetnet**, met het hoofdmeetnet voor **eutrofiëring via het oppervlaktewater (3.4)**;
- **inundatiemeetnet** (compartiment *inundatiewater*), met het hoofdmeetnet voor **eutrofiëring via het oppervlaktewater (3.4)**;
- **atmosferisch meetnet**, met de hoofdmeetnetten voor **eutrofiëring via de lucht (3.1)** en **verzuring via de lucht (4.1)**.

