*Disclaimer:*
This is a draft for a communication document.
As of this moment, the draft is created by a single author, Falk Mielke.
The draft is not representative of the general opinion or decisions within Vlaamse Overheid, until it has been reviewed and broad consensus found within a sufficiently large group of stakeholders. 
Please also excuse that the initial author is non-native in Dutch, and expect and apologize my absolutely embarassing orthography and grammar mistakes.


It is a mere draft to initiate a balanced thought assembly and internal discussion.

----

# Abstract

Dit memorandum is een samenvatting van een complexe, vorafgaandeanalyse van de ruimtelijke koppeling van grontwatermonitorings-installaties.
Het probeerd op een algemeen verstaanbare maar technisch gefundeerde manier onze redenering bij de volgende vraag uit te leggen:

:::{.callout-question}
Onder welke omstandigheden dient een bestaande WATINA-installatie[^1] hergebruikt te worden voor de doelstellingen van de Meetnetten Natuurlijk Milieu (MNM).
:::

[^1]: WATINA is een databank die gebruikt word om alle gegevens rond grondwater te kapteren: waterstanden enerzijds, maar ook chemische metingen. Deze worden in de regel opgemeten met piëzometers in peilbuizen. WATINA omvat over heel diverse projecten heen historische metingen sinds de jaren 1980, maar ook recente, hoogfrequente metingen van waterstanden.


# Situatie - Statistische Onderbouw

## Doelstelling van de MNM

Het primaire doel van het eerste meetnet van de MNM is de kwantificering van de milieudruk *"eutrofiëring via het grondwater"* (kort: *grondwatermeetnet*).
Representatief ligt de focus op het chemische element stikstof; een uiterst relevante vraagstelling voor het Vlaamse beleid rond de "Programmatische Aanpak Stikstof" ([PAS](https://nl.wikipedia.org/wiki/Programmatorische_Aanpak_Stikstof)).
Meer specifiek is de wettelijke taak van het INBO-project MNM een beschrijving van de *toestand en trend* van de stikstofinvloed op kwetsbare habitaten via verschillende milieucompartimenten[^2].
Het eerste milieucompartiment waarop in het kader van de MNM een metnet uitgerold wordt is het compartiment grondwater.
Het is de plan om in de nabije toekomst ook meetnetten voor andere compartimenten op te starten, en ook voor andere milieudrukken (bv. *vertroging via het grondwater*) zijn er concrete plannen.

[^2] Milieucompartimenten zijn: atmosfeer, bodem, grondwater, inundatiewater, waterkolom, waterbodem.


## Ruimtelijk Gebalanceerde Steekproef

Het feit dat toestand en trend over heel Vlaanderen moeten worden vastgesteld eist een pragmatische statistische aanpak.
Eerst en vooral moet de steekproef **ruimtelijk gebalanceerd** zijn.
Dit betekent dat de meetpunten gelijkmatig over de hele doeloppervlak verdeeld zijn ([Natura 2000](https://www.ecopedia.be/encyclopedie/natura-2000) gebieden in Vlaanderen, kort "N2KHab").

Er moet wel rekening gehouden worden met de specificiteit en onevenmatige verspreiding van verschillende [habitattypes](https://www.ecopedia.be/europees-beschermde-natuur/habitattypes).
Daarom stratificeren we onze steekproef na habitattypes.


Er zijn in theorie verschillende manieren om een ruimtelijk gebalanceerde steekproef te genereren.
Wij kozen er voor het zogenoemde **Generalized Random-Tesselation Stratified Design**, of **GRTS** [@Stevens2004] in het kader van Design-Based Inference [*cf.* @Brus2021, @Dumelle2022].


De voordelen van de GRTS metode zijn als volgd:

- goed gebalanceerde ruimtelijke verspreiding
- daardoor de mogelijkheid om opp een efficiente, voorwaardeloze manier inschattingen te berekenen
- datarijen zijn uitrekbaar zonder verlies van de serie
- koppeling en synergiën met bestaande (bv. biotische) meetnetten (verklarende charakter)

Een belangrijke component hierbij is de **voorwardeloze** (engl. *unbiased*) vaststelling van toestand en trend.
Dit is een fundamenteel verschil van modelgebaseerde inferentie, die kennis van zoveel mogelijke parameters en *constraints* eist.
Waarom dit een belangrijke basisaanname en voorwaarde voor een betrouwbare meetnet is gaan we in het volgende verder toelichten.


## Bias

De GRTS-methode zorgt voor een ruimtelijk gebalanceerde verdeling van steekproefeenheden over heel de doelpopulatie (N2kHab / Vlaanderen).
De oorspronkelijke trekkingen zijn [onvooringenomen, vrij van *bias*](https://nl.wikipedia.org/wiki/Bias_(fout)).


Maar het gebrek aan bias op populatieniveau kan enkel gegarandeerd worden als de toevallige plaatsing ook in de lokale omgeving van elke steekproeflocatie toegepast wordt.


Een voorbeeld om dit te verduidelijken:
Stel dat het doel is om een grondwatervariabele over alle grasvelden van Vlaanderen op te meten, en dat een ruimtelijk gebalanceerde steekproeftrekking toevallige punten op alle grasvelden van Vlaanderen kiest.
Stel nu dat voor de één of andere reden meetpunten enkel aan de rand van de doelgebieden geïnstalleerd kunnen worden.
Deze systematische afwijking van de doelpopulatie **zorgt voor een vertekening**.
Per gevolg zal de uitkomst van alle meetinspanningen informatie leveren over de randen van de doelgebieden, maar niet over de doelgebieden zelf.


## Intransparante Bias

De bias boven is relatief transparant en duidelijk; met voldoende gedetailleerde modelaannames zou mogelijk een transfer van de vertekende data naar de eigenlijk gewenste doelvariabelen mogelijk zijn.
Maar het hypotetische voorbeeld is een speciaal geval: de bias is gekend.
De veronderstelling is ook dat er voldoende kennis voor transfer en recuperatie van de data beschikbaar is.


Geen enkele van deze reparatieve veronderstellingen is voor een algemeen meetnet over heel Vlaanderen realistisch.

:::{.callout-note}
We constateren integendeel dat elke afwijking van de gerandomiseerde steekproeftrekking een onbekend bias veroorzaakt.

**De enkele manier om een bias te voorkomen is volledige randomisatie.**
:::


Een relevant praktisch voorbeeld: 
*Als we voor de grondwatermeetnet van MNM bestaande WATINA-meetpunten overnemen, dan erven de steekproefeenheden de assumties en specifieke installatievoorwaarden van deze meetpunten.*

Dit veroorzaakt een intransparente bias.

- Was er een systematische keuze van de lokale installatieomgeving? (bv. aan de rand van percelen)
- Waren er voor studies in het verleden voorwaarden aan het installatiemateriaal? (bv. chemisch inerte peilbuizenmateriaal)
- Is de peilbuizendiepte relevant voor de MNM-vraagstellingen? (grondwaterafhankelijke vegetatie)
- ...


Door WATINA-meetpunten te hergebruiken loopen de MNM gevaar om deze onzichtbare bias mee op te nemen.
Het cruciale probleem hierbij is dat de *bias* retrospektief niet of enkel met prohibitieve inspanningen meetbaar is.


De enkele effectieve methodische aanpak van *bias* is volledige randomisatie, per design.
*Bias* en daarmee de retrospectieve aanvechtbaarheid van de MNM moeten systematisch voorkomen worden.


## Praktische Beperkingen

Dit betekent uiteraard niet dat de gekozen steekproeflocaties volledig in steen gebijtelt zijn.
Uiteraard zijn er praktische overwegingen in de limieten. 
Bijvoorbeeld de inzet van middelen en mogelijke besparing door hergebruik.


:::{.callout-note}
De MNM streven erna om kostenefficient te werken om effektieve meetnetten kostenefficient te implementeren.

Maar ook de fatale aanvechtbaarheid en uitval van een hele meetnet door intransparente bias is een kostenrisico die we moeten voorkomen.
:::


De enige voorwaarde waaronder we een afwijking kunnen accepteren is als we onder redelijke overweging verwachten **dat voor twee nabije punten geen verschil in de doelvariabelen te verwachten is**, m.a.w. als we een identieke ruil van punten toepassen.
De vervangpunt staat representatief voor de doelpunt.


Enkel in gevallen waar we *de facto* en met een gegeven meetnauwkeurigheid geen verschil tussen een bestaande peilbuis-installatie en ons ruwe doelpunt verwachten is een hergebruik gerechtvaardigt.

Deze aanpak houdt rekening met de statistische voorwaarden van de meetnetten, maar maakt het ook mogelijk om de inzet van middelen en de verstoring van kwetsbare natuur redelijk te beperken.


--- 

Per gevolg verschuift onze vraagstelling, van de absolute vraag na het hergebruik van een concrete installatie, tot een vraag na de ruimtelijke variatie van onze doelvariabelen.

**Vanaf welke afstand zijn de verwachte uitkomsten te verschillend om een hergebruik te rechtvaardigen?**


# Ruimtelijke Koppeling

## Ruimtelijke Variabiliteit

- parameters: soilclass, filter depth difference, habitattype en vegetatie ...

## Data: Grondwaterchemie en Waterstanden

- limits of groundwater chemistry

## Methodologie

- referentie naar variogrammen


# Resultaten

- variogrammen voor waterchemie (instabiel)
- variogrammen voor waterstanden (benadering)


# Discussie


# TODO References

-> naar zotero/csl

*Brus D.J. (2021)*
Statistical approaches for spatial sample survey: Persistent misconceptions and new developments
European Journal of Soil Science 72 (2): 686–703
https://doi.org/10.1111/ejss.12988

*Stevens D.L. & Olsen A.R. (2004)*
Spatially Balanced Sampling of Natural Resources
Journal of the American Statistical Association 99 (465): 262–278
https://doi.org/10.1198/016214504000000250

*Dumelle, M.*, Higham, M., Ver Hoef, J. M., Olsen, A. R., & Madsen, L. (*2022*).
A comparison of design-based and model-based approaches for finite population spatial sampling and inference.
Methods in Ecology and Evolution, 13, 2018–2029.
https://doi.org/10.1111/2041-210X.13919
