---
title: "Een ruwe inschatting van steekproefgrootte voor toestandsbepaling in het grondwatermeetnet"
author: "Floris Vanderhaeghe"
date: "november 2018"
link-citations: true
linkcolor: link.colour
citecolor: link.colour
urlcolor: link.colour
geometry: margin=1in
mainfont: "Calibri"
fontsize: 11pt
documentclass: "article"
csl: ../inbo.csl
bibliography: ../RefsMNE_design.bib
output:
  html_document:
    keep_md: TRUE
    number_sections: yes
    fig_caption: yes
    toc: TRUE
    toc_float:
      collapsed: FALSE
      smooth_scroll: FALSE
    includes:
        in_header: ../header.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Ten geleide

Dit document loopt voorop op een meer gedegen berekening van de steekproefgrootte via steekproefsimulaties met modellen.

# Instelwaarden voor de toestandsbepaling

Zie verder [deze googlesheet](https://docs.google.com/spreadsheets/d/1IMlLh9EPPRLLoDNWkDzbVJU2cVvst7C8NyJRM2NvujM/edit#gid=229047732).

```{r}

```



# Literatuurreferenties {-}

