# (PART) Vraagstelling van het natuurbeleid voor de Meetnetten Natuurlijk Milieu {-}

<!-- ## Welke milieu-informatie hebben het Vlaamse en het Europese natuurbeleid nodig doorheen de tijd?  {#behoeften} - dit omvatte oorspronkelijk 050 + 060 -->

@westra:2011monitoring1 hebben de informatiebehoeften beschreven van het Vlaamse en het Europese natuurbeleid ten aanzien van de biotische habitatkwaliteit (toestand en trend van vegetatiekenmerken). Bepaalde elementen daarvan komen aangepast in dit deel terug, maar enkel in functie van het natuurlijk milieu.

Van het natuurbeleid gaat een informatiebehoefte uit ten aanzien van het natuurlijk milieu. Deze gaat veel ruimer dan de kaders die bepalend zijn voor de MNM (hoofdstuk \@ref(beweegredenen)). De MNM richten zich immers op het actieve, [vegetatiegerichte](#vegetatiegericht) natuurbeleid op het Vlaamse niveau -- zie [eerder](#gewestelijk). De MNM kunnen evenwel een **ondersteunende rol** spelen voor verschillende van deze andere natuurbeleidskaders, zoals: Europese vragen, lokale of gebiedsvragen, vergunningenbeleid, soortenvragen en vragen omtrent niet-Europees beschermde natuur (Figuur \@ref(fig:BehoeftedomeinenMNM)). Bovendien hangen aan die vragen ook wettelijke verplichtingen vast. Daarom wordt in hoofdstuk \@ref(verantwoording) toelichting gegeven bij de ruimere set aan informatiebehoeften ten aanzien van het natuurlijk milieu. De feitelijke vragen die aan deze verantwoordingen vasthangen, worden opgesomd in hoofdstuk \@ref(vragen).

In het licht van de beweegredenen (hoofdstuk \@ref(beweegredenen))
is bijkomend een *aanduiding* gebeurd van *die* vragen die we met de **MNM** in beschouwing nemen (paragraaf \@ref(vraagselectie)). Deze **vraagselectie** zal in hoofdstuk \@ref(kernvragen) verder worden gesynthetiseerd tot *kernvragen* voor de MNM, door afbakening en integratie. Daarop aansluitend geeft hoofdstuk \@ref(gebruik) een overzicht van de verwachte toepassing door eindgebruikers en van de rapportagenoden, en leidt hoofdstuk \@ref(opstap-ontwerp) elementen af die bepalend of noodzakelijk zijn voor het verdere ontwerp.














<!-- ### Verantwoording van de informatienoden van het natuurbeleid t.a.v. het natuurlijk milieu {#verantwoording} -- betreft de gehele titel van dit hoofdstuk; bovenaan gezet -->



# Toelichting bij de specifieke milieu-informatiebehoeften van het natuurbeleid {#verantwoording}


In paragraaf \@ref(toelichting) lichten we de specifieke informatiebehoeften toe die betrekking hebben op de _**ruimere set aan vragen ten aanzien van het natuurlijk milieu**_, inclusief deze waar de MNM zich op zullen richten.
Het is overigens op basis van deze analyse dat een deel van de beweegredenen (hoofdstuk \@ref(beweegredenen)) voor de MNM naar boven kwamen.
Een aantal elementen keren dus terug, maar geregeld in een bredere zin (bv. ook soorten, ook lokaal, enz.).

In paragraaf \@ref(prioriteringskwesties) leggen we vervolgens voor de gewestelijke schaal uit hoe de behoefte verschilt tussen verschillende types van milieu-informatie.



## De specifieke milieu-informatiebehoeften van het natuurbeleid {#toelichting}

```{block2, type = "exampleblock"}
**Om zeker te onthouden**

- Op basis van regelgeving, beleidsdocumenten en overleg zijn voor het natuurbeleid de verschillende informatiebehoeften onderzocht t.a.v. het natuurlijk milieu. Dit is gebeurd voor de gewestelijke en voor de gebieds- en lokale schaal.
- Zowel de Vlaamse als de Europese milieu-informatiebehoeften lichten we toe in bijlage \@ref(app:verantwoording).
- We hebben onderscheid gemaakt tussen lange-termijnbehoeften (recurrent en systematisch monitoren over decennia) en korte-termijnbehoeften (gevalsspecifieke evaluaties en opvolging).
- Milieu-informatie op gewestelijke schaal blijft gedurende lange termijn nodig (monitoringsbehoefte). Ze ondersteunt de planning, onderbouwing, evaluatie en bijsturing van zowel het actieve natuurbeleid (beweegreden MNM) als het passieve natuurbeleid (preventieve regelgeving en controle) op Vlaams niveau.
- Milieu-informatie op gebieds- en lokale schaal:
    - blijft nodig gedurende lange termijn voor het actieve natuurbeleid;
    - is gedurende korte termijn nodig voor specifieke gevallen in het actieve en passieve natuurbeleid.

```

Het instandhoudingsbeleid op Vlaams en Europees niveau [^Vl-Eur] en het Vlaamse natuurbehoudsbeleid werden aan een analyse onderworpen van de behoefte aan milieu-informatie. Er werd daarbij gesteund op drie gradaties van bronnen uit het natuurbeleid:

- **regelgeving**: argumenteert en geeft aan (of impliceert) wat minimaal nodig is aan milieu-informatie;
- **beleidsdocumenten**: argumenteren en geven aan welke doelstellingen actueel worden gehanteerd door het beleid, met welke aanpak deze concreet dienen te worden bereikt, en bijgevolg wat daar aan milieu-informatie voor nodig is;
- **overleg**: hieruit komen specifieke vragen naar boven ten aanzien van gewenste milieu-informatie. Ten dele kan dit samenhangen met meer persoonlijke zienswijzen.

Het resultaat van deze analyse was zowel de beleidsverantwoording van de informatievragen, als de informatievragen zelf. In deze paragraaf komt de verantwoording (toelichting) aan bod. In hoofdstuk \@ref(vragen) komen de vragen zelf aan bod.

**In bijlage \@ref(app:verantwoording) zijn de concrete toelichtingen voor elke milieu-informatiebehoefte opgelijst**^[*De geraadpleegde bronnen voor het Vlaamse natuurbeleid zijn*: 
@paelinckx:2009gewestelijke;
@vlaams:2014nota;
@vlaams:2014implementatiepad;
@agentschap_voor_natuur_en_bos:2014implementatienota;
@anb:2013pb4_1;
@anb:2014pb3_1;
@anb:2013pb5;
@anb:2013pb6;
@anb:2013pb8_4;
@schauvliege:2015omzendbrief;
@agentschap_voor_natuur_en_bos:2016voorontwerp;
Natuurdecreet;
Besluit Natuurbehoud;
Procedurebesluit IHD;
G-IHD-besluit;
S-IHD-besluiten;
Instandhoudingsbesluit.\
*De geraadpleegde bronnen voor het Europese natuurbeleid zijn*: 
@evans:2011assessment;
@whitfield:2011critical;
@etcbd:2016reference;
@dgenv_eea:2011reference;
@european_commission:2014establishing;
@europese_commissie:2015stand;
@european_environment_agency:2015state;
Habitatrichtlijn;
Uitvoeringsbesluit van 11 juli 2011.],
geordend volgens de beleidsvoerder (Vlaanderen / Europa), gewestelijke versus lokale behoeften, en daarbinnen volgens de termijn van de informatievragen, het geografisch toepassingsgebied en de doelpopulatie (over welke objecten zijn uitspraken nodig?). Deze informatiebehoeften omvatten zowel actief als passief beleid. De doelpopulatie (objecten waarover uitspraken nodig zijn) kan ook soorten of niet-Europees beschermde natuur omvatten. In de bijlage worden voor elke informatiebehoefte tevens de geraadpleegde bronnen opgegeven, i.h.b. de artikels uit de regelgeving.

Een **lange-termijninformatiebehoefte** betekent dat er behoefte is aan het recurrent en systematisch verzamelen en verwerken van informatie over lange termijn: typisch decennia in de context van het natuurbeleid. Dit is ook waar *meetnetten en monitoring* zich per definitie op richten [zie @wouters:2008ontwerp1; @wouters:2008ontwerp2]. Daarentegen heeft een **korte-termijninformatiebehoefte** te maken met gevalsspecifieke evaluaties (ad hoc), bv. voor vergunningverlening.


In de onderstaande tekst worden alleen de grotere patronen uit de specifieke informatiebehoeften gelicht en **samengevat**. Om de specifieke informatiebehoeften ten volle te begrijpen, is het dan ook essentieel om de **tabellen in bijlage \@ref(app:verantwoording)** door te nemen. Omdat er op syntheseniveau gelijkenis is tussen de Vlaamse en de Europese informatiebehoefte, maken we hier het onderscheid niet. Dit is wel het geval in bijlage \@ref(app:verantwoording).



### De informatiebehoeften op gewestelijke schaal {#gewest}


Over lange termijn hebben het Vlaamse en Europese natuurbeleid nood aan gewestelijke resp. regionale milieu-informatie (zie bijlage \@ref(app:verantwoording)), omdat deze informatie, zowel van *habitats* als van *soorten*, nodig is:

- voor *planning en onderbouwing van het actieve beleid* (cf. beweegredenen MNM), dus voor het aspect 'milieu' in de G-IHD en de taakstellingen per zesjarige cyclus (planning van herstel- en ontwikkelbeleid). Omdat de meeste inspanningen gebeuren binnen de Habitatrichtlijngebieden, bestaat een grotere informatienood voor het netwerk van Habitatrichtlijngebieden als geheel;
- voor *planning en onderbouwing van het passieve beleid*, dus voor het opstellen van preventieve regelgeving en als referentiekader bij het nemen van beslissingen over vergunningen;
- voor *evaluatie en bijsturing van het actieve* (cf. beweegredenen MNM) *en passieve beleid*, dus voor de voortgangsbewaking ^[Zie eerder [kader](#voortgang) voor uitleg bij het begrip 'voortgangsbewaking'.] van de realisatie van de beleidsdoelstellingen (G-IHD in 2050 en doelstellingen per zesjarige cyclus). Het betreft dan de milieu-informatiebehoefte, zowel voor de toetsing van de toestand en trend aan de doelstellingen (want milieu is onderdeel van de doelstellingen), als voor de verklaring waarom doelstellingen niet (volledig) worden gehaald (diagnose van oorzaken). De zesjaarlijkse evaluatie is wegens de Habitatrichtlijn verplicht voor alle lidstaten (rapportageverplichting).

De rol van milieu-informatie in het actieve natuurbeleid op gewestelijk niveau heeft te maken met de rol t.a.v. de regionale staat van instandhouding (SVI), die inherent is aan de G-IHD en de doelstellingen per zesjarige cyclus. Behalve een verklarende rol voor de SVI, speelt het natuurlijk milieu ook een rol in de SVI-bepaling zelf. Dat laatste werd uitgediept in paragraaf \@ref(SVI).

Tenminste voor de planning en onderbouwing (actief en passief) volgt de behoefte aan milieu-informatie ook duidelijk uit de doelstellingen van het *natuurbehoudsbeleid* in het Natuurdecreet (dus ook voor natuur die geen Europese bescherming geniet).

Er zijn op het gewestelijke niveau geen informatiebehoeften die slechts over een korte termijn (gevalsspecifiek) gelden.

In het Natura 2000 Programma kunnen ook **programmatische aanpakken** worden ingebed (zie [inleidend kader](#natuurintro)). Het zijn integrale programma's die gelden op gewestniveau, met oog op het reduceren van de omvang en effecten van een specifieke milieudruk. In 2014 werd de Programmatische Aanpak Stikstof (PAS) opgestart. Een karakterisering van de PAS, met daarbij de milieu-informatiebehoeften, wordt gegeven in bijlage \@ref(app:PAS).





### De informatiebehoeften op gebieds- en lokale schaal {#lokaal}

Over **lange termijn** hebben het Vlaamse en Europese natuurbeleid nood aan **gebieds- en lokale** milieu-informatie (zie bijlage \@ref(app:verantwoording)), omdat deze informatie, zowel van *habitats* als van *soorten*, nodig is:

- om het *actieve beleid te plannen en te onderbouwen*: de S-IHD en de managementplannen Natura 2000 zijn voor een belangrijk deel gebaseerd op informatie over het natuurlijk milieu in SBZ's, om te kunnen bepalen welke milieuknelpunten aangepakt moeten worden in een gebied;
- om het *actieve beleid te evalueren en bij te sturen*: de realisatie van de abiotische doelstellingen van de managementplannen Natura 2000 en de S-IHD moet worden geëvalueerd op het niveau van elke SBZ. Analoog dient de realisatie van abiotische doelstellingen op het niveau van natuurterreinen te worden opgevolgd. Op die manier is het mogelijk om tijdig in te grijpen en aangepaste maatregelen te nemen. De abiotische opvolging op het niveau van SBZ's wordt ook gevraagd (maar niet geëist) door Europa, zowel algemeen voor de SBZ als specifiek per habitat en per soort binnen de SBZ. Dit staat in het kader van de evaluatie van de effectiviteit van het Europese Natura 2000 netwerk.

Dat deze informatiebehoefte varieert tussen gebieden, en hoe dit zich verhoudt tot het werkdomein van de MNM, kwam reeds aan bod in paragraaf \@ref(schalen). Tevens werd daar in een [kader](#SDFEuropa) uitleg gegeven bij de gebiedsschaal in de Europese regelgeving.

Over **korte termijn** (dus los van monitoring) hebben het Vlaamse en Europese natuurbeleid nood aan **lokale** milieu-informatie (zie bijlage \@ref(app:verantwoording)), omdat deze informatie, zowel van *habitats* als van *soorten*, nodig is:

- om het *actieve beleid te plannen en te onderbouwen*: om abiotische knelpunten op te lossen, dient voor het *instandhoudingsbeleid* eerst voldoende lokale detailinformatie te worden verzameld over het natuurlijk milieu. Pas dan kunnen voldoende trefzekere instandhoudingsmaatregelen, meer bepaald de zg. 'acties ter verbetering van milieucondities'^[Dit is de abiotische tegenhanger van de acties rond beheer en inrichting;
zie [inleidend kader](#natuurintro).],
worden ontworpen en uitgevoerd. Ook de afbakening van de 'actiegebieden' waar deze acties dienen te gebeuren, benodigt abiotische informatie. Ook binnen het *natuurbehoudsbeleid* (niet-Europees beschermde natuur) is kennis over milieuknelpunten nodig om maatregelen te kunnen concipiëren en in plannen op te nemen;
- om het *passieve beleid te plannen en te onderbouwen*: wanneer een plan, programma of activiteit wordt aangemeld, is informatie over het natuurlijk milieu nodig om de juiste (vergunnings)beslissingen te kunnen nemen ter vrijwaring van de milieukwaliteit. Dit geldt zowel binnen het *instandhoudingsbeleid* als het *natuurbehoudsbeleid*;
- om het *passieve beleid te evalueren en bij te sturen*: gevalsspecifieke opvolging van het natuurlijk milieu^[Hiervoor wordt in de praktische wegwijzers ook de term 'monitoring' gebruikt. In deze gevalsspecifieke context gaat het dikwijls over veel kortere termijnen dan de 'lange termijn' waarvoor in dit rapport de term 'monitoring' wordt aangewend (typisch decennia). Het doel van een gevalsspecifieke opvolging in de context van vergunning is vooral controle.] kan worden voorzien, ter controle na vergunningverlening. Voor de verschillende milieudrukken worden hiervoor in de respectievelijke praktische wegwijzers aparte instructies voor de vergunningaanvragers voorzien.




## Niet alle milieu-informatie is even belangrijk: prioriteringen voor de gewestelijke schaal (MNM) {#prioriteringskwesties}

```{block2, type = "exampleblock"}
**Om zeker te onthouden**

- We weten nu *waarvoor* informatie over het natuurlijk milieu belangrijk is in het natuurbeleid op gewestschaal. Maar niet elke soort milieu-informatie is daarom even relevant!
- Er zullen dus keuzes gemaakt worden voor de MNM (Figuur \@ref(fig:prioritering)): (1) welke milieudrukken? - (2) welke (groepen van) habitat(sub)types en/of RBB's? - (3) welke standplaatsfactoren? Daarbij zal selectie (2) verschillend zijn per milieudruk (1), en zal selectie (3) verschillend zijn per milieudruk én  habitattype/RBB in kwestie.
- De samenhang tussen deze elementen wordt opgenomen in het zg. *conceptueel systeemschema van de standplaats*. Het bundelt de wetenschappelijke kennis terzake onder de vorm van schema’s en een databank.
- De keuzes in (1), (2) en (3) zullen telkens worden gebaseerd op een prioritering: een rangschikking van de verschillende mogelijke toestanden, volgens het belang. Dat gebeurt volgens criteria die in deze paragraaf worden opgesomd. Op die manier wordt voor (1), (2) en (3) een *afwegingskader* opgesteld om latere keuzes te kunnen onderbouwen.
- Wat betreft standplaatsfactoren (3), wordt ervan uitgegaan dat op dit moment de behoefte aan informatie over P-proxies (sterker gecorreleerd met de milieudruk) groter is dan deze over I-proxies (sterker gecorreleerd met de levensgemeenschap).
- De afwegingskaders en het conceptueel systeemschema worden los van het voorliggend rapport ontworpen, en kunnen verder verbeteren volgens voortschrijdend inzicht.

```

In de toelichting bij de milieu-informatiebehoefte op gewestelijke schaal (paragraaf \@ref(gewest)) lieten we nog in het midden welk *soort milieu-informatie* dan wel het meest relevant is, en voor *welke habitattypes* deze informatie dan relevant is. **Prioriteringen** daarin worden in deze paragraaf behandeld. Met prioriteren bedoelen we: rangschikken volgens belang.

In Figuur \@ref(fig:prioritering) is schematisch het verband weergegeven tussen de te prioriteren elementen voor de MNM. Er is voornamelijk nood aan prioritering van milieudrukken, habitat(sub)types / regionaal belangrijke biotopen en standplaatsfactoren. We bespreken deze elementen achtereenvolgens in deze paragraaf.


![(\#fig:prioritering)_Schema van het verband tussen de elementen waarvoor nadere keuzes gemaakt moeten worden in de MNM. De elementen zijn toegewezen aan een positie in de milieuverstoringsketen (P, S of I; cf. paragraaf \@ref(dpsir)). Elk element (kadertje) vertegenwoordigt een reeks mogelijke waarden, in enkele gevallen symbolisch voorgesteld met een hoofdletter. De roze lijnen vertegenwoordigen de koppelingen tussen de respectievelijke waarden van de verschillende elementen, aangezien deze onderling samenhangen. De landschapspositie hangt samen met het habitat(sub)type of regionaal belangrijk biotoop (RBB), en betreft de positie op de vochtgradiënt (van droog tot submers). De standplaats van een habitat(sub)type of RBB komt overeen met de S-positie in de milieuverstoringsketen (State). Ze omvat meerdere milieucompartimenten, gekenmerkt door standplaatsfactoren die aan de hand van milieuvariabelen gemeten kunnen worden (paragraaf \@ref(dpsir)). Een milieudruk werkt in op welbepaalde landschapsposities, milieucompartimenten en standplaatsfactoren. De twee roze elementen vertegenwoordigen de doelpopulatie en de meetnoden, die een afbakening vormen voor het ontwerp van de MNM. De voornaamste drie prioriteringsnoden (cf. tekst) zijn weergegeven met zwarte pijlen. De grijze pijlen vertegenwoordigen prioriteringen van andere elementen. De grijze pijlen vertrekken uit de zwarte omdat de 'grijze' prioriteringen sterk samenhangen met, of volgen uit, de prioritering volgens de zwarte pijlen._](../Figuren/Prioriteringsnoden.png){width=100%}



Een prioritering (rangschikking) samen met de criteria die de prioritering bepalen, noemen we een **afwegingskader**. Een afwegingskader laat onderbouwing van een selectie toe. Een prioritering en een afwegingskader houden op zich geen selectie in.

Welk soort *uitspraken* uiteindelijk nodig zijn (*met* die milieu-informatie), zal concreter worden in paragraaf \@ref(uitkomsten); dit is nadat de kernvragen zijn gedestilleerd (hoofdstuk \@ref(kernvragen)).


### Prioritering 1: milieudrukken {#prioritering1}

Een eerste prioriteringsnood betreft de **milieudrukken**. Welke standplaatsfactoren ook zouden worden gemonitord, deze monitoring zal voor het beleid vooral zinvol zijn als deze standplaatsfactoren in een ongunstige toestand kunnen komen (of zijn) als gevolg van milieudrukken^[
We merken wel op dat naast deze _primaire standplaatsfactoren_ ook _aanvullende standplaatsfactoren_ kunnen worden onderscheiden. Het eerste type vult meest rechtstreeks de informatiebehoefte in (het betreft per milieudruk één of eventueel enkele standplaatsfactoren). Het is over dit type dat in eerste instantie wordt gerapporteerd. Het tweede type heeft een ondersteunende functie en is voor het beleid van nut bij de verdere interpretatie van toestand en trend van de primaire standplaatsfactor.].
De aanwezigheid van milieudrukken is immers de grondreden waarom er een systematische, gewestelijke nood is aan milieu-informatie voor de ondersteuning van het natuurbeleid (zie paragraaf \@ref(beleidscyclus)).
Ook in de memorie van toelichting [@vlaamse_regering:2014memorie] bij het artikel 50undecies van het Natuurdecreet lezen we dat monitoringsnetwerken met name relevant zijn 'voor de belangrijkste milieueffectgroepen' (milieueffectgroepen behoren tot de lijst van milieudrukken).

Er opereren heel wat verschillende milieudrukken in Vlaanderen (zie Tabel \@ref(tab:milieudrukken)), sommige op lokale en andere op grotere ruimtelijke schaal. *Niet elke milieudruk is even belangrijk* voor elk habitat(sub)type (of ander vegetatietype). Ten eerste kan een habitat(sub)type voor bepaalde milieudrukken ongevoelig zijn. Dit kan voor lokale milieudrukken worden nagegaan met behulp van de effectenindicator [@wouters:2011beoordeling]. Voor milieudrukken die regionaal opereren, zoals klimaatverandering, ozonvervuiling e.d., kan literatuur worden geraadpleegd [bv. @demolder:2014hoofdstuk4;@van_der_aa:2015effecten]. Ten tweede zullen sommige milieudrukken niet van toepassing zijn voor een bepaald habitat(sub)type. Zo zijn milieudrukken die verlopen via oppervlaktewater veelal niet van toepassing bij habitat(sub)types van de droogste standplaatsen, die noooit met oppervlaktewater in contact komen. Ten derde stelt op het gewestelijke niveau niet elke milieudruk een even groot probleem voor een bepaald habitat(sub)type: sommige milieudrukken hebben maar een geringe invloed op het type en/of beïnvloeden maar een gering aandeel van de oppervlakte waar het type in Vlaanderen voorkomt. Al deze redenen leiden ertoe dat milieudrukken per type geprioriteerd kunnen worden. Omdat verschillende milieudrukken deels verschillende standplaatsfactoren beïnvloeden, is het mogelijk om te bepalen wat voor het beleid het relatieve belang is van verschillende standplaatsfactoren bij monitoring van een bepaald type.

Op basis van een beoordeling door INBO-experten was het mogelijk om een **afwegingskader** op te stellen van de  milieudrukken, overkoepelend en ook specifiek voor habitat(sub)types en regionaal belangrijke biotopen. Het afwegingskader voor de milieudrukken wordt verder opgesteld los van dit rapport.
    

    
### Prioritering 2: habitat(sub)types en regionaal belangrijke biotopen {#prioritering2}

Een tweede prioriteringsnood betreft de **habitat(sub)types en regionaal belangrijke biotopen**.
Er zijn voor het beleid diverse mogelijke redenen om aan een bepaald type de voorkeur te geven boven een ander:

- de mate waarin het type door *milieudrukken* wordt beïnvloed (zie afwegingskader milieudrukken
<!-- in bijlage \@ref(app:afwmilieudrukken) -->
). Dit komt voor habitattypes overeen met een prioritering van types volgens het ambitieniveau van de G-IHD inzake milieukwaliteit (want de G-IHD staan voor een gunstige staat van instandhouding)^[De monitoring zou eventueel voor elke milieudruk beperkt kunnen worden tot de méést gevoelige (beïnvloede) types, waarbij alleen *die* resultaten bepalend zijn voor het milieugerichte natuurbeleid (dat zich richt op alle gevoelige habitattypes). Uiteraard houdt een dergelijke benadering dan ook de keuze in om geen specifieke informatie te verzamelen voor Vlaamse uitspraken over de andere types.];
- de *oppervlakte* van het type in Vlaanderen: voorkeur zowel voor algemene types, indien sterk aan een milieudruk onderhevig (gezien betekenis voor het actieve beleid), als voor zeldzame types (behoudsbelang);
- de beschikbaarheid, of de intentie tot opmaak, van een *abiotisch toetsingskader* dat samenhangt met de gunstige staat (zie ook INBO-project [HabNorm](#HabNorm));
- het feit of een type functioneert als leefgebied van een *Europees beschermde soort*: zulke types hebben een groter belang;
- voor habitattypes, naast bovenstaande overwegingen:
    - de regionale *staat van instandhouding* in het Vlaamse Gewest: juist voor types in een ongunstige staat is er de grootste behoefte aan de diagnosefunctie van milieu-informatie;
    - het feit of een type wordt beschouwd in het meetnet *biotische habitatkwaliteit* (zie ook verder: paragraaf \@ref(koppeling));
    - het *belang van Vlaanderen* voor het type binnen Europa;
    - het Europees als *prioritair* aangeduid zijn;
- voor regionaal belangrijke biotopen (RBB's), naast bovenstaande overwegingen:
    - voor RBB's die geen leefgebied zijn van *Europees beschermde soorten* (zie hoger): prioriteit geven aan RBB’s die leefgebied zijn van *habitattypische soorten*.
        
   
Het afwegingskader voor de habitat(sub)types en regionaal belangrijke biotopen wordt los van dit rapport opgesteld.

Het is waarschijnlijk dat uitspraken dikwijls zullen gebeuren voor *groepen* van habitattypes / RBB's. Deze overweging komt aan bod in paragraaf \@ref(stratificatie).


### Prioritering 3: standplaatsfactoren {#proxykeuze}

Prioritering tussen standplaatsfactoren gebeurt in eerste instantie reeds in functie van de prioritering van milieudrukken (1) en types (2). Voor de standplaatsfactoren die beïnvloed worden door een milieudruk (1) en die relevant zijn voor een type (2), geldt een derde prioriteringsnood. De vraag is namelijk wat voor het Vlaamse en Europese natuurbeleid het relatieve belang is van de zogenaamde **P-proxies** en **I-proxies** (voor duiding, zie paragraaf \@ref(dpsir)). P-proxies zijn standplaatsfactoren die de milieudrukken het beste vertegenwoordigen (opwaarts in de milieuverstoringsketen). I-proxies vertegenwoordigen de kern van de abiotische functies die door een milieudruk worden beïnvloed; het zijn direct voor vegetatie bepalende standplaatsfactoren (opwaarts tot afwaarts in de milieuverstoringsketen).

Het onderscheid tussen P-proxies en I-proxies wordt samen met de koppelingen tussen de elementen van Figuur \@ref(fig:prioritering) opgenomen in het zg. *conceptueel systeemschema van de standplaats*.^[Het conceptueel systeemschema van de standplaats is een grafische voorstelling van de standplaatsfactoren die op een directe of indirecte wijze voor vegetatie relevant zijn, in de verschillende milieucompartimenten. Daarbij wordt gedifferentieerd tussen droge tot vochtige, natte en submerse standplaatsen (de landschapspositie). Bovenop deze voorstelling wordt aangeduid welke van deze standplaatsfactoren door de respectievelijke milieudrukken op een directe of indirecte wijze worden beïnvloed, samen met de richting van verandering (positief of negatief).]
Het bundelt de wetenschappelijke kennis terzake onder de vorm van schema's en een databank. Het systeemschema wordt los van het voorliggend rapport ontworpen, en vormt het **afwegingskader** voor de standplaatsfactoren. Het kan verder verbeteren volgens voortschrijdend inzicht.

In paragraaf \@ref(SVI) werd reeds aangegeven dat zowel P-proxies als I-proxies een rol spelen bij de *beoordeling* -- zie ook @fredshavn:2005species en @nielsen:2011monitoring.
De MNM hebben een rol in zowel *beoordeling* als *diagnose*, voor onderbouwing, planning, evaluatie en bijsturing van het natuurbeleid.^[Voor verdere duiding bij de begrippen 'diagnose' en 'beoordeling' verwijzen we naar het [eerdere kader](#tweerollen) in paragraaf \@ref(beleidscyclus).]
Op die basis kan reeds worden besloten dat de gewestelijke informatiebehoefte t.a.v. **milieudrukken op standplaatsen**, en dus P-proxies, **belangrijker** is dan deze t.a.v. abiotische functies, en dus I-proxies. Er kan tevens worden gesteld dat de informatiebehoefte t.a.v. milieudrukken op standplaatsen de **minimale** informatiebehoefte vertegenwoordigt. Dit heeft meerdere redenen:

- binnen de **diagnosefunctie** van de MNM (milieuknelpunten detecteren waar het Vlaamse beleid op moet focussen of bijsturen):
    - het actieve beleid aangaande het natuurlijk milieu heeft op gewestelijk niveau vooral informatie nodig voor het *brongerichte beleid*, en dus over milieudrukken (via P-proxies). Het is immers door te verhelpen aan milieudrukken, dat de milieukwaliteit op duurzame wijze in een gunstige toestand *kan* komen;
    - als gevolg van historische milieudrukken is het evenwel de verwachting dat de milieukwaliteit niet vanzelf in een gunstige toestand komt, na het oplossen van milieudrukken. Voorbeelden zijn een verzuurde en uitgeloogde toestand van infiltratiebodems of van geïsoleerde oppervlaktewateren als gevolg van historische verzuring, en gemineraliseerde (veraarde) veenbodems als gevolg van verdroging. Effectgericht beleid is daarom ook nodig, namelijk om ook de milieukwaliteit zelf aan te pakken. *Effectgericht beleid aangaande het natuurlijk milieu, op Vlaams niveau*, heeft echter vooral zin als eerst het brongerichte beleid de milieudrukken tot een niet-significant niveau heeft kunnen herleiden.
De opvolging van brongericht beleid gebeurt in elk geval via P-proxies, en niet zozeer via de I-proxies, tenminste inzoverre we alleen het effect van dat brongerichte beleid op de milieudruk zelf willen staven.
Het is dus momenteel nog moeilijk om in te schatten in hoeverre en wanneer informatie voor een effectgericht Vlaams beleid in de praktijk belangrijk zou worden (dus inzake abiotische functies: I-proxies);
    - een belangrijker deel van het effectgerichte beleid wordt onderbouwd en doorgevoerd op *gebieds- en lokaal niveau*, dan het geval is bij het brongerichte beleid;
    - het *passieve beleid* richt zich op menselijke actoren, en dus op driving forces. Ondersteuning van het passieve beleid met gewestelijke informatie kan dus het beste gebeuren met behulp van informatie over milieudrukken (via P-proxies);
    
- binnen de **beoordelingsfunctie** van de MNM (rol van abiotiek in de SVI):
    - de afwezigheid van significante milieudrukken - de precieze betekenis hiervan is later in te vullen - is een essentiële voorwaarde om de *gunstige SVI* te onderscheiden van de ongunstige (zie paragraaf \@ref(SVI)), gegeven dat de actuele specifieke structuren en functies (inclusief typische soorten) in goede conditie zijn;
    - voor het Vlaamse natuurbeleid is het kunnen maken van het onderscheid tussen FV en U1 (gunstig resp. matig ongunstig) de *belangrijkste rol van de MNM in de SVI-bepaling*. Immers is het Vlaamse instandhoudingsbeleid gericht op het behalen van een gunstige toestand. Het doen van uitspraken over milieudrukken is daarom een minimumvereiste voor de MNM;
    - hoewel Europa abiotische functies in de staat van instandhouding includeert (zij bevatten tenminste de I-proxies), worden lidstaten er in elk geval niet voor op de vingers getikt als ze uitspraken daarover louter op expertoordeel baseren, en/of impliciet op de biotische toestand proberen te baseren ^[In dat geval betreffen uitspraken veelal niet het niveau van een standplaatsfactor, maar een geheel aan met elkaar verwante standplaatsfactoren (bv. nutriënten, zuurtegraad), waardoor nadere duiding en kwantificering van de problematiek moeilijk blijft.]. Dit neemt niet weg dat het Vlaamse natuurbeleid wel een veel grotere nood heeft aan milieu-informatie, in vergelijking met diverse lidstaten met een beperktere milieuproblematiek (cf. bijlage \@ref(app:buitenland)). Dit komt door de aanwezigheid van diverse milieudrukken, die de beoogde toestand van habitattypes in belangrijke mate verhinderen of bedreigen in Vlaanderen.

De Vlaamse milieu-informatiebehoefte is dus het hoogst ten aanzien van milieudrukken en daar zal dan ook de nadruk op komen bij abiotische diagnose en beoordeling. Abiotische functies helemaal *uitsluiten* zal evenwel niet aan de orde zijn. Een aantal standplaatsfactoren die de inkomende milieudruk ter hoogte van de standplaats meten (P-proxies) behoren namelijk tegelijk tot de abiotische functies (direct vegetatie-beïnvloedend: I-proxies). Een voorbeeld zijn de nutriënten in oppervlaktewater in het geval van eutrofiëring via het oppervlaktewater.

- Met andere woorden wordt door **sommige P-proxies** sowieso een onderdeel afgedekt van de abiotische functies: het zijn **tegelijk I-proxies**.
- Het is dus wel *opportuun* om informatie over *deze* abiotische functies op een doordachte, herhaalbare en transparante manier te verwerken in de SVI-bepaling en ook te benutten in functie van effectgericht beleid op gewestelijk niveau.
- In het geval van de SVI-bepaling houdt dit dus ook een rol in van abiotiek bij het onderscheid tussen de matig en de zeer ongunstige toestand (U1/U2). Het gaat dan om de regionale toetsing aan 75% lokale situaties met gunstige structuren en functies. Dit impliceert in de mate van het mogelijke een (ruimtelijk beschouwd) *lokale integratie* van deelbeoordelingen alvorens de regionale uitspraak te doen voor dit criterium. Ook aangaande de eerste voorwaarde van de gunstige SVI, namelijk ‘specifieke structuren en functies (inclusief typische soorten) in goede conditie’, zal later dienen te worden bekeken of, en hoe, ook daarin informatie over abiotische functies wordt meegenomen en geëvalueerd.
- We voegen er ook aan toe dat *extra standplaatsfactoren* nuttig kunnen zijn voor de interpretatie van de relatie tussen de P-proxy en de milieudruk, en dat daarom de P-proxy zelf niet noodzakelijk volstaat voor een voldoende interpretatie.

Gezien de onzekerheden die er zijn over de haalbaarheid en kost van het *an sich* betrekken van I-proxies in de MNM, **gebeuren definitieve keuzes hierin beter per meetnet afzonderlijk**, op basis van concrete ontwerpimplicaties. Het is nu in elk geval duidelijk dat het monitoren van direct milieudrukgerelateerde standplaatsfactoren het minimum is. 






