# Vergelijking van scenario's

<!-- Dit hoofdstuk vereist dat verder gecreëerde scenario-summaries reeds op schijf beschikbaar zijn. -->
<!-- Als dit nog niet het geval is, compileer dit rapport eerst met parameter write_scenariofiles=TRUE. -->

```{r}
summaryfiles_present <- 
    list.files(file.path(datapath, "20_intermediate1")) %>% 
    grepl("summary", .) %>% 
    any
```


```{r results="asis", warning=FALSE, message=FALSE, eval=!params$write_scenariofiles && summaryfiles_present}
knit_child("_410_scenarios.Rmd", 
           quiet = TRUE,
           envir =  environment()) %>% 
  cat(sep = '\n')
```

```{r results="asis", eval=params$write_scenariofiles | !summaryfiles_present}
cat("_Dit hoofdstuk is niet ingevuld omdat hiervoor resultaatbestanden nodig zijn die pas in de huidige rapportcompilatie worden gecreëerd of overschreven (in de appendix), of gewoon omdat dergelijke bestanden ontbreken. Om de bestanden te creëren, compileer met parameter `write_scenariofiles = TRUE`. Compileer daarna het rapport een tweede keer, zonder deze bestanden te schrijven (de default-instelling voor parameter `write_scenariofiles`) om deze bestanden binnen dit hoofdstuk te gebruiken._")
```

