# Data-exploratie ter voorbereiding van de modellering {#app:eda}

<!-- - A Missing values?  -->
<!-- - B Outliers in Y / Outliers in X  -->
<!-- - C Collinearity X  -->
<!-- - D Relationships Y vs X  -->
<!-- - E Spatial/temporal aspects of sampling design (not relevant here)  -->
<!-- - F Interactions (is the quality of the data good enough to include them?)  -->
<!-- - G Zero inflation Y  -->
<!-- - H Are categorical covariates balanced? -->

<!-- functions that can be repeated for different data sets? Arguments like data, response, vars ? -->

```{r}
datasets <- 
    tibble(data = 
               list(gw51t, gw51a, gw33) %>% 
               set_names("GW_05.1_terr", 
                         "GW_05.1_aq", 
                         "GW_03.3"),
           response = list(vars(lg3_lcl, hg3_lcl),
                           vars(lg3_ost, hg3_ost),
                           vars(NO3, NH4, PO4)),
           var_cont = list(vars(hydroyear, x, y),
                           vars(hydroyear, x, y),
                           vars(date, year, month, x, y)),
           var_cat = list(vars(loc_code, 
                               sixyear, 
                               cluster_id, 
                               type, 
                               soilclass, 
                               ecoregion)) %>% rep(3)
    )
```


## Responsvariabelen

### Outliers

```{r warning=FALSE}
names(datasets$data) %>% 
    walk(function(dfname) {
        datasets %>% 
            filter(names(data) == dfname) %>% 
            (function(x, dfname2 = dfname) {
                df <- x$data[[1]]
                var <-  x$response[[1]]
                df2 <- select(df, !!!var)
                colnames(df2) %>%
                    walk(function(cname) {
                        tibble(df2[[cname]]) %>%
                            magrittr::set_colnames(cname) %>%
                            arrange(.data[[cname]]) %>%
                            mutate(id = seq_along(.data[[cname]])) %>%
                            {ggplot(., aes(x = .data[[cname]], y = id)) +
                                    geom_point(size = 0.5, alpha = 0.7) +
                                    labs(title = dfname2)} %>%
                            print
                    })
            }) 
    })
```


### Nullen




## Covariaten

### Outliers in continue covariaten


### Balancering van categorische covariaten


### Collineariteit



## Outliers en patronen in de relaties tussen variabelen, inclusief tijd en ruimte

<!-- acf & variogram is hier ook een optie -->

## Databeschikbaarheid voor interacties


