## GW_05.1_terr: lg3_std

```{r}
dataset <- gw51t
respvar <- "lg3_lcl"
stratumvar <- "type"
```


Aantal beschikbare observaties per stratum:

```{r}
table(dataset$type) %>% sort(decreasing = TRUE)
# table(dataset$type:dataset$soilclass) # more heterogeneity can be incorporated if temporal autocorrelation + temporal smoother (+ spatial autocorrelation) don't solve things
```

Gezien de computationele problemen om zeldzamere types te behouden, laten we deze met minder observaties in eerste instantie weg (we kunnen ze ook lumpen met een ander type).

```{r}
dataset <- 
  dataset %>% 
  filter(type %in% 
           (dataset %>% 
              count(type) %>% 
              arrange(desc(n)) %>% 
              filter(n >= 200) %>% 
              pull(type))
         ) %>% 
  mutate(type = droplevels(type))
```

Omwille van het grotere aantal types, wordt de dataset in stukken gesplitst.

```{r}
dataset_nested <- 
  read_scheme_types(lang = "nl") %>% 
  filter(scheme == "GW_05.1_terr") %>% 
  select(type, typegroup) %>% 
  inner_join(read_types(lang = "nl") %>% 
               select(type, typeclass),
             by = "type") %>% 
  mutate(subdataset_name = ifelse(str_detect(typegroup, "3$"),
                                  ifelse(typeclass == "GR",
                                         "GW_05.1_terr_group3_grasslands",
                                         "GW_05.1_terr_group3_other"),
                                  as.character(typegroup)),
         subdataset_name = factor(subdataset_name),
         subdataset_label = str_replace_all(subdataset_name, "_|\\.", "-")) %>% 
  select(-typeclass) %>% 
  inner_join(dataset, ., by = "type") %>% 
  group_by(subdataset_name, subdataset_label) %>% 
  nest() %>% 
  ungroup %>% 
  arrange(subdataset_name)
```

Aantal types en rijen per deelset:

```{r}
dataset_nested %>% 
  mutate(n_types = map_int(data, ~n_distinct(.$type)),
         n_rows = map_int(data, nrow)) %>% 
  select(-data, -subdataset_label) %>% 
  arrange(subdataset_name)
```


```{r results="asis", warning=FALSE, message=FALSE}
pwalk(list(dataset_nested$data, 
           dataset_nested$subdataset_name, 
           dataset_nested$subdataset_label), 
      function(dataset, subdataset_name, subdataset_label) {
        dataset <- mutate(dataset, type = droplevels(type))
        knit_expand("_933_gw51t_lg3.Rmd") %>% 
          {knit_child(text = ., 
                      quiet = TRUE,
                      envir =  environment())} %>% 
          cat(sep = '\n')
      })
```


