# Steekproefsimulatie en poweranalyse volgens scenario's {#app:simsamples}

## Aanpak

### Basisset van gesimuleerde populaties zonder lange-termijntrend

We simuleren een **basisset** van populaties op basis van het model dat specifiek met dit doel werd gefit.
Alle gesimuleerde populaties in de basisset zijn gegenereerd op basis van dezelfde modelparameterwaarden (posterior mean van fixed en hyperparameters).

Elke gesimuleerde populatie is uniek in zijn trekking van random effecten en residuals.
De ruimtelijke populatiegrootte wordt voor elk type gedimensioneerd in overeenstemming met de beschikbare schatting hiervan voor de doelpopulatie (zie paragraaf \@ref(popsize)).
Er worden steeds 12 tijdsstappen voorzien op elke locatie.

Omdat de gesimuleerde populaties moeten dienen voor scenario's met verschillende lange-termijntrend, laten we de lange-termijntrend weg uit het model.
Deze wordt in de scenario's vervangen door een gekende lineaire of exponentiële trend.

Deze basisset dient meerdere doelen:

- om design-based steekproeftrekking en inferentie voor specifieke scenario's te simuleren.
Het gaat dan om herhaalde trekkingen uit een vaste doelpopulatie met bepaalde kenmerken;
- om de invloed van nieuwe spatiale en temporele random effecten (uit dezelfde distributie) op de voorgaande poweranalyse te kunnen vaststellen.

Merk op dat in het model veelal reeds bepaalde types gelumpt werden in kleinere 'typeclusters' (in het model voorgesteld als `type`) om voldoende data te hebben per typecluster.
Ook types van de doelpopulatie waarvoor geen data voorhanden waren, werden aan een typecluster (met data) toegewezen.

In de gesimuleerde populaties worden voor elk origineel type van de doelpopulatie observaties gegenereerd op basis van de toewijzing aan typeclusters.

Voor de toestandsinferentie (design-based spatiotemporeel gemiddelde) hebben we slechts een zesjaarperiode nodig.
Voor de trendinferentie (richtingscoëfficiënt) benodigen we een twaalfjaarperiode.
We simuleren daarom in de basisset een tijdsverschil van twaalf jaar, zodat we voor toestandsinferentie de eerste zes jaar daarvan kunnen gebruiken.

De inputdata om de populaties te simuleren, zien er uit als volgt:

- een hypothetische lijst van locaties (`location`).
We beschouwen dit voor de simulaties niet spatiaal expliciet;
- per locatie komt één bepaald type voor (`type`); per type zijn meerdere locaties voorzien;
- in zoverre het model andere fixed effecten voorziet, wordt dit per type gespreid overeenkomstig de spreiding in de doelpopulatie;
- de tijdsstappen waarvoor we een waarde wensen te simuleren in functie van scenario's.
De tijdsstappen bestrijken een periode van 12 jaar -- we zullen immers kijken naar de trend over 12 jaar.


### Verhoudingen tussen het aantal locaties per type

Tussen types variëren we enkel in ruimtelijke steekproefgrootte, en niet in de frequentie (temporele steekproefgrootte), zoals voorzien in de ruimtelijke en de temporele design.
De temporele design is een systematische sampling.
    
De _verhouding_ tussen het aantal locaties per type, voor oneindige populaties, leiden we af uit de typespecifieke, _spatiale_ variantiecomponent van de schatter (van een doelparameter) voor oneindige populaties, meer bepaald uit de verhouding hiertussen voor verschillende types.
Dit kan zowel voor de toestands- als de trendschatter, maar we baseren ons op de toestandsschatter vermits deze de belangrijkste is.

Om de spatiale variantie per type stabiel te schatten (voor toestand), maken we een variant van de basisset, met per populatie 500 locaties en 6 tijdsstappen voor elk type (pure panel) en zonder artificieel toegevoegde trend.


### Aandachtspunt scenario's: ruimtelijke steekproefgrootte

_Elk scenario_ gaat uit van een gemiddelde ruimtelijke steekproefgrootte per type, voor oneindige populaties.

Deze wordt eerst herverdeeld over de types volgens de verhouding van de spatiale varianties, waarbij we tevens een ondergrens hanteren (om typespecifieke steekproefgroottes te vermijden van < 20% van de gemiddelde steekproefgrootte).

Daarna worden de ruimtelijke steekproefgroottes (per type) naar beneden bijgesteld op basis van de ruimtelijke populatiegrootte van elk type (finite population correction).
De steekproefgrootte van een eindige populatie hangt immers af van zowel de totale populatiegrootte als van de steekproefgrootte bij een oneindige populatie (zie paragraaf \@ref(popsize)).


### Scenario's

Scenario's voor steekproeftrekking kunnen zich onderscheiden in:

- het aantal getrokken locaties (voor alle types samen) uit een oneindige populatie;
- de revisit design;
- de grootte van een aan de populatie (post-hoc) toegevoegde lineaire of exponentiële trend.

De trend kan worden gezien als een constante jaarlijkse verandering (positief: toename, negatief: afname), hetzij op de absolute schaal (lineaire trend), hetzij op de logaritmische schaal (exponentiële trend: relatieve verandering).

- Een absolute verandering in $y_0$ van $\Delta y$ na $\Delta t$ jaren (resulterend in $y_0 + \Delta y$) komt overeen met een jaarlijkse verandering van $\beta = \frac{\Delta y}{\Delta t}$ in de functie $y = \alpha + \beta \cdot t$.
- Een relatieve verandering in $y_0$ van fractie $f$ na $\Delta t$ jaren (resulterend in $y_0 \cdot (1 + f)$) komt overeen met een grondtal $g = (1 + f)^{1 / \Delta t}$ voor de exponentiële functie $y = \alpha \cdot g^t$,
of, uitgedrukt op de logaritmische schaal, met een richtingscoëfficiënt $log(g) = \frac{log(1 + f)}{\Delta t}$ in de functie $log(y) = log(\alpha) + log(g) \cdot t$.

Concreet _definiëren_ we de trend in de scenario's op basis van het resultaat dat we artificieel zullen bereiken na $\Delta t$ jaren: hetzij via het geïntroduceerde absolute verschil $\Delta y$ na $\Delta t$ jaren, ofwel via de multiplicatiefactor $(1 + f)$ na $\Delta t$ jaren (bij een relatief verschil).

Daartoe wordt het 'fixed' deel  (verwachte waarde volgens model) van de gesimuleerde respons vervangen door de boven gestelde functie $y$.
Daarbij wordt het oorspronkelijke 'fixed' deel gesubstitueerd in $\alpha$.
Het random deel van de gesimuleerde respons blijft onveranderd behouden.

Afhankelijk van hoe de instelwaarden zijn uitgedrukt -- absoluut of relatief -- wordt een lineaire trend op de absolute ofwel de logaritmische schaal geanalyseerd.

Merk op dat een toenemende exponentiële trend ($f > 0$) bij milieuvariabelen met negatieve waarden resulteert in steeds sterker dalende waarden.



