## GW_05.1_aq: lg3_std

```{r}
respvar <- "lg3_std"
modelcomponent_tempnoise <- "Precision for hydroyear_std_short"
```

```{r include=FALSE}
rds_filepath <- file.path(datapath, "binary/simmodels",
                          str_c("model_gw51a_", respvar, ".rds"))
modelname <- basename(rds_filepath) %>% str_remove(".rds")
if (exists(modelname)) {
  M1 <- modelname %>% as.name %>% eval
} else {
  M1 <- readRDS(rds_filepath)
}
```

De modelvorm die werd gefit ten behoeve van simulaties, ziet er uit als volgt:

```{r}
M1$.args$formula
```

```{r}
modelterms_type <- 
    targetpop %>% 
    filter(scheme == "GW_05.1_aq") %>% 
    distinct(type) %>% 
    arrange(type) %>% 
    mutate(type = droplevels(type),
           modelterm = str_c("type", type),
           modelterm = ifelse(type == "3110", "type3130_aom", modelterm))
```

<!-- parallellize below chunk per type! -->
<!-- https://stackoverflow.com/questions/47552930/how-to-fork-parallelize-process-in-purrrpmap -->

We simuleren een grote steekproef om de spatiale variantiecomponent per type te bepalen.

```{r}
nsim <- nlocs_per_type * nrow(modelterms_type)
linear_trend <- 0
design_matrix <- 
  tibble(location = str_c("simloc_", str_pad(1:nsim, 5, pad = "0")) %>% as.factor,
         type = rep(modelterms_type$type, each = nsim / nrow(modelterms_type)),
         modelterm_type = rep(modelterms_type$modelterm, each = nsim / nrow(modelterms_type))) %>% 
  tidyr::expand(nesting(location, type, modelterm_type),
                nesting(hydroyear = 1:12,
                        temporal_increase = hydroyear * linear_trend))
```


```{r results="hide"}
# latent_names <- M1$misc$configs$contents$tag
# each simulation is for one location (having one type)
nr_nodes <- min(10, nrow(modelterms_type))
set.seed(123456)
system.time({
clus <- parallel::makeCluster(nr_nodes)
parallel::clusterApply(clus, 
                       as.integer(runif(nr_nodes) * 1e9), 
                       set.seed)
modelpar_simulation_tibble <- 
  parallel::clusterMap(clus,
                       function(type, modelterm, nlocs, seed, model) {
                         tibble::tibble(
                           type = type,
                           modelpar_simulation=
                             purrr::map(1:nlocs,
                    # the below code is preferred over 'n=1000' because otherwise
                    # the sampled hyperparameter values remain constant among posterior samples
                    # and also with seed it repeats random numbers that it already used.
                                ~INLA::inla.posterior.sample(n = 1, 
                                                             result = model, 
                                                             selection =
                                                               magrittr::set_names(list(0),
                                                                                   modelterm),
                                                             seed = seed
                                      )[[1]]))
                       },
                       type = modelterms_type$type,
                       modelterm = modelterms_type$modelterm,
                       nlocs = nlocs_per_type,
                       seed = as.integer(runif(nlocs_per_type) * 5e8),
                       MoreArgs = list(model = M1))
parallel::stopCluster(clus)
})
modelpar_simulation_tibble <- 
  bind_rows(modelpar_simulation_tibble) %>% 
  nest(modelpar_simulation = modelpar_simulation)
set.seed(123456)
system.time(
sim_nlocs_per_type <- 
    design_matrix %>% 
    nest(temporal_design = c(hydroyear, temporal_increase)) %>% 
    nest(location = location) %>% 
    inner_join(modelpar_simulation_tibble, by = "type") %>% 
    unnest(c(location, modelpar_simulation)) %>% 
    relocate(location) %>% 
    mutate(fixef_type = map_dbl(modelpar_simulation, ~.$latent[1, 1]),
           ranef_loc = map_dbl(modelpar_simulation, 
                               ~rnorm(1, sd = invsqrt(.$hyperpar["Precision for loc_code"]))),
           ranef_clus = map_dbl(modelpar_simulation, 
                               ~rnorm(1, sd = invsqrt(.$hyperpar["Precision for cluster_id"]))),
           temporal_noise = # sadly takes much computing time
             map(modelpar_simulation, function(simobs) {
               tau_temporal <- simobs$hyperpar[modelcomponent_tempnoise]
               continue <- TRUE
               while(continue) {
                 sim_temporal <- simulate_rw(tau = tau_temporal,
                                             length = 12,
                                             order = 1,
                                             n_sim = 1)
                 continue <-
                   sim_temporal %>%
                   mutate(change = y - lag(y)) %>%
                   summarise(max_change = max(abs(change), na.rm = TRUE),
                             max_net_change = max(abs(y)),
                             pval_trend =
                               lm(y ~ x) %>%
                               summary %>%
                               {.$coefficients["x", "Pr(>|t|)"]}) %>%
                   {.$max_change < 1.5 * invsqrt(tau_temporal) &&
                       .$max_net_change < 1.5 * invsqrt(tau_temporal) &&
                       .$pval_trend > 0.2} %>%
                   !.
               }
               sim_temporal %>%
                 as_tibble %>%
                 select(ranef_hydroyear = y)
             }),
           resid_noise = 
             map2(modelpar_simulation, modelterm_type, function(simobs, type) {
                 simobs$hyperpar[names(simobs$hyperpar) %>% 
                                   str_detect(str_c("^Stratum.*", 
                                                    str_remove(type, "type")))] %>% 
                 invsqrt %>% 
                 {tibble(resid = rnorm(12, sd = .))}
             })
             )
)
sim_obs_nlocs_per_type <- 
  sim_nlocs_per_type %>% 
  select(-modelterm_type, -modelpar_simulation) %>% 
  unnest(cols = c(temporal_design, temporal_noise, resid_noise)) %>% 
  rowwise %>% 
  mutate(response = sum(fixef_type, ranef_loc, ranef_clus, ranef_hydroyear, resid),
         .keep = "unused") %>% 
  ungroup
```






