# Kenmerken van de gebruikte omgeving

## Platform

```{r session-info, results = "asis", echo=FALSE}
si <- sessioninfo::session_info()
p <- si$platform %>%
  do.call(what = "c")
if ("sf" %in% si$packages$package) {
  p <- c(p, sf_extSoftVersion())
  names(p)[names(p) == "proj.4"] <- "PROJ"
}
if ("rgrass7" %in% si$packages$package) {
  p <- c(p, GRASS = link2GI::findGRASS()[1, "version"])
}
sprintf("- **%s**: %s\n", names(p), p) %>%
  cat(sep = "")
```


## Code versie

```{r results = "asis", echo=FALSE}
gitstate <- status(thisrepo)
code_labels <- 
    c(code_commithash =
          system("git log -n 1 --pretty=format:'`%H`'",
                 intern = TRUE),
      commit_datetime = 
          system("git log -n 1 --pretty=format:'%ai'",
                 intern = TRUE),
      `clean state (unmodified)?` = 
          gitstate$unstaged %>% 
          str_detect("\\.(R(md)?|sh)$") %>% 
          {!any(.)} %>% 
          enclose("`")
    )
sprintf("- **%s**: %s\n", names(code_labels), code_labels) %>%
  cat(sep = "")
```


## Data versie

```{r results = "asis", echo=FALSE}
metadata <- yaml::read_yaml(file.path(datapath, "nonpublic/metadata.yml"))
data_labels <- 
    c(watinalocs_tag = metadata$watinalocs_tag %>% enclose("`"),
      locs_7220_latest_commit = 
          file.path(datapath, "10_input/locs_7220.yml") %>% 
          get_latest_filecommit(gitroot, gitstate),
      locs_7220_datahash = 
          file.path(datapath, "10_input/locs_7220.yml") %>% 
          get_vc_datahash %>% enclose("`"),
      extlocs_tag = metadata$extlocs_tag %>% enclose("`"),
      watinadata_tag = metadata$watinadata_tag %>% enclose("`"),
      gwanalysisdata_tag = metadata$gwanalysisdata_tag %>% enclose("`")
    )
sprintf("- **%s**: %s\n", names(data_labels), data_labels) %>%
  cat(sep = "")
```


## R packages

```{r results = "asis", echo=FALSE}
si$packages %>%
    as_tibble %>%
    select(package, loadedversion, date, source) %>%
pander::pandoc.table(caption = "(\\#tab:sessioninfo)Geladen R packages",
                     split.table = Inf)
```



