# Vergelijking van scenario's

## Hoofdmeetnet GW_05.1_terr

### Primaire milieuvariabele `lg3_lcl`

```{r}
gw51t_lg3_lcl_status_summary <-
    read_vc_special(file.path("20_intermediate1/gw51t_lg3_lcl_status_summary"), root = datapath)
gw51t_lg3_lcl_trend_summary <-
    read_vc_special(file.path("20_intermediate1/gw51t_lg3_lcl_trend_summary"), root = datapath)
```

```{r}
gw51t_lg3_lcl_status_summary %>% 
    distinct(scenario, 
             total_spatialsample_size = total_n_finitepop_spatial, 
             trend_12yearly_multiplier) %>% 
    kable(caption = "De onderscheiden scenario's in GW_05.1_terr voor `lg3_lcl`.") %>% 
    kable_styling(full_width = FALSE)
```



```{r fig.width=10, fig.height=4.5, fig.cap="Het effect van de totale ruimtelijke steekproefgrootte en van de scenariotrend, op de kans dat de _relatieve_ foutenmarge (voor 90% betrouwbaarheid) op de schatting van de doelparameter onder een bepaald maximumniveau ligt."}
gw51t_lg3_lcl_status_summary %>% plot_summary
```

```{r fig.width=10, fig.height=4.5, fig.cap="Het effect van de totale ruimtelijke steekproefgrootte en van de scenariotrend, op de kans dat de _power_ voor het tweezijdig toetsen van de trend t.o.v. een nultrend een bepaald minimumniveau haalt."}
gw51t_lg3_lcl_trend_summary %>% plot_summary
```

## Hoofdmeetnet GW_05.1_aq

### Primaire milieuvariabele `lg3_std`

```{r}
gw51a_lg3_std_status_summary <-
    read_vc_special(file.path("20_intermediate1/gw51a_lg3_std_status_summary"), root = datapath)
gw51a_lg3_std_trend_summary <-
    read_vc_special(file.path("20_intermediate1/gw51a_lg3_std_trend_summary"), root = datapath)
```

```{r}
gw51a_lg3_std_status_summary %>% 
    distinct(scenario, 
             total_spatialsample_size = total_n_finitepop_spatial, 
             trend_12yearly_multiplier) %>% 
    kable(caption = "De onderscheiden scenario's in GW_05.1_aq voor `lg3_std`.") %>% 
    kable_styling(full_width = FALSE)
```

```{r fig.width=10, fig.height=4.5, fig.cap="Het effect van de totale ruimtelijke steekproefgrootte en van de scenariotrend, op de kans dat de _relatieve_ foutenmarge (voor 90% betrouwbaarheid) op de schatting van de doelparameter onder een bepaald maximumniveau ligt."}
gw51a_lg3_std_status_summary %>% plot_summary
```

```{r fig.width=10, fig.height=4.5, fig.cap="Het effect van de totale ruimtelijke steekproefgrootte en van de scenariotrend, op de kans dat de _power_ voor het tweezijdig toetsen van de trend t.o.v. een nultrend een bepaald minimumniveau haalt."}
gw51a_lg3_std_trend_summary %>% plot_summary
```



# Keuze van een scenario
