# Dankwoord {-}

De Meetnetten Natuurlijk Milieu worden ontwikkeld met input vanuit vele INBO-teams.
Dit rapport is een tussentijds resultaat van het ontwerpproces waarin bijdrages zijn verwerkt van Dries Adriaens, Nathalie Cools, Piet De Becker, Luc De Keersmaeker, Steven De Saeger, Luc Denys, Myriam Dumortier, Gerrit Genouw, Cécile Herr, Ivy Jansen, Suzanna Lettens, An Leyssen, Els Mencke, Johan Neirynck, Thierry Onkelinx, Patrik Oosterlynck, Jo Packet, Sam Provoost, Maud Raman, Kevin Scheers, Hans Van Calster, Toon Van Daele, Peter Van Gossum, Gunther Van Ryckegem, Jeroen Vanden Borre, Arne Verstraeten, Mathias Wackenier, Toon Westra en Jan Wouters.

Dank aan de reviewers Nathalie Cools, Gerrit Genouw, An Leyssen, Patrik Oosterlynck, Jo Packet, Peter Van Gossum en Toon Westra voor de constructieve feedback.

De auteurs zijn erkentelijk voor de ondersteuning door Hilde Eggermont, Maarten Hens, Maurice Hoffmann, Gerald Louette, Desiré Paelinckx, Johan Peymen, Marc Pollet en Paul Quataert.

We zijn dankbaar voor de ondersteuning van de Meetnetten Natuurlijk Milieu door het Agentschap voor Natuur en Bos, en in het bijzonder Bernard Van Elegem en Tine Mandonx.

Dankzij het Meetnet Biodiversiteit Agrarisch Gebied (MBAG) kunnen de Meetnetten Natuurlijk Milieu verder worden voorbereid op implementatie.


<!-- # Voorwoord {-} -->

<!-- De tekst voor het optionele voorwoord. -->

# Samenvatting {-}

Het Meetnet Biodiversiteit Agrarisch Gebied (MBAG) wordt ontworpen om de toestand en trend van de biodiversiteit in het agrarisch gebied in Vlaanderen op te volgen.
Via de derde pijler van het MBAG, het drukmeetnet, willen we een grondiger inzicht verkrijgen in de druk op natuur buiten het agrarisch gebied, onder meer ten gevolge van landbouwactiviteiten in het agrarisch gebied.
Het drukmeetnet steunt hierbij op de Meetnetten Natuurlijk Milieu (MNM), die volop in ontwikkeling zijn.
De MNM vormen het kader om het natuurlijk milieu in Natura 2000-habitats en regionaal belangrijke biotopen te monitoren.
Daarmee willen we uitspraken doen over de toestand en de trend van het natuurlijk milieu en milieudrukken op niveau Vlaanderen.
De MNM omvatten meerdere meetnetten, die elk een milieudruk opvolgen in een specifiek milieucompartiment (grondwater, oppervlaktewater, bodem, inundatiewater en lucht).
Ter voorbereiding van de implementatie van de eerste meetnetten van de MNM zijn meetplannen opgesteld.
Het gaat om de meetnetten verdroging en eutrofiëring via het grondwater, eutrofiëring via het oppervlaktewater en eutrofiëring via de bodem.
Dit rapport licht de onderliggende ontwerpconcepten en -keuzes toe en presenteert de eerste versie van de meetplannen.
Per meetnet werd hiervoor een ruimtelijke steekproef getrokken, zijn milieu- en meetvariabelen geselecteerd en werden protocollen verzameld.
Tot slot somt het rapport de volgende stappen op in de optimalisatie van de meetplannen en de uiteindelijke implementatie van de meetnetten.


<!-- # Aanbevelingen voor beheer en/of beleid {-} -->

<!-- Verplicht wanneer relevant. -->
