\benglish

# English abstract {-}

The project Monitoring Biodiversity in Agricultural Areas (_Meetnet Biodiversiteit Agrarisch Gebied_, MBAA) is designed to monitor the state and trend of biodiversity in agricultural areas.
The third pillar of MBAA, the pressure monitoring network, aims to gain a more thorough insight into the pressures due to, among others, agricultural activities on nature outside the agricultural area.
The pressure monitoring network relies on the Monitoring Programme for the Natural Environment (_Meetnetten Natuurlijk Milieu_, MNE), which is under development.
The MNE forms the framework for monitoring the natural environment in Natura 2000 habitats and regionally important biotopes.
Based on this monitoring, we want to make statements about the state and trend of the natural environment and environmental pressures on nature at the level of Flanders.
The MNE includes several monitoring schemes, each of which monitors an environmental pressure in a specific environmental compartment (groundwater, surface water, soil, inundation water and air).
In preparation for the implementation of the first MNE monitoring schemes, data collection plans have been drawn up.
The monitoring schemes considered are those on desiccation and eutrophication through groundwater, eutrophication through surface water, and eutrophication through soil.
This report explains the underlying design concepts and choices and presents the first version of the data collection plans.
For each monitoring scheme, a spatial sample was drawn, environmental and measurement variables were selected, and protocols were collected.
Finally, the report lists the next steps in the optimization of the data collection plans and the final implementation of the monitoring schemes.

\eenglish
