# Inleiding

Dit meetplan werd opgebouwd in het kader van het Meetnet Biodiversiteit Agrarisch Gebied (MBAG).
Met het MBAG willen we de toestand en trend van de biodiversiteit in het agrarisch gebied opvolgen.
MBAG bouwt zo veel mogelijk voort op bestaande monitoring en is gestructureerd in drie meetnetten, nl. een toestandsmeetnet, een effectiviteitsmeetnet en een drukmeetnet.
Het drukmeetnet heeft als doel een grondiger inzicht te verkrijgen in de toestand en trend van de druk op natuur buiten het agrarisch gebied, onder meer ten gevolge van landbouw.
Het drukmeetnet is opgebouwd uit een module over de impact op abiotiek in natuurgebieden en twee aanvullende modules over verontreiniging door gewasbeschermingsmiddelen via het voedselweb en impact op biodiversiteit elders in de wereld.
De module inzake de impact op abiotiek in natuurgebieden steunt op de Meetnetten Natuurlijk Milieu (MNM) die volop in ontwikkeling zijn.

## Meetnetten Natuurlijk Milieu {#MNM}

De Meetnetten Natuurlijk Milieu hebben als doel de toestand en de trend van milieudrukken in Natura 2000-habitats en regionaal belangrijke biotopen in Vlaanderen te monitoren.
Diverse milieudrukken verhinderen of bedreigen de beoogde toestand van habitattypes in belangrijke mate.
Het natuurbeleid heeft als taak om het kader en de maatregelen(programma’s) te voorzien opdat de milieuknelpunten voor natuur zouden worden opgelost.
De MNM dienen dus de onderbouwing, planning, evaluatie en bijsturing van het Vlaamse natuurbeleid te ondersteunen.
Hoewel er in Vlaanderen diverse milieumeetnetten operationeel zijn, ontbreekt de systematische monitoring van het natuurlijk milieu van Natura 2000-habitats en regionaal belangrijke biotopen in Vlaanderen.
Nochtans is de opvolging van de staat van instandhouding én de potentiële oorzaken van achteruitgand ervan juridisch vastgelegd in artikel 50undecies van het Natuurdecreet.
Daarnaast zijn de monitorings- en rapporteringsverplichtingen volgens de Habitatrichtlijn (artikels 11 en 17) een onrechtstreekse beweegreden om de MNM te starten.
Het natuurlijk milieu speelt namelijk een rol in de beoordeling van de regionale staat van instandhouding, via specifieke structuren en functies.

In het basisrapport (Vanderhaeghe et al. 2017) werden de beleidsvragen geformuleerd en kernvragen geïdentificeerd:

-   waarom is de staat van instandhouding ongunstig en/of evolueert het niet of onvoldoende in de gewenste richting? (*diagnose*)
-   hoe is het gesteld met de actuele milieu-aspecten die doorwerken in de bepaling van de regionale staat van instandhouding en en hoe verhouden ze zich ten opzichte van de (tussentijdse) gewestelijke doelstellingen van het Natura 2000-programma? (*beoordeling*)
-   hoe zullen de diagnose van de milieuknelpunten en de beoordeling van de toestand evolueren over 6 jaar, 12 jaar en in 2050 en zullen we op tijd de toekomstdoelstellingen bereiken? (*toekomstverwachting*)

## Milieudrukken {#milieudrukken}

In de monitoring van het natuurlijk milieu, of de milieukwaliteit van natuur, speelt de standplaats een sleutelrol.
De standplaats is een lokale, ruimtelijke eenheid die homogeen is in de voor planten belangrijkste milieufactoren en zouden we kunnen vertalen als een ‘homogene habitatvlek’.
De standplaats kan door een kleiner proefvlak worden vertegenwoordigd voor gegevensinzameling.
Een standplaats kan abiotisch gekarakteriseerd worden door milieufactoren, de zogenaamde standplaatsfactoren.
Een milieufactor is een specifieke milieu-eigenschap die en toestand beschrijft, zoals bodem-pH of waterpeil.
Met één milieufactor of standplaatsfactor hangen typisch meerdere milieuvariabelen samen, waaruit gekozen kan worden om de milieu- of standplaatsfactor te vertegenwoordigen.
Een milieuvariabele is een variabele waarvan de bepaling of berekening eenduidig vastligt, met inbegrip van het tijdsinterval waarvoor één waarde geldt en met inbegrip van alle aspecten van de meettechniek en desgevallend monstername en –bewaring.
Een voorbeeld van een milieuvariabele gelinkt aan de milieufactor waterpeil is de gemiddeld laagste grondwaterstand, bepaald met gekende, heldere procedures.

Wijzigingen in milieufactoren geeft aanleiding tot een cascade aan oorzaak-gevolgrelaties: de wijziging in één factor veroorzaakt wijzigingen in een of meerdere milieufactoren, die op hun beurt wijzigingen veroorzaken in andere milieufactoren, enzovoort. Op deze manier kan een wijziging in een milieufactor een negatieve invloed uitoefenen op natuur.
Wanneer een wijziging van een milieufactor van antropogene oorspong is, als onmiddellijk gevolg van een maatschappelijk proces (zoals landbouw, verkeer en industrie), en die een (vaak onrechtstreekse) negatieve invloed op natuur uitoefent, dan spreken we over een milieudruk.
Een milieudruk is dus gedefinieerd in termen van een antropogene milieuverandering.
Negen milieudrukklassen werden onderscheiden, z
Een volledig overzicht van de beschouwde milieudrukken is te raadplegen in het basisrapport (Vanderhaeghe et al. 2017) (en lijst plaatsen? zie figuur \@ref(fig:milieudrukken)).

```{r milieudrukken, message=FALSE, warning=FALSE, results='asis', echo=FALSE}
read_env_pressures(lang = "nl") %>% 
    select(Milieudrukklasse = ep_class_name,
           Milieudruk = ep_name) %>% 
    pandoc.table(
         split.table = Inf ,
         split.cells = c(30,50),
         justify = "left",
         caption = "(\\#tab:milieudrukken)Lijst van de milieudrukken."
)
```

## Types
Alle habitat(sub)types en regionaal belangrijke biotopen die voorkomen in Vlaanderen worden opgenomen in de MNM.
In de MNM wordt hiernaar verwezen onder de benaming 'types'.
+aantal?
+lijst?

## Afbakening van milieudrukken en types {#afbakening}
Om de meetnetten te ontwerpen, dienden keuzes te worden gemaakt en prioriteiten gesteld en dit op vlak van milieudrukken, types en standplaatsfactoren.
Niet elke milieudruk beïnvloedt sterk het natuurlijk milieu en niet elke milieudruk beïnvloedt elke standplaatsfactor en elk type laat staan in dezelfde sterkte.
Niet elke standplaatsfactor is relevant voor elk type.
Om de milieudrukken te prioriteren, werd een instrument opgesteld, nl. het afwegingskader voor milieudrukken.
Het bevat een overzicht van de mate waarin elk type door elke milieudruk actueel wordt beïnvloed op niveau Vlaanderen en voor elke milieudruk gevoelig is.
De actuele milieuproblematiek van elk type in Vlaanderen is gebaseerd op een expertenbevraging op INBO in 2016 naar invloedrelaties per milieudruk en type.
Het belang van een invloed hangt samen met zowel de ‘gemiddelde’ impact op de beïnvloede standplaatsen als het oppervlakte-aandeel van het type in Vlaanderen dat door de milieudruk wordt beïnvloed.
De gevoeligheden van elk type zijn gebaseerd op de effectenindicator en toegewezen gevoeligheden voor specifieke milieudrukken.
Op basis hiervan werden een rangschikking en indeling van milieudrukken voor alle types afzonderlijk bekomen en dit per waterhuishoudingsklasse (droog tot vochtig, tijdelijk tot permanent nat en oppervlaktewater).
Een type kan namelijk tot meer dan één waterhuishoudingsklasse behoren.
Voor meer info over het afwegingskader milieudrukken verwijzen we naar (het technisch achtergronddocument??).

Het afwegingskader maakte het bovendien mogelijk om milieudrukken algemeen te rangschikken voor elke waterhoushoudingsklasse, van hoogste belang (vb. druk 11 en druk 3.1) tot laagste belang (vb. druk 4.3, druk 7.3, druk 8.5 en druk 9.1). 
In de selectie van milieudrukken werd het afwegingskader milieudrukken bovendien gecombineerd met een aantal principes.
Sommige milieudrukken zijn gelinkt aan vernietiging, zijn gericht op fauna of zijn moeilijk in verband te brengen met standplaatsfactoren en vallen daarom, ondanks hun informatienood, buiten de scope van de MNM
Het resultaat was een selectie van 25 milieudrukken die worden opgenomen in de MNM.

Ten slotte liet het afwegingskader ook toe om doelpopulaties (types) af te bakenen voor elke milieudruk.
De doelpopulatie van een milieudruk is de verzameling van types die door de MNM worden opgevolgd om uitspraken te kunnen doen over de invloed van die milieudruk (via monitoring van een geschikte standplaatsfactor). 
De wijze van afbakening van de doelpopulatie per milieudruk hangt af van het belang van de milieudruk (bepaald in het afwegingskader milieudrukken): voor milieudrukken met het hoogste belang bestaat de doelpopulatie uit types die eraan gevoelig zijn, terwijl voor milieudrukken van het laagste belang de doelpopulatie bestaat uit de types die er sterk of matig door worden beïnvloed.
De milieudrukken verontreiniging (drukken 8.1 tem 8.4) hebben te veel kennishiaten, waardoor een precieze omlijning van de doelpopulatie verder te evalueren is.

## Standplaatsfactoren in het conceptueel systeemschema {#standplaatsfactoren}
Aangezien een milieudruk gedefinieerd is als een wijziging in standplaatsfactoren, dienden standplaatsfactoren geselecteerd te worden per milieudruk.
Standplaatsfactoren bevinden zich in één van de milieucompartimenten van de standplaats.
Een milieucompartiment is een ruimtelijke eenheid in de standplaats die een apart deel van het standplaatsmilieu vertegenwoordigt, zoals atmosfeer, bodem, oppervlaktewater, grondwater en inundatiewater.
Primaire standplaatsfactoren zijn die waarover de toestand en trend wordt gerapporteerd en waarmee een milieudruk wordt geëvalueerd.
Aanvullende standplaatsfactoren bieden ondersteuning bij de verdere interpretatie van de toestand en trend van de primaire standplaatsfactor en dienen niet per definitie op de standplaats te zijn bepaald (vb. omgeving).
De selectie van primaire standplaatsfactoren is gebeurd op basis van het afwegingskader standplaatsfactoren, ingebouwd in het conceptueel systeemschema, rekening houdend met de waterhuishoudngsklasse.
Het systeemschema bevat voor elke milieudruk de aanduiding van onder meer die standplaatsfactoren die rechtstreeks door de milieudruk worden beïnvloed, én de aanduiding van het compartiment dat het eerst wordt beïnvloed.
In de MNM beschouwen we P-proxies (P van Pressure), dit zijn standplaatsfactoren die volgens het conceptueel systeemschema rechtstreeks door een milieudruk worden beïnvloed.
Een verdere selectie gebeurde door uit een ruimere set van beschikbare P-proxies voor een milieudruk enkel de meest typische vertegenwoordiger te weerhouden en per waterhuishoudingsklasse de P-proxies te selecteren uit het milieucompartiment dat het meest rechtstreeks door de milieudruk wordt beïnvloed.
Voor meer info over het conceptueel schema verwijzen we naar (het technisch achtergronddocument??).

## Compartimentmeetnetten {#compartimenten}
Een meetnet beoogt vragen te beantwoorden over één milieudruk in één milieucompartiment.
De verschillende milieucompartmenten die we beschouwen binnen de Meetnetten Natuurlijk Milieu zijn atmosfeer, bodem, grondwater, inundatiewater, oppervlaktewater en waterbodem.
Omwille van praktische organisatie worden de meetnetten uit eenzelfde milieucompartiment gegroepeerd tot compartimentmeetnetten.
De meetnetten dienen samen één coherent geheel te vormen.
We onderscheiden vijf compartimentmeetnetten op basis van de zeven hoofdmeetnetten:

- grondwatermeetnet, met de hoofdmeetnetten verdroging via grondwater (druk 5.1) en eutrofiëring via grondwater (druk 3.3);
- bodemmeetnet, met het hoofdmeetnet eutrofiëring via de bodem (druk 3.2);
- oppervlaktewatermeetnet (waterkolom en -bodem), met het hoofdmeetnet eutrofiëring via het oppervlaktewater (druk 3.4);
- inundatiewatermeetnet, met het hoofdmeetnet eutrofiëring via het oppervlaktewater (druk 3.4);
- atmosferisch meetnet, met de hoofdmeetnetten eutrofiëring via de lucht (druk 3.1) en verzuring via de lucht (druk 4.1).

## Keuzes meetnetontwerp {#ontwerpkeuzes}

ruimtelijk gebalanceerde aselecte steekproef
typegroepen
steekproefgrootte: gewenste betrouwbaarheid van toestand en trend vs financiële capaciteit, beleidsprioriteiten en opportuniteiten



## Meetplannen {#meetplan}
Meetplannen hebben als doel de concepten en het ontwerp van een monitoring te vertalen naar een plan van aanpak die kan worden geïmplementeerd op het terrein, met het oog om de doelstellingen van de monitoring te bereiken. Een meetplan wordt opgesteld op meetnetniveau. Omwille van praktische voordelen op het terrein, wordt de meetplannen geaggregeerd tot op compartimentniveau (??). Een meetplan dient per meetnet een antwoord te bieden op de volgende vragen:

- op welke locaties van habitat(sub)types en regionaal belangrijke biotopen wordt de monitoring uitgevoerd?
Hiervoor wordt de doelpopulatie vertaald naar een ruimtelijk expliciet steekproefkader waaruit via een steekproeftrekking met vooraf bepaalde steekproefgrootte de steekproef wordt getrokken.
- hoe frequent en wanneer worden de locaties gemonitord? Voor elk meetnet wordt een herbezoekschema opgesteld. In combinatie met de hiervoor getrokken steekproef, levert dit een concrete lijst en kaartlaag van de spatiotemporeel-expliciete steekproef.
- welke primaire meetvariabelen en extra meetvariabelen ter verklaring of kwaliteitscontrole worden op de locaties opgemeten? Hiervoor dienen de standplaatsfactoren te worden vertaald naar milieuvariabelen en uiteindelijk meetvariabelen die op de getrokken locaties worden gemonitord. 
- hoe worden de meetvariabelen opgemeten? Hiervoor dienen protocollen voor handen te zijn om de evaluatie van de locatie op terrein, de wijze van bemonstering, de wijze van het hanteren en de installatie van toestellen, de monstertransport en de staalvoorbereiding transparant, reproduceerbaar en uniform te maken.



