# Meetnetten en hun doelpopulaties in het MBAG

De MNM omvatten meerdere meetnetten die niet allemaal tegelijkertijd kunnen opgestart worden.
Een gefaseerde implementatie van de verschillende meetnetten is te verkiezen omwille van praktische redenen (niet alle functies kunnen tegelijkertijd geworven en opgeleid worden) en beleidsprioriteiten die zich vertalen naar financiële opportuniteiten.

In het MBAG worden de volgende hoofdmeetnetten van de MNM beschouwd voor een eerste implementatiefase, de zogenoemde *kernhoofdmeetnetten*:

- eutrofiëring via bodem (SOIL_03.2);
- eutrofiëring via grondwater (GW_03.3);
- eutrofiëring via oppervlaktewater, opgesplitst in de deelmeetnetten
  - partim lentische types (stilstaande wateren) (SURF_03.4_lentic)
  - partim lotische types (stromende wateren) (SURF_03.4_lotic)

Het hoofdmeetnet verdroging via grondwater (GW_05.1) surft grotendeels mee op de eerste implementatiegolf en wordt opgesplitst in twee deelmeetnetten:

  - partim terrestrische types (GW_05.1_terr) - gedeeltelijk (typegroepen 2 en 3)
  - partim aquatische types (GW_05.1_aq)
  
De volgende secundaire meetnetten surfen mee op de eerste implementatiegolf:

- vernatting via grondwater (GW_05.2)
- verzuring via grondwater (GW_04.2)
- verzoeting via het grondwater (GW_07.1)
- verzoeting via het oppervlaktewater (incl. inundatiewater) (SURF_07.2)
- afname van stroomsnelheid, waterpeil en/of de fluctuatie ervan (SURF_064_lentic)?

De meetplannen van deze kernhoofdmeetnetten worden prioritair uitgewerkt. De meetplannen van de hoofdmeetnetten eutrofiëring via inundatiewater, eutrofiëring via atmosfeer en verzuring via atmosfeer worden in een of volgende fasen uitgewerkt voor implementatie.

De MNM hebben als default Vlaanderen als domein waarop de uitspraken worden gerapporteerd.
figuren: doelpopulaties per meetnet?
