# Steefproefkader

Op basis van Habitatkaart 2023 werd een basissteekproefkader aangemaakt.
Het basissteekproefkader bevat een laag voor elk stratum.
Een stratum is een hoofdtype of subtype, waarbij geen overlap voorkomt tussen sub- en hoofdtypes, en welke in het geval van stilstaande wateren en mergelgroeven verder zijn opgedeeld volgens grootteklassen (zie ook \@ref(stratificatie)).

Aan de populatie-eenheden worden vervolgens GRTS-adressen toegekend.
Drie verschillende types populatie-eenheden worden hierbij onderscheiden: niet-cel-eenheden (oppervlaktewater, waterlopen type 3260, type 7220 en mergelgroeven type 8310), centroïde-gebaseerde celeenheden en celeenheden.

<!-- ik denk niet dat we hier iets kunnen laten zien maar misschien wel verwijzen naar de datalagen? -->
<!-- FV: zie bv. https://github.com/inbo/n2khab-mne-design/blob/d6cb295427f82c4cd92250151f0ebb27080e7edd/030_preparations/010_explore_targetpop/70_conclusions.Rmd#L187-L193 
deze staan allemaal op Zenodo (voor algemeen overzicht zie ook https://inbo.github.io/n2khab/articles/v025_geospatial_hab.html#data-sources-1) -->

## Ruimtelijke restricties

De doelpopulatie van een aantal meetnetten dient ruimtelijk te worden ingeperkt, zoals aangegeven in tabel \@ref(tab:spatial-restrictions). 

```{r spatial-restrictions}
scheme_targetpop_sets %>%
  filter(stset_name == "mbaa_mne_phase_1_schemes") %>%
  pluck("scheme_set", 1) %>%
  filter(!is.na(spatial_restriction)) %>%
  select(
    Meetnet = scheme,
    `Ruimtelijke inperking (Engels)` = spatial_restriction
  ) %>%
  kbl(caption = "Voor een deel van de meetnetten wordt de doelpopulatie ruimtelijk ingeperkt.") %>%
  kable_styling(full_width = FALSE)
```
