# Steekproefgroottes en panels (en herbezoekschema's??-> eerder voor 060 variables?) 

Dit hoofdstuk van het meetplan beschrijft de ruimtelijke en temporele toewijzing van de meetlocaties per meetnet.

## Steekproefgroottes

Enkel voor de hoofdmeetnetten worden steekproefgroottes ingesteld.
Secundaire meetnetten krijgen geen specifieke steekproefgrootte toebedeeld: enkel die locaties die samen voorkomen in de betrokken steekproefkaders zullen worden opgenomen in de secundaire meetnetten. Echter, voor die types van de secundaire meetnetten die niet voorkomen in de hoofdmeetnetten, worden extra steekproefgroottes toegevoegd.

De steekproefgroottes van een hoofdmeetnet worden verdeeld over de meetnetspecifieke typegroepen.
Hoewel een zelfde precisie van uitspraak wordt beoogd voor de verschillende typegroepen, wordt een gebalanceerde verdeling over de types eveneens beoogd.
De uiteindelijke verdeling is het resultaat van een evenwichtsoefening.
Deze dient, enerzijds, te garanderen dat uitspraken over de verschillende typegroepen binnen een meetnet een gelijkaardige precisie behalen (i.e. streven naar een gelijke verdeling van locaties tussend  de typegroepen).
Anderzijds, dient ze voldoende flexibiliteit te hebben die toelaat om post-hoc types te herschikken over de typegroepen bij een herafbakening of herdefiniëring van de typegroepen zonder een dat de precisie van de uitspraak van de betrokken typegroepen in het gedrang komt.
Het resultaat is dat typegroepen met veel types een groter steekproef krijgen toebedeeld dan typegroepen met weinig types.

Een vooropgestelde verdeling van de steekproef over de verschillende typegroepen en types gaat ervan uit dat de doelpopulatie oneindig groot is.
De doelpopulaties zijn echter eindig en in sommige gevallen zelfs kleiner dan de vooropgestelde steekproefgrootte.
Om hiervoor te corrigeren worden de steekproefgroottes per type herberekend rekening houdend met een eindigepopulatiecorrectie.


<!-- Tabel... overzicht van de steekproefgroottes per meetnet per typegroep, met vermelding van het aantal types per typegroep? -->

## Panels


## Herbezoekschema's
