## Van standplaatsfactoren naar meetvariabelen
Een milieudruk is gedefinieerd als een wijziging in standplaatsfactoren.
Primaire standplaatsfactoren zijn die waarover de toestand en trend wordt gerapporteerd en waarmee een milieudruk wordt geëvalueerd.
Aanvullende standplaatsfactoren bieden ondersteuning bij de verdere interpretatie van de toestand en trend van de primaire standplaatsfactor en dienen niet per definitie op de standplaats te zijn bepaald (vb. omgeving).

De primaire standplaatsfactoren zijn:
-   eutrofiëring via grondwater (GW_03.3): stikstof (N) en fosfor (P)
-   verdroging via grondwater (GW_05.1_terr, GW_05.1_aq en GW_05.1_quarries): waterpeil
-   eutrofiëring via bodem (SOIL_03.2): N en P;
-   eutrofiëring via oppervlaktewater (SURF_03.4_lentic en SURF_03.4_lotic): N en P

Primaire milieuvariabelen werden geselecteerd om de primaire standplaatsfactoren te vertegenwoordigen.
Een milieuvariabele is een variabele waarvan de bepaling of berekening eenduidig vastligt, met inbegrip van het compartiment waarin ze bepaalt wordt, het tijdsinterval waarvoor één waarde geldt en alle aspecten van de meettechniek en desgevallend monstername en –bewaring.
Het is ook voor deze milieuvariabelen dat bereiken kunnen worden afgeleid waarbinnen een habitattype zich duurzaam in gunstige staat bevindt (cfr. HabNorm, rapport Van Calster et al 2020?).

Ter verklaring en interpretatie van de primaire milieuvariabelen, werden bovendien verklarende milieuvariabelen geselecteerd:
- verklarende aanvullende milieuvariabelen, deze zijn ter plaatse op de standplaats bemeten of te meten op monsters genomen op de standplaats, maar hierover wensen we geen uitspraak te doen;
- verklarende omgevingsvariabelen: deze zijn te bemeten in de omgeving van de standplaats, zijn reeds ter beschikking via een andere databron of zijn nog te modelleren.
Ten slotte werden extra meetvariabelen gekozen die ter kwaliteitscontrole van de primaire milieuvariabelen dienen. 

Meetvariabelen beschrijven de directe meting van de milieuvariabele.
Een milieuvariabele kan rechtsreeks overeenstemmen met een meetvariabele, maar kan ook berekend zijn, zoals door aggregatie van meerdere waarden van dezelfde meetvariabele (vb. in tijd of ruimte) of van meerdere meetvariabelen.
Een voorbeeld van de eerste berekeningswijze is de jaargemiddelde hoogste grondwaterstand ten opzichte van het maaiveld, welke de temporele aggregatie vereist van de jaarrond gemeten meetvariabele stijghoogte in een peilbuis.
Een voorbeeld van de tweede berekeningswijze is de fosfaatverzadigingsgraad die berekend wordt uitgaande van de bodemconcentraties van P, aluminium en ijzer na oxalaatextractie.

Onderstaande tabellen lijsten de primaire milieuvariabelen, de verklarende milieuvariabelen en de milieuvariabelen voor kwaliteitscontrole voor  de meetnetten GW03.3, GW_05.1_terr, GW_05.1_aq, GW_05.1_quarries, SOIL_03.2, SURF_03.4_lentic en SURF_03.4_lotic.


(ref:milieuvarGW_03.3) De primaire milieuvariabelen die de primaire standplaatsfactoren vertegenwoordigen, de verklarende milieuvariabelen en de milieuvariabelen voor kwaliteitscontrole voor het meetnet eutrofiëring via grondwater (GW_03.3)
```{r milieuvarGW_03.3}
mv=as_tibble(rbind(c('N', 'primair', 'nitraatconcentratie', 'NO3', 'nitraatconcentratie'),
                  c('N', 'primair', 'ammoniumconcentratie', 'NH4', 'ammoniumconcentratie'),
                  c('P', 'primair', 'orthofosfaatconcentratie', 'PO4', 'orthofosfaatconcentratie'),
                  c('N&P', 'verklarend', 'jaargemid. laagste grondwaterstand t.o.v. maaiveld','LG3', 'stijghoogte'),
                  c('N&P', 'verklarend', 'jaargemid. hoogste grondwaterstand t.o.v. maaiveld','HG3', 'stijghoogte'),
                  c('N&P', 'verklarend', 'sulfaatconcentratie','SO4', 'sulfaatconcentratie'),
                  c('N&P', 'verklarend', 'bodemtextuurklasse','textuur', 'nvt'),
                  c('N&P', 'verklarend', 'nabijheid grondwaterlichaam','GWL', 'nvt'),
                  c('N&P', 'kwaliteitscontrole', 'geleidbaarheid','EC', '-'),
                  c('N&P', 'kwaliteitscontrole', 'kaliumconcentratie','K', 'kaliumconcentratie'),
                  c('N&P', 'kwaliteitscontrole', 'calciumconcentratie','Ca', 'calciumconcentratie'),
                  c('N&P', 'kwaliteitscontrole', 'magnesiumconcentratie','Mg', 'magnesiumconcentratie'),
                  c('N&P', 'kwaliteitscontrole', 'ijzerconcentratie','Fe', 'ijzerconcentratie'),
                  c('N&P', 'kwaliteitscontrole', 'nitrietconcentratie','NO2', 'nitrietconcentratie'),
                  c('N&P', 'kwaliteitscontrole', 'natriumconcentratie','Na', 'natriumconcentratie'),
                  c('N&P', 'kwaliteitscontrole', 'chlorideconcentratie','Cl', 'chlorideconcentratie'),
                  c('N&P', 'kwaliteitscontrole', 'waterstofcarbonaatconcentratie','HCO3', 'waterstofcarbonaatconcentratie'),
                  c('N&P', 'kwaliteitscontrole', 'zuurtegraad','pH', 'pH')
))

colnames(mv) = c('Standplaatsfactor','Type milieuvariabele','Milieuvariabele','Afkorting milieuvariabele', 'Meetvariabele')

mv
has_rownames(mv)

```

<!-- op dezelfde wijze voor GW_05.1_terr, GW_05.1_aq, GW_05.1_quarries, SOIL_03.2, SURF_03.4_lentic en SURF_03.4_lotic-->

