* Intro
The central function of this project is a quantification of the influence which agricultural activities exert on adjacent areas.
This question intrinsically references the phenomenon of spatial coupling, i.e. the non-independence of points in space.
Trivially, the degree of dependence is intimately linked to the spatial distance between locations:
an observation or measurement is more likely to resemble other measurements in its immediate vicinity, than those further away [@Miller2004].

"Tobler's Law", named after Waldo Tobler who popularly phrased and thereby famously formalized this distance-difference relation [@Tobler1970],
raises at least two corollaries for MBAA, which we would like to address in this chapter:
1) at what distance would two measurements be practically identical (justifying re-use of an existing site);
2) what is the maximum reach of common influence factors (i.e. at what distance will observations be mostly independent).

Methods to answer these questions are technically and logistically demanding. 
Reasons are the continuous but anisotropic effects of many common influence factors (e.g. water flow),
the overlap of spatial scales of geographic and biological characteristics (climate regions, habitat types, microhabitat),
and temporal variability (seasonal to daily periodicities).
These factors cause sample size fragmentation,
which turns out to be prohibitive for a direct analysis of available (WATINA) water chemistry parameters to quantify eutrophication.
On the other hand, water /levels/ are monitored continually with data loggers.
Besides their relevance as one of the focus modules of MNE,
water level analysis can also serve as a proxy for spatial coupling of other groundwater related parameters.


In this chapter, we present the outcome of a variogram-based analysis to quantify spatial non-independence (i.e. spatial coupling) of groundwater levels.
By applying a slightly modified procedure, tailored to the specificities of the data set, 
we provide broad answers to the two questions above for the overall region of Flanders.
We herein summarize the main results; interested readers are referred to 
our much more extensive analysis notes [TODO publish] and
a tutorial on variogram analysis [@VgramTutorial2025].


* Results




_____

@article{Miller2004,
 ISSN = {00045608, 14678306},
 URL = {http://www.jstor.org/stable/3693985},
 author = {Harvey J. Miller},
 journal = {Annals of the Association of American Geographers},
 number = {2},
 pages = {284--289},
 publisher = {[Association of American Geographers, Taylor & Francis, Ltd.]},
 title = {Tobler's First Law and Spatial Analysis},
 urldate = {2025-05-16},
 volume = {94},
 year = {2004}
}

@article{Tobler1970,
 ISSN = {00130095, 19448287},
 URL = {http://www.jstor.org/stable/143141},
 author = {W. R. Tobler},
 journal = {Economic Geography},
 pages = {234--240},
 publisher = {[Clark University, Wiley]},
 title = {A Computer Movie Simulating Urban Growth in the Detroit Region},
 urldate = {2025-05-16},
 volume = {46},
 year = {1970}
}


@article{VgramTutorial2025,
 URL = {https://tutorials.inbo.be/tutorials/spatial_variograms},
 author = {Mielke, Falk},
 journal = {INBO tutorials},
 publisher = {[Institute for Nature and Forest Research]},
 title = {An Algorithmic Approach to Variograms},
 urldate = {2025-03-28},
 year = {2025}
}
