## Protocollen

Protocollen zijn noodzakelijk om op een transparante, herhaalbare en uniforme wijze:

- de locatie van een steekproefeenheid op het terrein te evalueren, m.a.w. de evaluatie of de locatie tot het doeltype behoort, en indien nodig te vervangen door een andere steekproefeenheid op een andere locatie via de **locatie-evaluatie- en vervangprotocollen**;
- compartimenten te bemonsteren, toestellen te installeren en stalen te hanteren, te transporteren en voor te bereiden via de **veldprotocollen**;
- stalen chemisch te analyseren via de **laboprotocollen**.

### Evaluatie- en vervangprotocollen voor locaties

Het locatie-evaluatieprotocol laat toe om op terrein te **evalueren of de locatie tot de doelpopulatie behoort**.
Dit komt op de eerste plaats neer op het controleren of de vegetatie die in de steekproefeenheid voorkomt tot het habitattype of de regionaal belangrijke biotoop behoort waarvoor de steekproefeenheid is getrokken.
Dergelijke beslissingen maken deel uit van de protocollen voor de monitoring van de biotische habitatkwaliteit en steunen in hoofdzaak op diverse [karteersleutels](https://www.vlaanderen.be/inbo/de-biologische-waarderingskaart/bwk-handleiding-veldsleutels/).
Karteersleutels en monitoringprotocollen zijn nog niet beschikbaar voor alle types.

Specifiek voor de meetnetten in de MNM in het kader van het MBAG dienen **bijkomende criteria** te worden afgetoetst.
Deze toetsen of bemonstering mogelijk is.
Het gaat hierbij over een minimumoppervlakte voor het bodemmeetnet, een minimumvolume voor het oppervlaktewatermeetnet en de aanwezigheid van ondiep grondwater (via grondboring of water in peilbuizen) voor het grondwatermeetnet. 
De bestaande en geplande evaluatieprotocollen voor de habitatkwaliteitsmonitoring zullen worden aangevuld met deze extra criteria, zodat MBAG-MNM-specifieke projectprotocollen voor locatie-evaluatie worden verkregen.

Wanneer een steekproefeenheid op het terrein niet geschikt blijkt voor bemonstering, kan de terreinmedewerker via de procedure in het vervangprotocol binnen een vooraf bepaald gebied **een andere steekproefeenheid selecteren** die wel geschikt is.  
Dit vergroot de kans dat de terreinmedewerker een bemonstering kan uitvoeren tijdens het bezoek aan een gebied en verhoogt de efficiëntie van het terreinwerk.
Reeds beschikbaar is het vervangprotocol '[vervangprocedure voor geselecteerde steekproefeenheden van terrestrische types](https://protocols.inbo.be/2023.01/index.html)', toe te passen als de steekproefeenheid een GRTS-rastercel is.
Afhankelijk van het type (zie \@ref(spatialespreiding)) kan de beoordeling in de centroïde van de steekproefeenheid (bij centroïdgebaseerde koppeling van het steekproefkader) of over de volledige steekproefeenheid (bij celgebaseerde koppeling van het steekproefkader) worden uitgevoerd.
In deze protocollen dient verduidelijkt te worden voor welke types de celgebaseerde koppeling en voor welke de centroïdgebaseerde koppeling geldt. 
De vervangprocedure voor aquatische types, de mergelgroeven (8310) en de kalktufbronnen met tufsteenformatie (7220) zijn nog niet beschikbaar.

Als zelfs na het doorlopen van het vervangingsprotocol geen geschikte steekproefeenheid is gevonden, leidt dit locatiebezoek tot een _non-response_ en dient een volgende steekproefeenheid te worden bezocht.

### Veldprotocollen

De veldprotocollen die nodig zijn voor de **staalname of installatie van materiaal of toestellen** voor de bepaling van de meetvariabelen, zoals vermeld in Tabel \@ref(tab:milieuvar-gw-03-3) tot en met Tabel \@ref(tab:milieuvar-surf-03-4-lotic), zijn raadpleegbaar via [de oude INBO-protocollensite](https://sites.google.com/inbo.be/veldprotocollen/startpagina).
Ze worden stelselmatig geüpdatet en ontsloten via de [INBO-protocollen-website](https://inbo.github.io/protocols/index.html).

Reeds via deze site te raadplegen geüpdate veldprotocollen zijn:

- voor grondwater:
  - Richtlijnen voor het plaatsen van peilbuizen (`sfp-104-nl`)
  - Richtlijnen voor het bemonsteren van peilbuizen (`sfp-105-nl`)
  - Richtlijnen voor het bepalen van het waterpeil in peilbuizen (`sfp-106-nl`)
- voor oppervlaktewater:
  - Bepaling doorzicht waterkolom oppervlaktewater op basis van de Secchi-diepte (`sfp-113-nl`)
  - Bemonstering waterkolom oppervlaktewater (`sfp-114-nl`)
  - Veldmeting abiotiek oppervlaktewater met behulp van WTW Multi 3430 veldmeter (`sfp-115-nl`)
  - Abiotische staalname stilstaande oppervlaktewateren (`spp-116-nl`), een MNM-specifiek projectprotocol dat bovenstaande protocollen integreert voor stilstaande wateren
  - Abiotische staalname waterlopen (`spp-117-nl`), een MNM-specifiek projectprotocol dat bovenstaande protocollen integreert voor stromende wateren
- voor bodem:
  - Bemonsteren aan de hand van oppervlaktemonsters (`sfp-201-nl`)

In sommige gevallen is het nodig een variant van een bestaand protocol uit te werken als een MBAG-MNM-projectprotocol.
Meetnetspecifieke protocollen voor de verzameling van omgevingsvariabelen dienen nog te worden ontwikkeld.

De volgende aspecten zullen worden gebundeld in een **MBAG-MNM-specifiek projectprotocol**:

- betreffende de combinatie van meer dan één (sub)meetnet: om potentiële verstoring te voorkomen, dienen staalname- en betredingsregels te worden gedefinieerd.
- metadataverzameling: verzamelen en opslaan van informatie over de selectie en eventuele vervanging van steekproefeenheden, subsampling en non-response van steekproefeenheden.
Naast het niet beantwoorden van de steekproefeenheid aan de criteria van het locatie-evaluatieprotocol, kunnen ook andere redenen leiden tot een non-response voor een steekproefeenheid.
Deze redenen kunnen gelinkt zijn aan het verzamelen van stalen of data, zoals ontoegankelijkheid van het gebied, vandalisme of verlies van staal.

### Laboprotocollen

De laboprotocollen nodig voor de **chemische analyse van stalen**, zoals vermeld in Tabel \@ref(tab:milieuvar-gw-03-3) tot en met Tabel \@ref(tab:milieuvar-surf-03-4-lotic), zijn [intern](https://drive.google.com/drive/folders/1W7fPb6bHbSbp5mtzEMd-KyFHvZongwIk) raadpleegbaar door INBO-medewerkers.
Op termijn worden ook deze protocollen opengesteld via de [INBO-protocollen-website](https://inbo.github.io/protocols/index.html).
