# Verdere optimalisatie van meetplannen en verdere stappen voor implementatie {#volgendestappen}

## Verdere uitwerking en optimalisatie van de meetplannen: aandachtspunten en revisies

De voorliggende meetplannen zijn het tussentijdse resultaat van het lopende ontwerpproces.
Ze zijn dus niet het eindpunt van het proces, maar zijn nog in verdere ontwikkeling.
Voor een aantal aspecten zijn verdere toevoegingen en uitwerking nodig en optimalisaties wenselijk.

De volgende aspecten vragen nog **verdere toevoeging en uitwerking**:

- het steekproefkader:
  - ruimtelijke inperking van het steekproefkader van deelmeetnet verdroging via het grondwater - mergelgroeven (`GW_05.1_quarries`): beperken tot deze die in contact staan met grondwater;
  - technische update van de steekproefeenheden van stilstaande en stromende wateren;
  - voor de terrestrische eenheden in het steekproefkader: rekening houden met de proportie van habitattypes per eenheid in het basissteekproefkader (de zogenaamde phab-waarden in de Habitatkaart);
  - integreren van beschikbare metadata over eenheden in het meetnet voor de biotische habitatkwaliteit;
  - uitbreiding van het GRTS-raster aan de grenzen van het Vlaams Gewest: een aantal eenheden op de rand van het domein is in de huidige versie niet betrokken;
- de spatiotemporele steekproef:
  - trekking van reserve-eenheden: ter vervanging van eenheden die niet tot de doelpopulatie behoren en eenheden met een verwachte systematische non-response;
  - het membership design (onderdeel van het revisit design), waarbij locaties worden toegewezen aan panels (koppeling spatiale en temporele design);
- de protocollen: 
  - locatie-evaluatieprotocollen: bestaande en geplande protocollen voor de biotische habitatkwaliteitsmonitoring aanvullen met MNM-specifieke criteria;
  - vervangprotocollen voor aquatische types, de mergelgroeven (8310) en de kalktufbronnen met tufsteenformatie (7220);
  - verzameling en opslag van metadata: informatie over de selectie en eventuele vervanging van steekproefeenheden, subsampling en non-response van steekproefeenheden;
  - verzameling van omgevingsvariabelen.


Verdere optimalisatie is **wenselijk** op het vlak van:

- de spatiotemporele steekproef:
  - optimalisatie van het temporele design op basis van poweranalyses (welke meetfrequentie is nodig?), in het bijzonder wat betreft abiotische staalname in oppervlaktewateren op basis van reeds beschikbare tijdsreeksen;
  - optimalisatie van het panel design (volgens welk herbezoekpatroon worden locaties aan tijdstippen gekoppeld?);
  - fijnstelling van de ruimtelijke steekproefgroottes, waar mogelijk op typeniveau, met behulp van poweranalyses;
  - spatiotemporele optimalisatie van de veldwerkplanning: ontwikkeling van een optimalisatietool om de efficiëntie te verhogen (via het reduceren van de bezoektijd en de verplaatsingstijd  tussen opeenvolgend te bezoeken locaties), rekening houdend met de karakteristieken van de meetlocaties en de medewerkers;
  - panelsynergieën tussen meetnetten;
  - aan elkaar koppelen van vlak naast elkaar gelegen steekproefeenheden in het grondwatermeetnet (één meetinstallatie om beide te bedienen), vb. tussen verschillende types die ruimtelijk aan elkaar grenzen of binnen een zeldzaam type;
- de protocollen
  - projectprotocol: uitsluiten van verstoring door combinatie meerdere meetnetten op zelfde locatie;
  - grondwatermeetnet: instellen van de maximale afstand van getrokken GRTS-adres ten opzichte van bestaande meetlocaties met lange tijdreeks van hoge kwaliteit;
  - bodemmeetnet: fijnstelling diepte van bodembemonstering.

Ook na deze toevoegingen en optimalisaties worden de meetplannen op regelmatige basis gereviseerd.
Aanleidingen tot **meetplanrevisie** zijn (niet-limitatief):

- een update van de Habitatkaart of Watervlakkenkaart, wat zal leiden tot de aanpassing van het basissteekproefkader en bijgevolg ook van de ruimtelijke steekproef en toewijzing van ruimtelijke steekproefeenheden aan panels;
- metadata over selectie, vervanging en non-response van steekproefeenheden, welke zullen leiden tot bijsturing van de ruimtelijke steekproef;
- inzicht in het voorkomen van non-response van steekproefeenheden onder specifieke omstandigheden (omgevingsvariabelen), welke zal leiden tot de bijsturing van de poststratificatie om vertekening door non-response te beperken;
- betere inzichten en meer kennis over processen en technieken, welke aanleiding kunnen geven tot wijzigingen in de keuze van op te volgen milieu- en meetvariabelen en veld- en laboprotocollen;
- wijzigingen in keuzes in het meetnetontwerp, zoals vermeld in de paragrafen \@ref(ontwerpkeuzes), in beoogde betrouwbaarheid en precisie van de uitspraken maar ook financiële injecties of beperkingen, welke een impact kunnen hebben op de steekproefgrootte;
- actualisering van het afwegingskader milieudrukken (\@ref(afbakening)), welke kan leiden tot het wijzigen van de doelpopulatie van een meetnet.
- ervaring op het terrein en in het labo, welke feedback zullen genereren die een verdere optimalisatie van het meetplan mogelijk maakt.

