## Volgende stappen in de implementatie van de MNM in het kader van het MBAG

Parallel aan de bijsturing en optimalisatie van de meetplannen, worden stappen ondernomen in de verdere implementatie van de MNM.
Het betreft acties in het kader van (i) praktische aspecten in de uitrol van de meetnetten, (ii) het ontwerp van de analyse- en rapportageketens, (iii) het databeheer, (iv) kwaliteitszorg, (v) onderzoek en ontwikkeling en (vi) communicatie.

De volgende praktische aspecten verdienen uitwerking voor de **uitrol van de meetnetten**:

- de ontwikkeling van een mobiele applicatie voor opslag van metadata en opvolging van het terreinwerk;
- synergieën op het terrein met het biotische habitatkwaliteitsmeetnet;
- temporele optimalisatie van de monsterstroom staalname - staalregistratie - staalvoorbereiding - chemische analyse - staalopslag volgens labocapaciteit;
- de aanwerving en opleiding van terrein- en labomedewerkers en monitoring officers;
- verdere omkadering door en ontwikkeling van draagvlak bij het beleid.

De volgende stappen zijn nodig in het **ontwerp van de analyse- en rapportageketens**:

- de ontwikkeling van validatieroutines om ruwe data te valideren;
- de ontwikkeling van richtlijnen en routines om ruwe data te verwerken tot datasets voor analyse (analysedata);
- de ontwikkeling van analyseroutines om vragen per meetnet te beantwoorden;
- de ontwikkeling van analyseroutines om tijdens een overgangsfase (bv. eerste meetcyclus) historische meetgegevens te gebruiken uit een 'judgment' steekproef (niet-aselect).
Hierdoor kunnen reeds in een vroeger stadium trenduitspraken gebeuren over een langere periode.
De uitspraken zijn echter onder voorbehoud, want de statistische onderbouwing is dan beperkt;
- het verder verbeteren van analysen door gebruik te maken van aanvullende milieuvariabelen en omgevingsvariabelen in de inferenties;
- de ontwikkeling van beleidsgerichte indicatoren over toestand en trend van het natuurlijk milieu;
- het ontwikkelen van semi-automatische rapportagemodules en webpagina's.
Dit omvat ook syntheserapporten, online ontsluiting van indicatoren en input voor de voortgangsrapportages van het Vlaamse en Europese instandhoudingsbeleid;
- de aanwerving en opleiding van data scientists en statistici om het gros van bovenstaande taken te behartigen.

Op het vlak van **databeheer** dienen acties ondernomen te worden in:

- het opstellen en bijsturen van het datamanagementplan;
- het ontwikkelen van een database voor de opslag en raadpleging van het basissteekproefkader en de bijsturing ervan door terreininzicht, revisies van de Habitatkaart en dergelijke;
- het ontwikkelen van een systeem om planning en uitvoering van monitoringsactiviteiten bij te houden;
- de uitwisseling van relevante monitoringdata tussen entiteiten via webprotocollen;
- het ontwikkelen van data-opslagsystemen voor verwerkte ruwe gegevens (analysedata respectievelijk resultaatdata);
- het bevorderen van de publicatie van de verzamelde gegevens als open data binnen het wettelijk toegestane kader;
- het beschikbaar stellen van de verzamelde data via repositories en webprotocollen (API's);
- de aanwerving en opleiding van een data manager.

Daarnaast is een recurrente **kwaliteitszorg** nodig om knelpunten te detecteren en oplossingen voor te stellen, te implementeren en op te volgen.
Dit proces kijkt zowel naar het operationele niveau (van planning terreinwerk tot data-opslag) als naar de effectiviteit van rapportages en indicatoren (worden de kernvragen optimaal beantwoord?).
Hiervoor is een periodieke kwaliteitsrapportage nodig, inclusief een stappenplan met acties.

Los van de continue revisies op basis van nieuw verworven inzichten, werden **onderzoeksnoden en kennishiaten** geïdentificeerd.
Voor de meetnetten in de eerste implementatiegolf is het wenselijk dat deze onderwerpen verder worden onderzocht (niet-limitatief):

- evaluatie van alternatieve milieuvariabelen voor de standplaatsfactor N in het bodemmeetnet 3.2 eutrofiëring via de bodem, met voldoende snelle respons, dicht bij de druk en praktisch haalbaar;
- verder opstellen van gunstige abiotische bereiken voor alle primaire milieuvariabelen en hun betrokken types (cfr. HabNorm);
- analyse temporele autocorrelatie van primaire milieuvariabelen in grondwater en oppervlaktewater;
- evaluatie van nieuwe sensoren;
- selectie en evaluatie van vlakdekkende aanvullende milieuvariabelen of omgevingsvariabelen die correleren met de primaire standplaatsfactoren in grondwater en bodem om de juistheid en precisie van de uitspraken voor Vlaanderen te verhogen, zoals via:
  - GIS-lagen van huidige milieu-informatie verzameld via teledetectie (incl. modellering) of historisch landgebruik via secundaire dataverwerving;
  - procesmodellen of empirische modellen op basis van bestaande metingen.

Onderzoek over deze onderwerpen vereist het verwerven van financiering via projectontwikkeling voor nationale en internationale onderzoeksoproepen.
Ondersteuning van de onderzoekers door een onderzoekscoördinator is hiervoor wenselijk.

Op het vlak van **ontwikkeling** zijn we steeds op zoek naar mogelijke synergieën met andere lopende meetnetten of nieuwe monitoringsinitiatieven.
In het kader daarvan is de uitwerking van een berekeningsmodule voor kosten en personeelsinzet wenselijk.

Tot slot heeft ook **communicatie** een belangrijke rol in de MNM, waarin volgende acties op de planning staan:

- communicatie over de MNM in het kader van het MBAG;
- de opmaak van een communicatieplan voor de MNM: welke informatie wordt op welk moment gedeeld via welke media;
- wetenschappelijke en vulgariserende publicaties over de onderzoeks- en meetnetresultaten.
