---
title: "Meetplannen voor de Meetnetten Natuurlijk Milieu in het Meetnet Biodiversiteit Agrarisch Gebied"
subtitle: "Eerste implementatiefase van de module MNM in het MBAG: ontwerpversie "
author:
  - name:
      given: "Karen"
      family: "Wuyts"
    email: "karen.wuyts@inbo.be"
    orcid: "0000-0002-3371-6828"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
    corresponding: true
  - name:
      given: "Floris"
      family: "Vanderhaeghe"
    email: "floris.vanderhaeghe@inbo.be"
    orcid: "0000-0002-6378-6229"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
reviewer:
  - name:
      given: "Nathalie"
      family: "Cools"
    email: "nathalie.cools@inbo.be"
    orcid: "0000-0002-7059-2318"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  - name:
      given: "Gerrit"
      family: "Genouw"
    email: "gerrit.genouw@inbo.be"
    orcid: "0009-0001-3333-0079"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  - name:
      given: "An"
      family: "Leyssen"
    email: "an.leyssen@inbo.be"
    orcid: "0000-0003-3537-286X"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  - name:
      given: "Patrik"
      family: "Oosterlynck"
    email: "patrik.oosterlynck@inbo.be"
    orcid: "0000-0002-5712-0770"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  - name:
      given: "Jo"
      family: "Packet"
    email: "jo.packet@inbo.be"
    orcid: "0000-0001-5590-323X"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  - name:
      given: "Peter"
      family: "Van Gossum"
    email: "peter.vangossum@inbo.be"
    orcid: "0000-0002-1595-7126"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  - name:
      given: "Toon"
      family: "Westra"
    email: "toon.westra@inbo.be"
    orcid: "0000-0003-2478-9459"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
date: "`r lubridate::today()`"
year: 2024
doi: 10.21436/inbor.106819398
reportnr: 34
depotnr: D/2024/3241/259
cover_description: Bodemstaalname in Heiberg voor chemische analyse (foto door Floris Vanderhaeghe)
link-citations: true
linkcolor: link.colour
citecolor: link.colour
urlcolor: link.colour
geometry: margin=1in
mainfont: "Calibri"
fontsize: 11pt
documentclass: "article"
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/research-institute-for-nature-and-forest.csl
bibliography: ../../refs_mne_design.yaml
lang: nl
style: INBO
floatbarrier: subsubsection
tocdepth: 3
keywords: "monitoring; Natura 2000; habitat; natuurlijk milieu; meetnetten; milieudruk"
community: "inbo"
publication_type: report
funder: Instituut voor Natuur- en Bosonderzoek (INBO)
rightsholder: Instituut voor Natuur- en Bosonderzoek (INBO)
always_allow_html: true
site: bookdown::bookdown_site
params:
  update_rdata_file: FALSE
  update_raster_file: FALSE
  update_raw_textdata: FALSE
  reproduce_r_package_versions: FALSE
output:
  bookdown::html_document2:
    pandoc_args: 
      - "-M"
      - "author=Karen Wuyts, Floris Vanderhaeghe"
    keep_md: TRUE
    number_sections: yes
    code_download: yes
    fig_width: 10
    fig_height: 5
    fig_caption: yes
    df_print: paged
    toc: TRUE
    toc_float:
      collapsed: FALSE
      smooth_scroll: FALSE
    includes:
      in_header: ../../header.html
  INBOmd::pdf_report:
    keep_tex: TRUE
    clean_supporting: FALSE
    includes:
      in_header: header.tex
  bookdown::word_document2:
    pandoc_args: 
      - "-M"
      - "author=Karen Wuyts, Floris Vanderhaeghe"
    number_sections: yes
    keep_md: TRUE
    fig_width: 10
    fig_height: 5
    fig_caption: yes
    df_print: paged
    toc: TRUE
    reference_docx: wordstylesmarkdown.docx
  # INBOmd::gitbook: default
  # INBOmd::epub_book: default
  # # Don't run the format below.
  # # Only required for RStudio to recognise the project as a bookdown project.
  # # Hence don't use 'Build all formats'.
  # bookdown::dontrun: default
---

```{r setup, include=FALSE}
# see script R/renv_snapshotting.R to execute the manual steps needed to UPDATE 
# the file 'renv.lock' with the currently used R and package versions
if (params$reproduce_r_package_versions) {
  source("renv/activate.R") # activate renv on demand
  renv::restore()           # restore package versions from renv.lock
  status <- renv::status()  # we only proceed if project library is in sync with 
                            # renv.lock
  if (!status$synchronized) {
    stop(
      "Restoring package versions went wrong. ",
      "Please run renv::status() manually, solve problems and try again."
    )
  }
}
options(
  scipen = 999,
  knitr.kable.NA = ""
)
conflictRules("n2khab", exclude = c("read_schemes", "read_scheme_types"))
conflictRules("lubridate", exclude = c("intersect", "union"))
conflictRules("tidyr", exclude = "extract")
conflictRules("knitr", exclude = "spin")
conflictRules("kableExtra", exclude = "group_rows")
conflictRules("ggplot2", exclude = "guide_axis_logticks")
conflictRules("git2rdata", exclude = c("meta", "wrap"))
conflictRules("googledrive", exclude = c("request_generate", "request_make"))
conflicted::conflict_prefer("filter", "dplyr")
conflicted::conflict_prefer("select", "dplyr")
library(rprojroot)
projroot <- find_root(is_rstudio_project)
gitroot <- find_root(is_git_root)
datapath <- file.path(projroot, "data")
for (subdir in c(
  "binary/intermediate",
  "text/raw"
)) {
  path <- file.path(datapath, subdir)
  if (!dir.exists(path)) dir.create(path, recursive = TRUE)
}
library(knitr)
library(kableExtra)
library(dplyr)
library(tidyr)
library(stringr)
library(purrr)
library(forcats)
library(ggplot2)
library(ggh4x)
library(cols4all)
library(lubridate)
library(n2khab)
library(n2khabmon)
library(git2rdata, exclude = "pull")
library(terra)
library(units)
library(sf)
library(tidyterra)
# Setup for googledrive authentication. Set the appropriate env vars in
# .Renviron and make sure you ran drive_auth() interactively with these settings
# for the first run (or to renew an expired Oauth token)
if (Sys.getenv("GARGLE_OAUTH_EMAIL") != "") {
  options(gargle_oauth_email = Sys.getenv("GARGLE_OAUTH_EMAIL"))
}
if (Sys.getenv("GARGLE_OAUTH_CACHE") != "") {
  options(gargle_oauth_cache = Sys.getenv("GARGLE_OAUTH_CACHE"))
}
library(googledrive)
library(googlesheets4)
opts_chunk$set(
  echo = FALSE,
  dpi = 300
)
library(INBOtheme)
inbocol_1 <- inbo_steun_blauw
inbocol_2 <- inbo_steun_geelgroen
inbocol_2_light <- inbo_munt
inbocol_3 <- inbo_steun_donkerroos
inbocol_1_contrast <- "white"
inbocol_2_contrast <- "black"
inbocol_3_contrast <- "white"
col_gridline_bw <- theme_bw()$panel.grid$colour
# see functions.R for various kinds of updating theme() functions
if (!interactive() && opts_knit$get("rmarkdown.pandoc.to") == "latex") {
  opts_chunk$set(dev = "cairo_pdf", dpi = 300, out.width = "100%")
  theme_set(theme_inbo(base_size = 10))
}
source(file.path(projroot, "R/functions.R"))
```

```{r set-filepaths}
rdata_path <- file.path(datapath, "binary/intermediate/objects_mbaa_mne_phase_1.RData")
raster_path <- file.path(datapath, "binary/intermediate/grts_mh_n2khab.tif")
update_rdata <- !file.exists(rdata_path) || params$update_rdata_file
update_raster <- !file.exists(raster_path) || params$update_raster_file
```

```{r get-rdata-file, eval = update_rdata}
with_drive_quiet({
  drive_download(
    as_id("14XXjgvEJmt6pqSSLuJNhNL-ZgMUNjGZ1"),
    path = rdata_path,
    overwrite = TRUE
  )
})
```

```{r get-raster-file, eval = update_raster}
with_drive_quiet({
  drive_download(
    as_id("1B0b5rI6-PlpnSr0kk0mx4GhKhoE9bkpt"),
    path = raster_path,
    overwrite = TRUE
  )
})
```

```{r load-datafiles}
load(rdata_path)
grts_mh_n2khab <- rast(
  file.path(datapath, "binary/intermediate/grts_mh_n2khab.tif")
)
```

```{r common-objects}
provinces <- read_admin_areas(dsn = "provinces")
mne_schemes <-
  read_schemes(lang = "nl") %>%
  filter(programme == "MNE")
mne_types <-
  read_types(lang = "nl") %>%
  semi_join(
    read_scheme_types() %>%
      semi_join(mne_schemes, join_by(scheme)),
    join_by(type)
  )
mne_scheme_types <-
  read_scheme_types(lang = "nl", extended = TRUE) %>%
  filter(programme == "MNE")
typeclass_cols <-
  # colourblind-friendly, but low contrast between some colours; white borders
  # are advised:
  c4a("carto.safe", 10) %>%
  set_names(
    mne_types$typeclass_name %>%
      # order typeclass levels to match colours more intuitively:
      levels() %>%
      .[c(1, 5, 3, 10, 4, 9, 7, 2, 8, 6)]
  )
```

