# (PART) Oriëntatie: wat, wie en waarom? {-}

In de volgende hoofdstukken wordt er van uit gegaan dat de lezer reeds een goede basiskennis heeft van het actuele Vlaamse en Europese instandhoudingsbeleid. Daarom wordt in bijgaand [kader](#natuurintro) een inleiding gegeven tot het natuurbeleid, met opgave van de referenties waar meer detail is te vinden.



```{block2, type = "block"}
\hypertarget{natuurintro}{}<A id="natuurintro"></A>**Introductie tot het Europese en Vlaamse natuurbeleid**

De Habitatrichtlijn[^habitatrichtlijn] stelt tot doel om de **natuurlijke habitats en de wilde dier- en plantensoorten van communautair belang** in een **gunstige staat van instandhouding** te behouden of te herstellen **op het grondgebied van de Europese Unie**.
De twee voornaamste aanpakken hiertoe zijn:

- het *Natura 2000 netwerk van Speciale Beschermingszones (SBZ's)*. Dit netwerk integreert de SBZ's van de Habitatrichtlijn en van de Vogelrichtlijn[^vogelrichtlijn]. In dit netwerk dragen *instandhoudingsmaatregelen* en *passende beoordelingen* bij aan herstel of behoud van de gunstige staat van instandhouding van bijlage I habitattypes en bijlage II soorten in hun natuurlijke verspreidingsgebied (artikels 3 tot 11, i.h.b. 3 en 6).
- *beschermingsmaatregelen* (met uitzonderingen) t.a.v. specifieke soorten (bijlage IV en V).

De lidstaten moeten de zg. staat van instandhouding ('conservation status'; zie verder) monitoren (art. 11), moeten voorzien in de nodige landschapsecologische infrastructuur om SBZ's effectief te maken, moeten onderzoek bevorderen voor de diverse facetten en dienen zesjaarlijks te rapporteren (art. 17) over de instandhoudingsmaatregelen, de effecten ervan op de staat van instandhouding en over de monitoringsresultaten [zie ook @louette:2015implementing]. De lidstaten dienen de bepalingen in de eigen wetgeving te implementeren.

Het Natuurdecreet [^natuurdecreet] bevat de implementatie in Vlaanderen van het Europese Natura 2000 beleid (Habitat- en Vogelrichtlijn). Dit deel van het Vlaamse natuurbeleid heet het **instandhoudingsbeleid**. Het instandhoudingsbeleid staat dus in verband met de Europees beschermde habitats en (leefgebieden van) soorten in Vlaanderen. Het Vlaamse natuurbeleid dat niet onder het instandhoudingsbeleid valt, benoemen we hier als het **natuurbehoudsbeleid**. Het staat in verband met niet-Europees beschermde natuur en overige beleidsinstrumenten en -omkaderingen. Het instandhoudings- en het natuurbehoudsbeleid hebben gemeenschappelijk dat ze voorzien in maatregelen in de breedste betekenis (inclusief beleidsbeslissingen e.d.), met oog op *behoud, beheer en herstel van de natuur en het natuurlijk milieu*.  In de beide gevallen is er een actieve en een passieve component aanwezig. Onder 'actief beleid' worden doelentoewijzing, maatregelen op terrein en de opvolging daarvan begrepen. 'Passief beleid' komt neer op het vermijden dat andere activiteiten een hypotheek leggen op doelstellingen van het natuurbeleid, en dit gebeurt via handhaving, wetgeving en vergunningenbeleid.

_**Het instandhoudingsbeleid voorziet in:**_

1. de **aanwijzing** van Speciale Beschermingszones (SBZ's). De SBZ's voor de Habitatrichtlijn (SBZ-H's of *Habitatrichtlijngebieden*) zijn aangewezen in 2014 via de zogenaamde Aanwijzings- of S-IHD-besluiten[^sihd-besluiten]. Dikwijls bestaan Speciale Beschermingszones uit méér dan één 'deelgebied', d.i. wanneer zij bestaan uit een geografisch niet aaneensluitend oppervlak.
1. **instandhoudingsdoelstellingen**. Het betreft voor habitats en soorten een kwalitatief of kwantitatief uitgedrukte doelstelling met betrekking tot een bepaald geografisch oppervlak. Er dient daarbij onderscheid te worden gemaakt tussen de **gewestelijke instandhoudingsdoelstellingen of G-IHD** en de **specifieke instandhoudingsdoelstellingen of S-IHD**, dit is conform het Procedurebesluit[^procedurebesluit-IHD].

    - De *G-IHD* betreffen de doelstellingen op niveau van **het Vlaamse Gewest**, dus het gebied binnen en buiten SBZ's. Ze moeten worden behaald in 2050. Ze definiëren de doelstelling voor de (regionale) 'staat van instandhouding' (SVI) van elk habitattype en elke soort.
        - De SVI is een begrip uit de Habitat- en Vogelrichtlijn om uit te drukken hoe het met een habitattype of soort is gesteld. De SVI wordt voor de Habitat- en Vogelrichtlijn door elke lidstaat zesjaarlijks gerapporteerd voor de biogeografische regio's binnen de grenzen van een lidstaat (zie Figuur \@ref(fig:biogeografie)). De SVI is hetzij gunstig, hetzij matig ongunstig, hetzij zeer ongunstig [@evans:2011assessment]. Voor de Europese Commissie is de SVI van elk habitattype en elke soort dé maatstaf waarmee *zesjaarlijks* de evolutie van de Europees beschermde natuur wordt geëvalueerd [@european_environment_agency:2015state]. De SVI voor het Vlaamse Gewest wordt bepaald ten behoeve van het Vlaamse natuurbeleid, om de voortgang van de realisatiegraad van de G-IHD te kunnen bewaken. De biotische kwaliteitscriteria die aanleiding geven tot de bepaling van de SVI, zijn in Vlaanderen vaak gedefinieerd voor zg. habitat**sub**types [@tjollyn:2009ontwikkeling;@inbo:2015ontwikkeling]. Habitatsubtypes zijn deelentiteiten van een habitattype die het begrip 'vegetatietype' beter benaderen (habitattypes zijn dikwijls een heterogene verzameling van meerdere vegetatietypes).
        - De SVI is samengesteld uit de toestand en trend van bepaalde kenmerken van een habitattype of soort. De SVI is daarmee gekoppeld aan een bepaald tijdsinterval: de afgelopen 6 jaar voor de toestand en de afgelopen 12 jaar voor de trend. De G-IHD komen neer op de *gunstige* SVI voor alle habitattypes en soorten, in het Vlaamse Gewest. Concreet betekent dit dat de G-IHD voor habitattypes doelstellingen specifiëren van areaal, oppervlakte en kwaliteit, en voor soorten van areaal, populatie en leefgebiedskwaliteit. In het geval van kwaliteit speelt het oplossen van milieudrukken een voorname rol. De G-IHD werden vastgesteld in het G-IHD-besluit[^gihd-besluit]. Meer achtergrond wordt gegeven in @paelinckx:2009gewestelijke.
        
    - De *S-IHD* zijn de doelstellingen voor habitattypes (oppervlakte en kwaliteit) en soorten (populatie en leefgebiedskwaliteit) op het niveau van **elke afzonderlijke SBZ**. Momenteel zijn deze bepaald voor de SBZ-H's, via de Aanwijzingsbesluiten. Indien voor een SBZ-H grote overlap bestond met een SBZ voor de Vogelrichtlijn (SBZ-V of *Vogelrichtlijngebied*) is de SBZ-V mee opgenomen in de S-IHD. De S-IHD zijn in het bijzonder nodig om het gewestelijke natuurbeleid ('programmaniveau') te kunnen omzetten naar gebieds- en lokaal natuurbeleid ('projectniveau'), en aldus gebiedsspecifieke instandhoudingsmaatregelen te kunnen uitwerken.
    
1. **actieve instandhoudingsmaatregelen (actief beleid)**. Het betreft de maatregelen die in de Habitat- of Vogelrichtlijngebieden worden genomen om de S-IHD te bewerkstelligen. Het instandhoudingsbeleid hanteert een programmacyclus van zes jaar (conform het Europese Natura 2000 beleid). Daarbij worden de instandhoudingsmaatregelen per cyclus (de zg. prioritaire inspanningen) geconcretiseerd tot *prioritaire acties*. Er zijn twee types te onderscheiden: **acties rond beheer en inrichting**, die zich in het natuurbeheer situeren, en **acties rond verbetering van milieucondities**, zowel brongericht (verminderen van de milieudruk bij de 'bron') als effectgericht (verbeteren van de milieukwaliteit in de habitat- of leefgebiedsvlek). Prioritaire acties zijn veelal gebiedsspecifiek, maar kunnen ook generiek zijn (maatregelprogramma's op niveau Vlaanderen).

1. **passieve instandhoudingsmaatregelen (passief beleid)**. Via wetgeving, handhaving en vergunningverlening wordt er voor gezorgd dat actuele habitatvlekken, actuele populaties van soorten, en de zones die bijkomend nodig zijn om de instandhoudingsdoelen te realiseren, gevrijwaard blijven van negatieve effecten van menselijke plannen, programma's en vergunningsplichtige activiteiten. Meerdere aspecten maken hiervan deel uit [@agentschap_voor_natuur_en_bos:2016voorontwerp]. Zo is er in het kader van een vergunningverlening de verplichte opmaak van een **passende beoordeling** om de impact op de natuurlijke kenmerken van een speciale beschermingszone na te gaan. De modaliteiten daarvoor worden gespecifieerd in *praktische wegwijzers* [zie omzendbrief: @schauvliege:2015omzendbrief]. Het betreft in hoofdzaak effecten die verlopen via het natuurlijk milieu (abiotiek).
Ter ondersteuning van het inschatten van de impact worden door de Vlaamse Overheid inspanningen gedaan om zoveel mogelijk lokale milieugegevens te ontsluiten via een Informatiesysteem Passende Beoordeling. Verder wordt, met oog op de handhaving van alle bestaande Natura 2000 regelgeving, een Handhavingsplan Natura 2000 uitgevoerd.

Het instandhoudingsbeleid heeft als **planmatige omkadering**, conform het Natuurdecreet en het Instandhoudingsbesluit[^instandhoudingsbesluit]:

- het **Vlaams Natura 2000-programma**: dit programma beoogt de *realisatie van de G-IHD*, in cycli van zes jaar en met twee- en zesjaarlijkse evaluaties. De eerste programmaperiode is 2014-2020. Het programma voor deze periode bestaat bij het schrijven van dit rapport als voorontwerp [@agentschap_voor_natuur_en_bos:2016voorontwerp]. Het Natura 2000 Programma (N2000P) *coördineert* de instandhoudingsmaatregelen op gewestelijk niveau en voorziet daarnaast zones buiten de SBZ's om bij te dragen aan het bereiken van de G-IHD.  Het N2000P kan ook voorzien in programmatische aanpakken. *Programmatische aanpakken* zijn integrale programma's op Vlaams niveau om een milieudruk te kunnen reduceren. Momenteel is een Programmatische Aanpak Stikstof (PAS) opgestart om de grootte en de effecten van atmosferische stikstofdepositie in Vlaanderen te reduceren [@vlaamse_regering:2014programmatische].
- de **managementplannen Natura 2000** worden afzonderlijk uitgewerkt per SBZ. Zij beogen analoog de realisatie van de S-IHD, via de *uitvoering* van de instandhoudingsmaatregelen, die zij in grote lijnen uitzetten. Deze maatregelen moeten meer concreet worden opgenomen in **natuurbeheerplannen** en in **overeenkomsten milieucondities**, en conform deze overeenkomsten worden uitgevoerd.  De managementplannen Natura 2000 moeten minstens het 'bindend deel' van het N2000P realiseren. Per programmacyclus doorlopen ze een aantal 'planversies'. Managementplannen Natura 2000 voorzien ook in zoekzones, daar waar nog bijkomende oppervlakte habitat of leefgebied is benodigd. Ze voorzien tevens in actiegebieden, voor de acties rond verbetering van milieucondities (voor brongerichte acties kunnen actiegebieden ook buiten de SBZ liggen).
- **soortbeschermingsprogramma's**: om taakstellingen voor 2020 en 2050 te bereiken, dienen jaarlijks 4 soortbeschermingsprogramma's te worden goedgekeurd [@agentschap_voor_natuur_en_bos:2016voorontwerp]. Elk programma richt zich op de nodige maatregelen voor de G-IHD van één specifieke soort, dus op niveau Vlaanderen.
- **managementplannen**: zij beogen maatregelen in specifieke gebieden *buiten* de SBZ's, hetzij voor het instandhoudingsbeleid (om de G-IHD te kunnen bereiken), hetzij voor natuurbehoudsbeleid.
- **monitoringsprogramma's**: het Natuurdecreet schrijft monitoring voor, zoals in paragraaf \@ref(regelgeving) is uitgelegd. Zowel het draagvlak, de afspraken, de uitvoering en de resultaten (abiotisch en biotisch) dienen volgens het N2000P te worden gemonitord om de voortgang op regionaal, gebieds- en lokaal niveau te kunnen evalueren en bij te sturen. De taak van monitoring vertoont duidelijk een overlap met de monitoringsbehoefte van het Europese natuurbeleid (zie hoger).

**_Op het natuurbehoudsbeleid_** wordt hier zeer summier ingegaan. Specifieke toelichtingen bij  de betreffende artikels van het Natuurdecreet worden onder meer gegeven in een omzendbrief [@ministerie_van_de_vlaamse_gemeenschap:1998omzendbrief]. Het natuurbehoudsbeleid voorziet in regelingen omtrent vegetatiewijzigingen, beheerplannen, (erkenning van) natuurreservaten, subsidies, VEN en IVON, bescherming van historisch permanent grasland, en regels voor het vergunningenbeleid (zie tevens het Besluit Natuurbehoud[^besluit-natuurbehoud]). Qua omkadering zijn er regelingen rond verwerving, beheerovereenkomsten, natuurinrichting, en het recht van voorkoop. Qua planmatige omkadering zijn er gewestelijke en provinciale natuurrichtplannen (deze worden niet verder gemaakt: vervangen door de managementplannen), managementplannen (buiten SBZ) en de Biodiversiteitsvisie. De **Biodiversiteitsvisie** is voorzien tegen 2020 en dient om de focus van het Vlaamse natuurbeleid niet enkel op de Europees beschermde natuur te leggen, maar *ook op andere natuur*.

Het Natuurdecreet bepaalt ook de opdracht voor het INBO om een periodiek **_Natuurrapport_** op te maken. Dit overkoepelt het instandhoudingsbeleid en het natuurbehoudsbeleid. De opdracht omvat:

- een beschrijving en evaluatie van de bestaande natuur in het Vlaamse Gewest;
- de te verwachten evolutie van deze natuur bij ongewijzigd beleid en bij het door de Vlaamse Regering voorgenomen beleid;
- de evaluatie van het voorbije beleid.

Het Oprichtingsbesluit van het INBO [^oprichtingsbesluit] draagt in dit verband op om "*periodiek te rapporteren over de toestand van de natuur en het natuurlijke milieu, en over de effecten van het milieubeleid en de mate waarin de vooropgestelde milieubeleidsdoelstellingen werden bereikt, en toekomstverkenningen te maken en de kennis en de monitoring ervan te evalueren*". Continuïteit in de rapportage over de toestand en de beleidseffecten wordt actueel voorzien door de **natuurindicatoren**, als onderdeel van het Natuurrapport [cf. @demolder:2016natuurindicatoren].


```




![(\#fig:biogeografie)*Situering van Vlaanderen (zwart omlijnd) in de biogeografische regio’s van België (rood omlijnd): de Marien Atlantische, de Atlantische en de Continentale regio. Het door de Europese Commissie ter beschikking gestelde raster (10 x 10 km) voor het bepalen van het areaal van habitattypes en soorten is eveneens weergegeven. Overgenomen van @louette:2013staat.*](../Figuren/Biogeografie.png){width=70%}




