# Lijst van milieudrukken, met betekenis {#app:milieudrukken}

De lijst met toelichting bij de respectievelijke milieudrukken is leesbaar als [online bijlage](https://docs.google.com/spreadsheets/d/1aVUQWQlaL3k5hjuwyH-8c0lW7hjIkPz8VZbNgyMlN0A/edit?usp=sharing), en tevens [als xlsx-formaat](https://drive.google.com/uc?export=download&id=0B-DYcTNHFnIXbU1GQjM5TFh4cmM) te downloaden.

In de context van het vergunningenbeleid bestaat er reeds een classificatie van milieudrukken: de lijst van effectgroepen en effectsubgroepen. Voor gebruik binnen de Meetnetten Natuurlijk Milieu hanteren we een verder uitgebreide lijst, die maximaal is afgestemd op de effect(sub)groepen van het vergunningenbeleid. De uitbreiding is gebeurd:

- omwille van **vertaalbaarheid** naar standplaatsfactoren: een milieudruk moet voldoende nauw zijn afgebakend opdat de erdoor beïnvloede standplaatsfactoren voldoende eenduidig kunnen worden bepaald (bij meetnetontwerp), en opdat standplaatsfactoren vlot met milieudrukken kunnen worden geassocieerd (bij interpretatie van meetnetresultaten). Om dezelfde reden, en om redenen van consistentie, wensten we voor alle milieudrukken bovendien een consequente opgave van de richting van de druk (bv. niet 'wijziging van de grondwaterstand' maar 'verdroging via het grondwater' of 'vernatting via het grondwater'). Dit betekent concreet dat:
    1. de effectgroepen typisch te breed zijn; we benoemen ze als milieudruk-*klassen*;
    1. de effectsubgroepen hetzij worden overgenomen als milieudruk, hetzij nader worden opgesplitst omwille van voldoende nauwe afbakening en/of aangeven van de richting;
    1. in sommige gevallen nog geen milieudrukken bestonden voor een milieudrukklasse, wanneer geen effectsubgroepen bestonden voor een effectgroep. In die gevallen zijn nieuwe milieudrukken gedefinieerd volgens de rationale hierboven.
- omwille van het **vollediger** afdekken van alle milieuproblematieken die Vlaamse habitattypes of RBB's ondervinden. Immers zijn niet alle milieudrukken van lokale oorsprong en toewijsbaar aan een initiatiefnemer, wat wel de context is van het vergunningenbeleid. In het bijzonder is de milieudrukklasse 'klimaatverandering' toegevoegd, met drie milieudrukken. Hiermee worden invloeden van klimaatverandering vertegenwoordigd die plaatsvinden bovenop de invloed van meer direct op gebiedsniveau ontstane milieudrukken, zoals peilwijzigingen. Dit onderscheid is gemaakt, ook al heeft klimaatverandering via onder meer diezelfde milieudrukken invloed op habitats: ze vinden plaats op een andere tijdsschaal en gesuperponeerd bovenop de lokaler ontstane milieudrukken. Behalve via de overige onderscheiden milieudrukken heeft klimaatverandering ook invloed door de toegenomen frequentie van brand en stormschade, en door de aspecten die gepaard gaan met zeespiegelstijging (bij kust- en estuariene types).

De lijst is tot stand gekomen in samenwerking met de INBO-medewerkers van het project [HabNorm](#HabNorm) en werd getoetst met ANB.
