# Voorstel

## Parallellen tussen meetnetten natuurlijk milieu (MNM) en biotisch meetnet

- gebruik van eenzelfde master **GRTS**-grid, met eenheden van 32 x 32 m² [@onkelinx_grts_2019].
We noemen dit verder een 'level0-cel', verwijzend naar de hiërarchische GRTS-niveaus in de `GRTSmh_brick` en `GRTSmh_diffres` databronnen [@vanderhaeghe_grtsmh_brick_2019; @vanderhaeghe_grtsmh_diffres_2019].
- de MNM hebben een **verklarende** waarde voor de resultaten van het biotisch meetnet [@westra_monitoring_2014], dit volgens _flexibel_ samen te stellen typegroepen per meetnet (i.e. typegroepen op maat, voor een milieudruk in een milieucompartiment, waarbij samenstelling van de typegroep makkelijk herzien kan worden) [@vanderhaeghe_meetnetten_2018]
- per type een integratie, op niveau Vlaanderen, van de biotische en abiotische elementen in de **G-SVI** [@vanderhaeghe_vraagstelling_2017]
- uitspraken zijn gewenst zowel op niveau **Vlaanderen** als op niveau van het **SBZ-H netwerk**
- **uitdagingen** i.v.m. steekproef en terreinwerk:
    - het handhaven van een _**aselecte**_ steekproef, in een context van allerhande bestaande meetpunten van een _judgment_ sample.
    N.B.: biotisch wordt geopteerd om van een aantal types bestaande punten (PQ's e.d.) te betrekken.
    - onzekerheid over de effectieve aanwezigheid op een bepaalde locatie van een bepaald type, volgens een van de databronnen `habitatmap_terr`, `watersurfaces_hab`, `habitatstreams`, `habitatsprings` (samen bestrijken deze alle types uit de doelpopulaties van de meetnetten).
    _**Uitdaging**: is het mogelijk om de trefkans te verhogen zodat een getrokken locatie van een type op terrein vaker overeenstemt met het type in kwestie?_
    Deze uitdaging stelt zich vooral terrestrisch, waar types veelal niet dekkend voorkomen in een polygoon en waarbij de locaties in de polygoon niet gekend zijn.
    Een hogere trefkans vermindert het aantal keren dat men op terrein naar een alternatieve locatie moet uitwijken.
    - het praktisch omgaan met de afwezigheid van een type op een bepaalde locatie waar het type voorkomt volgens het steekproefkader.
    Strikt genomen valt een locatie dan af en wordt een locatie uit het steekproefkader toegevoegd op basis van de GRTS-rangschikking.
    _**Uitdaging**: wat zijn mogelijke opties om hier op een meer praktische manier van af te wijken?_
    - veel terrestrische polygonen zijn maar ten dele bedekt door het type in kwestie (cf. phab-waarden).
    _**Uitdaging**: het veelvuldig voorkomen van kleinere habitatvlekken -- waar hogere milieudrukken kunnen worden verwacht (cf. versnippering) -- proberen mee te krijgen in het steekproefkader._
    
## Vaststellingen steekproefkader

- In meer dan 20% van alle gevallen komt (binnen een polygoon) het type voor met een *oppervlakte* kleiner dan de oppervlakte van een level0-cel (1024 m²) (Fig. \@ref(fig:patch-areas)).
De verdeling van deze lage-oppervlakteklassen is quasi uniform.
- Heel wat terrestrische types komen voor een aanzienlijk deel van hun (reële) oppervlakte voor in polygonen waar ze een *phab* van hoogstens 50% halen (Fig. \@ref(fig:phabclasses-areas-typeclass)).

## Overwegingen en voorstel voor de MNM

### Algemeen

We hernemen ter informatie enkele relevante basisprincipes uit @vanderhaeghe_meetnetten_2018.

- Elk meetnet volgt een *aselecte* steekproefstrategie.
- Afdoende ruimtelijke en temporele *dekking*
- Elk meetnet volgt een *eenvoudige* steekproefopzet in ruimte en tijd. Wegens begrijpbaarheid, verwerkbaarheid, duurzaamheid.
- Elk meetnet hanteert een *flexibele* steekproefopzet.
    - Criterium hiervoor: inferentiewijzen kunnen op eenvoudige wijze valide blijven doorheen de tijd, niettegenstaande evolutie van de context.
    - Kenmerken hierbij: aanpasbaarheid van vragen; bestand tegen aanpassing van domeinen en van steekproefkader; flexibiliteit inzake aanpasbaarheid van steekproefgrootte en het kunnen omgaan met non-response.
    - Daarom voorkeur voor equal probability designs.
    - Uitspraken voor (sub)domeinen gebeuren zoveel mogelijk post-hoc en zijn niet inherent aan de design (subpopulation estimations via poststratificatie).
        
Specifiek hieraan verbonden voorkeuren voor de MNM:

- consequent de *GRTS-strategie* volgen.
Het opnemen van een bestaand meetpunt komt voor wanneer dit qua ruimtelijk geldigheidsbereik overlapt met de getrokken cel uit het GRTS-raster.
- indien mogelijk de volledige _doelpopulatie_ meenemen, ook de lagere phab-waarden aangezien een aantal types qua oppervlakte vooral door lage phab-waarden zijn vertegenwoordigd
- ivm flexibiliteit: zie ook paragraaf \@ref(substructuur)

### Steekproefeenheid en steekproefkader voor terrestrische types

- de **steekproefeenheid** is een cel van het GRTS-raster.
Standaard is dit het 32 x 32 m² niveau (level 0), maar afhankelijk van de milieuvariabele kan eventueel voor een ander niveau worden gekozen.
    - de metingen gebeuren steeds om de volledige steekproefeenheid te vertegenwoordigen, met betrekking tot het type.
    Bemerk dat het type meestal _niet_ dekkend voorkomt binnen de steekproefeenheid.
    (Fig. \@ref(fig:detprob-point))
    - het beoogde type in de steekproefeenheid kan op verschillende manieren worden bemeten (vertegenwoordigd), afhankelijk van de milieuvariabele:
        - zeer lokaal geldende metingen (bv. bodemkwaliteit):
            - het type dekkend bemonsteren met een bepaalde intensiteit (geeft een accurater resultaat voor de gehele steekproefeenheid)
            - indien verstoring door bemonstering langduriger inwerkt, of om andere reden (bv. kostprijs, haalbaarheid): het type bemonsteren in een ruimtelijk _deel_ van de steekproefeenheid.
            Deze sublocatie eventueel verschuiven in de tijd: zeker bij verstoringseffecten of indien variatie te verwachten binnen de cel
        - ruimtelijk breder geldende metingen (bv. grondwater, atmosfeer):
            - 1 punt in de steekproefeenheid volstaat voor meting
            - indien meting ruimtelijk breder toepasbaar is dan de steekproefeenheid, kan de meting desgevallend voor meerdere aangrenzende steekproefeenheden (of types) gelden.
            Een variant hiervan is de steekproefeenheden op een hoger hiërarchisch GRTS-niveau onderscheiden.
- voor de opbouw van het **steekproefkader** kunnen de GRTS-rastercellen op twee manieren met de polygonen worden gekoppeld:
    1. puntgebaseerd: op basis van het centroïd of een random punt in elke rastercel: de steekproefeenheid wordt alleen betrokken wanneer dit _punt_ overlapt met een polygoon met het type (op terrein: wanneer het punt _effectief_ overlapt met het type).
De centroïdmethode is toegepast in het meetnet biotische habitatkwaliteit.
    1. celgebaseerd: de steekproefeenheid wordt betrokken wanneer de _rastercel_ overlapt met een polygoon met het type
    
    Aandachtspunten:
    - de *trefkans* met de celgebaseerde methode is veel hoger (Fig. \@ref(fig:detprob-cell), \@ref(fig:detprob-point-cell))
    - de *populatiegrootte* van de celgebaseerde methode is (logischerwijs) veel hoger dan de centroïdbenadering (overwegend 50% tot >100% groter) (Fig. \@ref(fig:popsize-surplus), \@ref(fig:popsize-abs))
    - de _oppervlakteschatting_ volgens het steekproefkader komt in principe exact overeen met de celgebaseerde methode
    
    - in beide methoden kan met **gelijke gewichten** tussen eenheden worden gewerkt in de inferenties, waarbij de reëel verschillende oppervlaktes van een type tussen steekproefeenheden worden geabstraheerd als 'gelijke oppervlaktes'.
        - Een fundamenteel verschil is dat bij puntgebaseerde koppeling grotere celbedekkingen van het type proportioneel vaker gesampled worden, dus dit weerspiegelt in principe goed de totale oppervlakte.
        Bij celgebaseerde koppeling wordt daarentegen uitgegaan van een evenwaardigheid tussen kleinere en grotere vlekken op het sub-level0-celniveau.^[
        Zo'n benadering is enigszins in analogie met de eenheden van de aquatische types, i.e. plassen (ongeacht de oppervlakte).
        ]
    - voor **oppervlaktevertegenwoordiging** wordt in de _centroïdgebaseerde_ methode normaal uitgegaan van een oppervlakte van 1024 m² (32 x 32 m²) voor elke steekproefeenheid omdat de kans op het treffen van een type in een cel gelijk is aan de oppervlakteproportie in die cel.
    Bij implementatie blijkt deze rekenmethode in de praktijk een overschatting te geven, dus er zou nog een correctie toegepast kunnen worden (Fig. \@ref(fig:popsize-centroid-rel)).
    Bij de _celgebaseerde_ methode vertegenwoordigt elke cel de gemiddelde oppervlakte van het type in een cel, over alle cellen.
    
    - _voordelen_ van een celgebaseerde methode zijn:
        - de hogere trefkans op een type, daardoor minder vaak moeten afwijken van de steekproefopzet
        - het kunnen rekening houden met alle ruimtelijke configuraties van een type, cf. het vaak optreden van kleine vlekken, en daardoor de feitelijke doelpopulatie volledig afdekken (fouten/tekorten in de databronnen daar gelaten)
        - de hogere beschikbaarheid aan vervangcellen in de omgeving, in zoverre voor vervanging een strategie gevolgd wordt om het GRTS-raster te gebruiken (zie verder)
        - een directe koppeling tussen de ruimtelijke eenheid die (standaard) bemeten wordt (steekproefeenheid) en deze die voor selectie gehanteerd wordt
    - _nadelen_ van een celgebaseerde methode zijn:
        - verminderde synergie met de centroïdgebaseerde methode (biotisch meetnet): punten worden toegevoegd in de GRTS-reeks
        - grotere populatiegrootte leidt tot enigszins kleinere eindige-populatiecorrectie


### Herlokalisatie van steekproefeenheden

Onderstaande is vooral geïnspireerd op de terrestrische situatie.
In principe kan hetzelfde worden toegepast op de tot punten geabstraheerde waterplassen en waterloopsegmenten.

Wanneer een level0-cel op terrein niet tot de doelpopulatie blijkt te horen (en dus niet in het steekproefkader thuishoorde): is het een optie om _in de nabije buurt_ een locatie te selecteren?
Verschillende benaderingen hiervoor:

- **GRTS-rangschikking** volgen binnen een grotere GRTS-cel om een andere level0-cel te selecteren (hetzij centroïd-, hetzij celgebaseerd).
Ook al wordt door deze vervanging afgeweken van de pure level0-rangschikking, hiermee wordt wel nog strikt de GRTS-benadering op het hogere niveau gevolgd (die ook door een level0-trekking wordt gevolgd indien 'grote cel behoort tot doelpopulatie' wordt gedefinieerd als 'grote cel bevat minstens één level0-cel die behoort tot doelpopulatie').
Ook wordt op deze manier de ruimtelijke balans in stand gehouden tussen eventuele meerdere level0-cellen binnen dezelfde cel van hoger niveau.
Voor deze piste kiezen we voor het niveau **256 x 256 m² (level 3)**:
    - dekt qua grootteorde de meeste polygoongroottes af (waar een type volgens de habitatkaart dus in zou moeten voorkomen) (Fig. \@ref(fig:hist-polarea))
    - is nog haalbaar om in beeld te brengen op terrein volgens een rooster van 32 x 32 m², minstens voor het type dat men zoekt.
    I.e. corrigeren van het steekproefkader binnen een cel van 256 x 256 m² (level 3).
- een **andere werkwijze** die gerandomiseerd een nieuwe locatie toewijst in de omgeving:
    - hetzij vasthoudend aan de steekproefeenheden (level0-cellen) en de koppelingsmethode (centroïd-/celgebaseerd)
    - hetzij los van de steekproefeenheden en de koppelingsmethode (bv. 6510 in biotisch meetnet). 

Een piste op basis van GRTS-celselectie respecteert de oorspronkelijke steekproefeenheden en heeft daarom in MNM de voorkeur.

- Het is gebleken dat voor de meeste types elke level3-cel maar één keer bemonsterd zal worden in een concrete steekproef. 
Dat komt doordat de meeste types nog behoorlijk wat level3-cellen ter beschikking hebben (Fig. \@ref(fig:level3-pertype)).
Slechts bij 12 types is dit aantal lager dan 50.
    - Gevolg: de volgende level0-cel binnen een level3-cel zou normaal niet zijn voorgekomen in een level0-gebaseerde selectie in een correct steekproefkader.
    - In essentie kunnen we dus stellen dat we twee GRTS-adressen verwisselen wanneer we toch de eerstvolgende level0-cel binnen dezelfde level3-cel opnemen.
    Dit valt te verdedigen, aangezien de toewijzing van deze adressen binnen de level3-cel at random gebeurde, en de adressen onderling ruimtelijk gebalanceerd zijn geordend.
    
Er is ook een relatie met de koppelingsmethode tussen polygonen en raster:
bij de celgebaseerde koppeling is de populatie groter, en zijn er dus gemiddeld meer level0-cellen ter beschikking per level3-cel.
(Figuur die de beide methoden hiervoor vergelijkt is nog niet gemaakt.
Wel reeds op haalbaarheid gestaafd voor de centroïdgebaseerde methode).


### Substructuur in de design {#substructuur}

Indien verantwoordbaar vermijden we in de MNM substructuur die verder gaat dan het onderscheid tussen types.
Dit is omwille van flexibiliteit van de design.

Substructuur zorgt voor verschillen in sampling weights tussen steekproefeenheden, en met name bij _monitoring_ wijzigt zo'n substructuur in de tijd en is substructuur dus zoveel mogelijk te vermijden [@overton_desirable_1996; @manly_sampling_2014].
Door die wijzigingen in substructuur gaan sampling weights verschillend evolueren tussen punten en zouden er aldus onevenwichten in de design ontstaan.

M.a.w. extern ontstane wijzigingen van strata (bv. een punt komt in een ander stratum terecht) of veranderde definitie van strata leiden tot cross-stratum-specifieke sampling weights (oude strata x nieuwe strata).
Dit compliceert inferenties en/of noopt tot bijwerken van de steekproef om (alleen in de nieuwe periode) de onevenwichten door oudere substructuur weg te werken.
Daarnaast wordt ook poststratificatie gecompliceerder, want ook hier ontstaan cross-strata met automatisch minder data per cross-stratum.

Concreet toegepast op de MNM lijkt het daarom, in vergelijking met het biotisch meetnet, interessant om:

- geen overbemonstering toe te passen in het **SBZ-H netwerk**.
Er zal daardoor overall een gelijkaardige precisie ontstaan binnen en buiten het SBZ-H-netwerk _terrestrisch_ (want evenveel oppervlakte binnen als buiten), en zo'n 30% kleinere foutmarge binnen SBZ-H t.o.v. erbuiten voor _stilstaande wateren_ (want dubbel zoveel plassen binnen als buiten).
Dit patroon varieert sterk per type: bepaalde types komen vooral voor binnen en andere vooral buiten SBZ-H.
Het is op zich logisch dat de monitoringinspanning voor types die vooral buiten SBZ-H liggen, ook meer buiten SBZ is gesitueerd.
Het SBZ-H netwerk zelf vertegenwoordigt slechts 7.7% van Vlaanderen, dus er is de facto reeds veel aandacht voor omdat er een verhoudingsgewijs groot oppervlakte-aandeel van de doelpopulatie binnen ligt.
- niet te stratificeren volgens **oppervlakteklassen** voor de stilstaande wateren.^[
Dit is inmiddels getoetst met Luc Denys.
]
De steekproefeenheid is de plas, ongeacht zijn grootte.
De informatie op dit niveau (volgens plassen) is, ondanks de discrepantie met de (oppervlaktegewogen) G-IHD, voor het natuurbeleid veel informatiever om (plasgerichte) maatregelen te nemen.
Dit geldt in het bijzonder voor de milieuproblematiek.
De verdeling van plasoppervlakte-klassen volgens plaseenheden (Fig. \@ref(fig:watsurf-areaclasses-polygons)) is immers enorm verschillend van deze volgens oppervlakte-eenheden (Fig. \@ref(fig:watsurf-areaclasses-area)).
    - Deze aanpak zal leiden tot het niet of nauwelijks bemonsteren van de allergrootste plassen (heel gering aandeel), maar dit is de consequentie van het consistent zijn in de keuze 'elke plas is even belangrijk'.
    - Er kan daarnaast wel een oppervlaktegewogen uitspraak gebeuren in functie van G-IHD, ook zonder stratificatie volgens oppervlakteklassen.
    Daarbij kan poststratificatie (of regression estimation) gebruikt worden om de nauwkeurigheid van de oppervlaktegewogen uitspraak te verhogen.
    Daarin speelt de auxiliary variabele van elke plas / oppervlakte-eenheid immers een rol in de schatting (bv. landgebruik in omgeving), zodat hier ook informatie over de grotere plassen wordt meegenomen in de schatting.



