# Ten geleide {#inleiding}

Dit rapport beoogt een ruwe inschatting van steekproefgroottes voor de deelmeetnetten _SURF_03.4_lentic_ (stilstaande wateren) en _SURF_03.4_lotic_ (stromende wateren) in het oppervlaktewatercompartiment van de Meetnetten Natuurlijk Milieu (MNM).
Verder verfijnde berekeningen van steekproefgroottes en verschillende herbezoekpatronen blijven later mogelijk via steekproefsimulaties op basis van een meer gedetailleerd model.
Voor de eenvoud beschouwen we voorlopig enkel de toestand en nog niet de trend.

Voor meer achtergrondinformatie verwijzen we naar @wuyts_meetplannen_2024 en tevens naar een meer gedetailleerd conceptrapport over de strategie in de MNM voor steekproefopzet en inferentie [@vanderhaeghe_meetnetten_2018].
Het voorliggend rapport is een toepassing van paragraaf 7.1.1 van laatstvermeld rapport (toestand 22 jan 2019).

We gebruiken een eenvoudig model om de (gemiddelde) variantie tussen locaties en de (gemiddelde) variantie tussen herhaalde metingen te schatten voor één type, binnen één jaar.
We schatten daarmee de variantie van de design-based schatter van het spatiotemporeel gemiddelde van een (gemiddelde) typegroep over een cyclus van zes jaar.
Op die manier kunnen we het totaal aantal nodige locaties en herhalingen bepalen.
