# Concepten en methodiek

## Schatters en instelwaarden {#schatters}

We leggen hier kort enkele basisconcepten uit. Zie voor meer info @onkelinx_ontwerp_2008, @vanderhaeghe_meetnetten_2018 en meer algemene literatuur over kansrekening en (model-assisted) design-based inferentie, zoals @de_gruijter_sampling_2006, @sarndal_model_1992, @lohr_sampling_2010 en @cochran_sampling_1977.

De steekproefgrootte (zowel ruimtelijk als temporeel) wordt gekozen om een gewenste **precisie** en **betrouwbaarheid** te bekomen van 'schatters', op het niveau van een typegroep. ^[Een typegroep is een niet al te heterogene groep van habitat(sub)types en RBB's, op maat van de milieuvariabele, waarvoor we voldoende nauwkeurige resultaten wensen.]
De schatters zijn een berekening op basis van geobserveerde monitoringdata van een milieuvariabele, waarbij de data voortkomen uit een *aselecte* steekproefopzet (i.e. een steekproef die tot stand komt via een randomisatieprocedure).
Met deze schattingen willen we de waarde $\mu$ voor de totale doelpopulatie zo goed mogelijk bepalen, met name van:

- het spatiotemporeel gemiddelde gedurende zes jaar (toestand);
- het spatiale gemiddelde van de (lange-termijn) trend van een milieuvariabele over 12 jaar (trend); optioneel ook binnen één cyclus van zes jaar (korte-termijntrend).

We spreken van 'schatter' wanneer we de stochastische variabele bedoelen -- in dit rapport gesymboliseerd als $\hat{\mu}$.
Het hoedje '^' verwijst naar het feit dat we een populatieparameter (zonder '^') schatten.
De concrete uitkomst ('schatting') $\bar{x}$ bij monitoring zal afhangen van de concrete steekproef en dus van de steekproefgrootte en andere design-kenmerken.
Een schatter heeft dus een kans(dichtheids)distributie (met een verwachte waarde (gemiddelde) $E[{\hat{\mu}}]$ en een variantie $\sigma^2_{\hat{\mu}}$). Deze distributie hangt af van steekproefgrootte en andere design-kenmerken.
We spreken van een 'onvertekende schatter' als de verwachte waarde van de schatter ^[De verwachte waarde is het gemiddelde van de schattingen bekomen uit alle mogelijke steekproeven volgens een bepaalde design.] gelijk is aan de waarde $\mu$ van de populatieparameter die door de schatter wordt geschat.
We werken in principe steeds met onvertekende schatters.

De twee aspecten waarover we controle willen voor uitspraken over de toestand, zijn de foutenmarge (~ precisie) en het betrouwbaarheidsniveau.
De grenzen die we er aan opleggen noemen we de **instelwaarden** (een ondergrens voor de informatiekwaliteit).


### De foutenmarge

De 'precisie' van schatters (schattingen) heeft betrekking op de *foutenmarge* van de schatting, gegeven alle kenmerken van de steekproefopzet.
Door een aselecte steekproefbenadering en een 'design-based inferentie' te gebruiken, kunnen we *betrouwbaarheidsintervallen* bekomen die effectief betrekking hebben op alle Vlaamse locaties van een type en typegroep.
Het betreft een betrouwbaarheidsinterval rondom de geschatte waarde op basis van de steekproef.

Meer concreet bepaalt de foutenmarge het bereik rond de steekproefschatting (steekproefgemiddelde) waarvan we aannemen dat de populatieparameter (spatiaal of spatiotemporeel gemiddelde van de volledige populatie) erbinnen ligt.
Dat bereik is dan ${\bar{x}} \pm {foutenmarge}$.
De foutenmarge is dus de helft van het betrouwbaarheidsinterval indien dit interval symmetrisch is.

Voor de foutenmarge kan een *instelwaarde* gekozen worden, dus we geven aan welke foutenmarge we niet wensen te overschrijden (i.e. we willen voldoende precisie).
We maken onderscheid tussen een 'gewenste' foutenmarge om niet te overschrijden (een gewenst scenario) en een 'maximale' foutenmarge (een minimaal scenario: wat minimaal nodig is aan informatie voor een zinvolle betekenis).

De foutenmarge wordt dus uitgedrukt op de **schaal** waarop de milieuvariabele wordt geanalyseerd, bv.:

- *op de originele schaal*: de foutenmarge is bv. een vast bereik op de schaal van een waterstand.
Een instelwaarde ervoor (maximale foutmarge) is een constante, rechtstreeks te interpreteren op deze schaal;
- *op de logaritmisch getransformeerde schaal*: hetzelfde geldt als voor de originele schaal, maar dan voor de logaritmisch getransformeerde milieuvariabele.
    - Een belangrijke toepassing is het 'constant maken' van een instelwaarde die relatief wordt uitgedrukt, bv. 'de foutenmarge mag maximaal 10% zijn'.
    Op de originele schaal betekent dit een toegelaten foutenmarge die toeneemt met de geschatte waarde (schatting).
    In het voorbeeld is dat dus $({\bar{x}} + 0.10 \cdot {\bar{x}}) - {\bar{x}}$ op de originele schaal, oftewel $0.10 \cdot {\bar{x}}$ en dus afhankelijk van de waarde van ${\bar{x}}$.
    Vertaald naar de logschaal, in positieve richting ^[Op de logschaal is de foutenmarge het kleinst in de positieve richting (vanaf de schatting), en dus het strengst / meest conservatief. Daarom werken we met deze waarde.], wordt de foutenmarge *onafhankelijk* van de waarde van ${\bar{x}}$:
    
$$\log_{10} ({\bar{x}} + 0.10 \cdot {\bar{x}}) - \log_{10} {\bar{x}} = \log_{10} 1.10 + \log_{10} {\bar{x}} - \log_{10} {\bar{x}} = \log_{10} 1.10$$

Voor het hoofdmeetnet _SURF_03.4_ in het oppervlaktewatermeetnet (eutrofiëring via oppervlaktewater) zijn de primaire milieuvariabelen of 'doelvariabelen' (= toestand- en trenduitspraken gewenst) de volgende:

- deelmeetnet _SURF_03.4_lentic_ (stilstaande wateren): concentraties van NO~3~^-^-N en P~tot~
- deelmeetnet _SURF_03.4_lotic_ (stromende wateren): concentraties van NO~3~^-^-N en PO~4~^3-^-P

In al deze gevallen is gekozen om de analyse op de logschaal te doen en de instelwaarden relatief te bepalen.
Een relatieve foutenmarge, uitgedrukt als fractie $f$ (tussen 0 en 1), wordt in de log~10~-schaal vertaald als een absolute (constante) foutenmarge van $log_{10} (1 + f)$.

In de notaties die volgen, zullen we log-transformaties niet vermelden, maar veronderstellen we dat $\hat{\mu}$, $\mu$ enzovoort op zich reeds verwijzen naar de log-getransformeerde variabele.


### Het betrouwbaarheidsniveau van de foutenmarge: $1 - \alpha$

Het betrouwbaarheidsniveau is de betrouwbaarheid van de uitspraak: 'de populatieparameter ligt in het bereik ${\bar{x}} \pm {foutenmarge}$'.
Dit wordt uitgedrukt als een **kans** (tussen 0 en 1). We willen dat deze kans hoog genoeg is om betrouwbare uitspraken te doen. ^[
De kans drukt uit welk aandeel van steekproeven de populatieparameter effectief zouden omvatten met het betrouwbaarheidsinterval -- mocht je herhaaldelijke steekproeven kunnen nemen, wat niet het geval is.]

Het complement van het betrouwbaarheidsniveau is de type I fout ($\alpha$), i.e. de kans dat de bovenstaande uitspraak verkeerd is.

Ook voor het betrouwbaarheidsniveau $1 - \alpha$ kan een instelwaarde gekozen worden.
In de MNM wordt veelal gekozen voor $1 - \alpha = 0.90$.



### De distributie (kansdichtheidsfunctie) van de schatter als sleutel tot het vraagstuk

We legden al uit dat een onvertekende schatter een distributie kent met volgend gemiddelde en variantie:

$$\hat{\mu} \sim (\mu,\sigma^2_{\hat{\mu}})$$

Omdat schatters, zoals spatiale of spatiotemporele gemiddelden, berekend worden over een groter aantal observaties, zijn onze schatters bij goede benadering normaal verdeeld:

$$\hat{\mu} \sim \mathcal{N} (\mu,\sigma^2_{\hat{\mu}})$$

Dit impliceert dat de (tweezijdige) foutenmarge op een schatting $\bar{x}$, met een betrouwbaarheidsniveau $1 - \alpha$ als volgt kan worden uitgedrukt:

$$foutenmarge = log_{10} (1 + f) = z_{1 - {\alpha}/2} \cdot \sigma_{\hat{\mu}}$$

waarbij $z_{1 - {\alpha}/2}$ het ${1 - {\alpha}/2}$ percentiel is van de standaard normale verdeling $\mathcal{N} (0, 1)$.

Met andere woorden, we kennen de relatie tussen de foutenmarge, het betrouwbaarheidsniveau en de standaardafwijking $\sigma_{\hat{\mu}}$ van de schatter.
Nu is het zo dat de spatiale en temporele **steekproefgrootte** (samen met overige design-kenmerken) een belangrijke invloed hebben op de variantie $\sigma^2_{\hat{\mu}}$ van de schatter.

Voor een steekproefgrootteberekening is het dus belangrijk om de variantie van de typegroepschatter te ontbinden in deelcomponenten die bepaald worden door de design, waarbij ook het verband met de spatiale en temporele steekproefgrootte duidelijk wordt.
Door de foutenmarge en het betrouwbaarheidsniveau in te stellen, stellen we (gezien de bovenstaande formule) een na te streven waarde in voor $\sigma_{\hat{\mu}}$.
Dat zal zich doorvertalen naar de verschillende deelaspecten van de design waarover we controle hebben.


### Minimum detecteerbaar verschil voor een toets

Ter informatie voegen we ook het verband toe tussen een relatieve foutenmarge $f$ (tweezijdig) en een relatief detecteerbaar verschil $\delta$ voor een eenzijdige toets met power $\pi$ (de kans op statistisch significante overschrijding van een grenswaarde).

In de logschaal:

$$\log_{10}(1 + \delta) = \sigma_{\hat{\mu}} \cdot (z_{1 - \alpha} + z_{\pi}) = \frac{\log_{10}(1 + f)}{z_{1 - \alpha / 2}} \cdot (z_{1 - \alpha} + z_{\pi})$$

Zodat:

\begin{equation}
\delta = (1 + f)^\frac{z_{1 - \alpha} + z_{\pi}}{z_{1 - \alpha / 2}} - 1
(\#eq:rel-detectable-diff)
\end{equation}



## Keuzes in het meetnetontwerp

Meerdere van onderstaande keuzes zijn reeds gemaakt in het verleden.
Daarvoor verwijzen we naar @wuyts_meetplannen_2024 en tevens enkele conceptrapporten [@vanderhaeghe_meetnetten_2018; @vanderhaeghe_meetnetten_2019].

### Types en typegroepen

Hoewel we de steekproefgrootte willen bepalen in functie van kwaliteitseisen op het typegroepniveau, volgen we in de MNM een steekproefstrategie die voor elk type een (minder nauwkeurige) schatting mogelijk maakt, door te stratificeren volgens type.
Dit geeft veel flexibiliteit naar veranderingen in de afbakening van typegroepen, de veranderende interesse in verschillende types en in de wijze waarop de typegroepschatter wordt gedefinieerd (door gelijke of ongelijke weging van types).
Meer achtergrond hierbij wordt gegeven in @vanderhaeghe_meetnetten_2018.

Concreet stellen we de typegroepschatter in dit rapport voor als $\hat{\mu}$ en de typeschatter als $\hat{\mu}_{type}$.

In het algemeen bestrijkt de ruimtelijke doelpopulatie van MNM-meetnetten wel wat types, en dan gaan we voor de steekproefgrootteberekeningen uit van een 'gemiddeld type' en een 'gemiddelde typegroep', eerder dan te werken op maat van elk specifiek type of typegroep.
Dit heeft meerdere redenen: maatwerk op typeniveau vergt veel data om robuuste inschattingen te doen van de variantiecomponenten (zie verder), zodat het risico bestaat op schijnbare verschillen.
Door de types te poolen, zal de gemiddelde uitspraak over nodige aantallen in ruimte en tijd robuuster zijn.
De typegroepen liggen niet definitief vast (zie hoger), en hun enige rol hier is dan ook de aanname van de (gemiddelde) grootte van één typegroep in termen van aantal types.

### Spatiotemporeel meetnetontwerp {#spatiotemporeel}

In de deelmeetnetten _SURF_03.4_lentic_ (stilstaande wateren) en _SURF_03.4_lotic_ (stromende wateren) in het oppervlaktewater gaan we uit van herhaalde metingen per locatie binnen een jaar (of een seizoen), én per locatie van één extra set herhaalde metingen in het daaropvolgende jaar.
Voor de toestandsbepaling op niveau Vlaanderen zal een aantal herhalingen per locatie wenselijk zijn in de mate dat de temporele variatie op één locatie beduidend groter is dan de spatiale variatie tussen locaties.
Tevens komen herhalingen de locatiespecifieke trendbepaling ten goede, omdat trendbepalingen bij voorkeur op locatiebasis gebeuren en de temporele variatie effect heeft op de precisie van de trendparameter.
Tot slot laten de herhalingen toe om met een beperkte precisie locatiespecifieke karakteristieken te schatten voor een (sub)jaarperiode, zoals het gemiddelde of een kwantiel; evenwel is dit niet het doel van de MNM, die het Vlaamse niveau beogen.

Ondanks het feit dat we met de bestaande dataset minder informatie hebben over tussen-jaarvariatie op locatiebasis, proberen we deze te schatten in functie van een periodic rotational pattern op jaarbasis met een cyclus van 6 jaar (patroon [2-4] [^revisit_pattern]), met herhaalde metingen binnen één jaar.
In deze context willen we het aantal locaties en aantal herhalingen binnen één jaar optimaliseren.

[^revisit_pattern]:
De notatie voor herbezoekpatronen is conform @mcdonald_review_2003.
Een herbezoekpatroon $[x-y]$ betekent voor elke locatie: $x$ perioden bemonsteren, daarna $y$ perioden niet bemonsteren, en dit blijven herhalen daarna.
Het aantal panels is dan $x + y$.

De ruimtelijke doelpopulatie van elk deelmeetnet is bepaald door een lijst van types, die elk een andere ruimtelijke verspreiding hebben.
De steekproefeenheden zijn plassen in het geval van deelmeetnet _SURF_03.4_lentic_, en waterloopsegmenten (type 3260) of habitatvlekken (type 7220) in het geval van deelmeetnet _SURF_03.4_lotic_.

De temporele doelpopulatie hangt af van de primaire milieuvariabele (doelvariabele):

- deelmeetnet _SURF_03.4_lentic_, concentratie NO~3~^-^-N: 1e kwartaal (januari - maart)
- deelmeetnet _SURF_03.4_lentic_, concentratie P~tot~: zomerhalfjaar (april - september)
- deelmeetnet _SURF_03.4_lotic_, concentratie NO~3~^-^-N: zomerhalfjaar (april - september)
- deelmeetnet _SURF_03.4_lotic_, concentratie PO~4~^3-^-P: zomerhalfjaar (april - september)



## Definitie van de typegroepschatter

We definiëren de typegroepschatter ${\hat{\mu}}$ als het gemiddelde van de typeschatters:

$${\hat{\mu}} = \frac{1}{n_{types}} \cdot \sum_{type}{\hat{\mu}_{type}}$$

Met $n_{types}$ het aantal types in de typegroep.
Voor de beschouwde meetnetten is dit heel klein: 2 types per typegroep bij _SURF_03.4_lentic_ en 1 per typegroep bij _SURF_03.4_lotic_.

De typeschatter $\hat{\mu}_{type}$ vertegenwoordigt het spatiotemporele gemiddelde voor één zesjaarperiode in overeenstemming met bovenvermelde design, waarbij voor elke locatie een drietrapsaggregatie gebeurt (trap 1: locatie; trap 2: herhaling tussen twee opeenvolgende jaren; trap 3: herhaling binnen een jaar).

$$\hat{\mu}_{type} = \frac{1}{n} \cdot \frac{1}{2} \cdot \frac{1}{m} \cdot \sum_{loc}\sum_{yr = 1}^2\sum_{rep}{x_{loc,yr,rep}}$$

Met:

- $n$: het totaal aantal locaties voor een type;
- $m$: het aantal metingen per jaar op dezelfde locatie (zg. herhalingen);
- $x_{loc,yr,rep}$: steekproefwaarde voor locatie $loc$, jaar $yr$ en herhaling (tijdstip) $rep$, voor een type.

Het totaal aantal locaties voor een (gemiddelde) typegroep, $n_{tg}$, is bepaald door:

\begin{equation}
n_{tg} = n \cdot n_{types}
(\#eq:nlocs-typegroup)
\end{equation}


## Samenstelling van de variantie van de typegroepschatter

We herhalen uit de literatuur [bv. @cochran_sampling_1977; @de_gruijter_sampling_2006] de variantie van de schatter voor het gemiddelde $\mu_y$ van een variabele $y$ in een gestratificeerd design, i.e. over (alle) $k$ strata (die allemaal worden bemeten), waarbij elk stratum een gelijk aandeel krijgt (volgend uit design of wegens vastgelegde gewichten) en waarbij we als vereenvoudiging een vaste variantie voor de strata $Var[ \hat{\mu}_{y,i}]$ veronderstellen.

$$
\begin{aligned}
Var \left[ \hat{\mu}_y \right]
&= Var \left[ \frac{1}{k} \cdot \sum_{i=1}^k{\hat{\mu}_{y,i}} \right] \\
&= \frac{1}{k^2} \cdot \sum_{i=1}^k{Var \left[ \hat{\mu}_{y,i} \right]} \\
&= \frac{1}{k^2} \cdot k \cdot Var \left[ \hat{\mu}_{y,i} \right] \\
&= \frac{1}{k} \cdot Var \left[ \hat{\mu}_{y,i} \right]
\end{aligned}
$$

We passen dit verband toe in de onderstaande afleiding.

Wegens de definitie van de typegroepschatter ${\hat{\mu}}$ en omdat alle types van een typegroep worden bemeten, geldt het volgende verband tussen diens variantie $\sigma^2_{\hat{\mu}}$ en de variantie $\sigma^2_{\hat{\mu}_{type}}$ van de typeschatter ${\hat{\mu}_{type}}$ (dat een gemiddeld type in een typegroep vertegenwoordigt):

\begin{equation}
\sigma^2_{\hat{\mu}} = \frac{1}{n_{types}} \cdot \sigma^2_{\hat{\mu}_{type}}
(\#eq:vartg)
\end{equation}

Met:

\begin{equation}
\sigma^2_{\hat{\mu}_{type}} = \frac{1}{n} \cdot (\sigma^2_s + \frac{1}{2} \cdot (\sigma^2_y + \frac{1}{m} \cdot \sigma^2_t))
(\#eq:varty)
\end{equation}

Met:

- $\sigma^2_s$: de *spatiale variantie* (variabiliteit tussen de locaties) van het locatiespecifieke gemiddelde van twee opeenvolgende jaren, voor één (gemiddeld) type in een zesjaarperiode;
- $\sigma^2_y$: de _temporele variantie tussen twee opeenvolgende jaargemiddelden_ op _dezelfde locatie_;
- $\sigma^2_t$: de _temporele variantie_ van de metingen _in hetzelfde jaar_ op _dezelfde locatie_.

We maken in deze benadering geen onderscheid in variantieverschillen tussen verschillende types en tussen verschillende typegroepen; het gaat om een gemiddelde inschatting.
Het verband tussen de standaardfout van de typeschatter en de typegroepschatter kwam reeds aan bod in @vanderhaeghe_meetnetten_2018.

Formule \@ref(eq:varty) voor de variantie van de typeschatter is gebaseerd op een drietraps-design: op elke locatie uit de steekproef van locaties (trap 1) wordt een temporele steekproef van twee opeenvolgende jaren getrokken (trap 2), en vervolgens uit elk jaar een temporele steekproef van herhalingen binnen het jaar (trap 3) [cf. @de_gruijter_sampling_2006; @sarndal_model_1992; @lohr_sampling_2010].
We gebruiken hier de formule op basis van de variantieparameter van de typeschatter, eerder dan de meer complexe schatter ervan, die eventueel ook rekening houdt met eindige-populatiecorrecties [@cochran_sampling_1977; @onkelinx_ontwerp_2008; @de_gruijter_sampling_2006].
Bij steekproefgrootteberekeningen is eindige-populatiecorrectie immers niet noodzakelijk; zonder deze correctie bekomen we een meer conservatieve inschatting.

Merk op dat we in trap 3 _niet_ uitgaan van synchrone bemonstering van locaties binnen een jaar, maar per locatie van (andere) random tijdstippen gelegen in de temporele doelpopulatie van het jaar.
Vereenvoudigd voorgesteld komt de aanpak volgens paragraaf \@ref(spatiotemporeel) nochtans neer op bemonstering van de betrokken locaties in _dezelfde_ tijdsvakken van het jaar, cf. een pure panel voor dat jaar.
Voor een pure panel geldt een andere variantieschatter [cf. @de_gruijter_sampling_2006: p. 225].
In de praktijk gaat het hier echter over een systematische verdeling van de betrokken locaties over een veelheid aan mogelijke tijdstippen (dagen) binnen het jaar, waarbij een groot deel van de dagen van de temporele doelpopulatie (namelijk de meeste weekdagen) daarvoor gebruikt worden.
Verschillende locaties worden dus toch vooral op andere momenten bemeten.
Deze opzet is ook aanwezig in de datasets die we zullen gebruiken, zodat we de dit aspect van de formules kunnen toepassen.

<!-- XXXXXX werkpunt om verder te bekijken: -->

Anderzijds houden de formules geen rekening met het feit dat de voor de locaties beschikbare jaarduo's in trap 2 elkaar overlappen (met één gemeenschappelijk jaar).
Het is op dit moment niet helemaal duidelijk of dit wel nodig is.
De toekenning van jaarduo's gebeurt namelijk at random per locatieniveau, onafhankelijk van andere locaties, en dit is wat in een getrapt design verondersteld wordt.
Ook passen we geen temporele stratificatie toe, waardoor geen conflict optreedt met overlappende jaarduo's.
De temporele populatie van jaarduo's waaruit er één wordt getrokken, heeft dus onderlinge overlappen.
Of we dit inderdaad mogen negeren, is nog niet helemaal duidelijk.

We wensen van $\sigma^2_s$, $\sigma^2_y$ en $\sigma^2_t$ een schatting te bekomen zodat we het totaal aantal locaties $n$ en aantal herhalingen $m$ kunnen bepalen in functie van de gewenste nauwkeurigheid (zie instelwaarden) van de typegroepschatter.
We zullen dit doen door met een eenvoudig model deze variantiecomponenten te schatten.
Bemerk dat we bij monitoring (en ook bij een steekproefgrootteschatting via steekproefsimulatie) een design-based inferentie beogen, wat aan de basis ligt van de bovenstaande formules [zie @vanderhaeghe_meetnetten_2018 voor een rekenvoorbeeld].

## Bepaling van steekproefgroottes

Vooraf merken we op dat steekproefgroottebepaling steeds een inschatting blijft.
Ook al kunnen componenten van variabiliteit worden geschat op basis van bestaande data, deze zijn geen garantie voor de toekomstige waarden en het blijft dan ook een inschatting.
Het verdient daarom aanbeveling om conservatief te blijven, enerzijds door uit te gaan van simple random sampling voor oneindige populaties; anderzijds kan het nuttig zijn om het effect na te gaan van een onderschatting van $\sigma^2_s$ en $\sigma^2_t$.

Op basis van de eerdere vergelijkingen kunnen we het aantal locaties op typegroepniveau $n_{tg}$ en het aantal herhalingen per jaar $m$ rechtstreeks uitdrukken in functie van:

- de variantie van de typegroepschatter $\sigma^2_{\hat{\mu}}$, waarvoor we de maximale waarde zelf invullen;
- de varianties $\sigma^2_s$ en $\sigma^2_t$ op typeniveau, die we schatten op basis van data.

Immers, uit \@ref(eq:varty) volgt dat:

$$n = \frac{\sigma^2_s}{\sigma^2_{\hat{\mu}_{type}}} + \frac{1}{2} \cdot \frac{\sigma^2_y}{\sigma^2_{\hat{\mu}_{type}}} + \frac{1}{2 \cdot m} \cdot \frac{\sigma^2_t}{\sigma^2_{\hat{\mu}_{type}}}$$

Zodat (via \@ref(eq:vartg) en \@ref(eq:nlocs-typegroup)):

\begin{equation}
n_{tg} = \frac{\sigma^2_s}{\sigma^2_{\hat{\mu}}} + \frac{1}{2} \cdot \frac{\sigma^2_y}{\sigma^2_{\hat{\mu}}} + \frac{1}{2 \cdot m} \cdot \frac{\sigma^2_t}{\sigma^2_{\hat{\mu}}}
(\#eq:ntg-ifv-m)
\end{equation}

Het aantal locaties per type kan steeds worden afgeleid uit \@ref(eq:nlocs-typegroup).

Analoog bekomen we uit \@ref(eq:varty) het aantal herhalingen:

$$m  = \frac{\sigma^2_t}{2 \cdot n \cdot \sigma^2_{\hat{\mu}_{type}} - 2 \cdot \sigma^2_s - \sigma^2_y} = \frac{\sigma^2_t}{2 \cdot n_{tg} \cdot \sigma^2_{\hat{\mu}} - 2 \cdot \sigma^2_s - \sigma^2_y}$$

We bekomen dus een functieverband tussen $n_{tg}$ en $m$, maar nog geen unieke uitkomst.

Naast praktische en verdere statistische overwegingen, is een klassieke manier om één uitkomst te kiezen deze op basis van kostminimalisering.
Als we $C_s$ definiëren als de kost om één locatie toe te voegen aan de steekproef zonder metingen (spatiale eenheidsprijs), en $C_t$ als de kost om één herhaling (meting) te doen van een steekproeflocatie (temporele eenheidsprijs; inclusief gerelateerde kosten zoals vervoer, chemische analyse ...), dan is de totale kost $C$ voor de data-inzameling in één typegroep:

$$C = n_{tg} \cdot C_s + n_{tg} \cdot m \cdot C_t$$

Door hier \@ref(eq:ntg-ifv-m) in te substitueren, kunnen we vervolgens de waarde $m_{opt}$ voor $m$ bepalen die $C$ minimaliseert:

$$m_{opt} = \frac{\sigma_t}{\sqrt{2 \cdot \sigma^2_s + \sigma^2_y}} \cdot \sqrt{\frac{C_s}{C_t}}$$

Bemerk hoe in deze formule de temporele en spatiale variabiliteit omgekeerd op het aantal herhalingen inwerken t.o.v. de spatiale en temporele eenheidsprijzen.

Substitutie van $m_{opt}$ in \@ref(eq:ntg-ifv-m) levert dan het aantal locaties voor één typegroep.




