rdata_set <- c(
  "n2khab_data_checksums_reference",
  "versions_required",
  "schemes",
  "targetpops",
  "modules",
  "submodules",
  "domains",
  "module_domains",
  "module_scheme_props",
  "mod_scheme_variableset_mainfieldactivity",
  "mod_scheme_vars",
  "activities",
  "activity_sequences",
  "field_activities",
  "field_activity_sequences",
  "biotic_timing",
  "bioticfag_spsubset_type_timing",
  "mod_scheme_field_activity",
  "mod_scheme_actseq_fag",
  "mod_scheme_ps_fag_paneldesign",
  "scheme_ps_variableset_paneldesign",
  "n2khab_types_expanded_properties",
  "n2khab_strata_expanded",
  "n2khab_strata",
  "n2khab_targetpops_expanded",
  "n2khab_targetpops",
  "hmt_pol_stratum_grts_cell_all_n2khab",
  "grts_mh_n2khab_index",
  "domain_grts_n2khab",
  "domainpart_grts_n2khab",
  "stratum_units_non_cell_n2khab",
  "units_non_cell_n2khab_grts",
  "stratum_grts_n2khab",
  "stratum_grts_n2khab_collapsed",
  "stratum_grts_n2khab_phabcorrected",
  "stratum_grts_n2khab_phabcorrected_no_replacements",
  "domain_stratum_nunits",
  "domain_type_nunits",
  "scheme_targetpop_sets",
  "submodule_targetpops_strata",
  "targetpops_strata",
  "scheme_sampling_frame",
  "sp_samplingframes",
  "sp_samplingframe_domain",
  "mhq_sampled_types_per_domain",
  "mhq_mod_dom_scheme_mhqsampletype_no_sample",
  "mhq_mod_dom_type_no_sample",
  "mhq_scheme_category",
  "submod_dom_scheme_ssf_stratum_nunits",
  "module_domain_schemes",
  "module_schemes",
  "module_targetpops",
  "submodule_domain_scheme_typestats",
  "submodule_domain_scheme_stratumstats",
  "submodule_domain_scheme_ps_designattr",
  "module_domain_scheme_ps_stratum_target_sample_size",
  "module_domain_scheme_ps_stratum_sample_size",
  "mod_scheme_targetfieldactivity",
  "scheme_ps_target_paneldesign",
  "mod_scheme_yrs_moco_ps",
  "mhq_samples",
  "scheme_moco_ps_dom_stratum_sample_size",
  "scheme_moco_ps_stratum_dom_spsamples",
  "scheme_moco_ps_stratum_sppost_spsamples_spares",
  "scheme_moco_ps_stratum_sppost_spsamples",
  "scheme_moco_ps_stratum_sppost_spsamples_sf",
  "scheme_moco_ps_stratum_sppost_spsamples_spares_sf",
  "samplinglocations_sf",
  "vbi_overlaps",
  "scheme_moco_ps_spsubset_panel_calendar",
  "scheme_moco_ps_spsubset_fas_stratum_sppost_panelmemship",
  "scheme_moco_ps_spsubset_targetfag",
  "scheme_moco_ps_spsubset_fag_stratum_sppost_spsamples_calendar",
  "scheme_moco_ps_spsubset_targetfag_stratum_sppost_spsamples_calendar",
  "fag_stratum_grts_calendar",
  "fag_grts_calendar",
  "cal_0.14.0_continuation",
  # exporting specific functions:
  "verify_n2khab_data",
  "add_point_coords_grts",
  "filter_grtsraster_by_address",
  "get_level3replacement_cellnrs",
  "convert_level0_to_level3",
  "collapse_strata"
)

if (params$save_rdata) {
  module_suffix <- str_c("_", str_flatten(modules$code_short))
  phabcorr_suffix <- ifelse(
    params$phab_correct,
    "",
    "_nophabcorrection"
  )
  save(
    list = rdata_set,
    file = file.path(
      datapath,
      "binary/results",
      str_c("objects", module_suffix, phabcorr_suffix, ".RData")
    )
  )
}

